### ISSUE TITLE
Eclipse reports Type mismatch for @Deprecated class

### ISSUE THREAD

**Issue by hd42** [eclipse-jdt/eclipse.jdt.core#1412] opened 2023-09-21 14:00 UTC
We have a situation that can be simplified to the following case:

1.) An abstract class with a generic type:
```
public abstract class AbstractClass<T> {}
```

2.) An annotation interface that references that class:
```
public @interface AnnotationWithClassValue {
	Class<? extends AbstractClass<?>> value();
}
```

3.) Two classes referencing each other:
3.a) A concrete class extending the abstract class:
```
//Adding @Deprecated here fixes the bug
//@Deprecated
public class ConcreteClass extends AbstractClass<AnnotatedClass> {}
```

3.b) A class annotated with the annotation that is marked as deprecated:
```
@Deprecated
@AnnotationWithClassValue(ConcreteClass.class) //Type mismatch: cannot convert from Class<ConcreteClass> to Class<? extends AbstractClass<?>>
public class AnnotatedClass {}
```

Editing any of the classes clears the error till the next clean build, which restores it. Marking the `ConcreteClass` as `@Deprecated` also resolves the issue.

The problem appeared when we moved a project from Java 8 to Java 11, remains with Java 17 and vanishes when returning the project to Java 8.

I can reproduce the error in 4.28 and 4.29.

I assume this might be related to  #1399 and/or #189

**Comment by stephan-herrmann** [comment] 2023-09-21 19:46
There is _some_ similarity to #1399 indeed, as both issues are caused by annotations that cause an unfortunate order of compilation steps.

Unlike #1399 this issue is not a recent regression, but indeed triggered by raising compliance to 9 or greater. Since that version, deprecation warnings are supposed to show `since` and `forRemoval` values. As we are trying to report this while resolving a super type reference, we are not ready to resolve the annotation.

Perhaps, we can defer just that problem reporting without further upsetting processing order.

**Comment by hd42** [comment] 2023-09-25 09:15
Is this something that will be fixed for 23.12 or maybe even for older releases? It blocks our migration to Java > 8. Is there anything we can do to help without understanding the JDT compile process?

**Comment by iloveeclipse** [comment] 2023-09-25 09:39
> Is this something that will be fixed for 23.12

May be, no guarantee. The best thing one can do (if the feature is needed) is to provide patch & test as PR.

> or maybe even for older releases?

No, there are no maintenance releases anymore.

**Comment by laeubi** [comment] 2023-09-27 04:20
> The best thing one can do (if the feature is needed) is to provide patch & test as PR

Are there any hints where to look at just in case someone try to provide a patch?

**Comment by stephan-herrmann** [comment] 2023-09-28 15:11
> Are there any hints where to look at just in case someone try to provide a patch?

I didn't consider this a good first issue, because tweaking the order of compilation steps is a very fragile issue.
For that reason I had already assigned the issue to myself :)

**Closed** 2023-10-12 20:36 UTC
Labels: bug, compiler
