### ISSUE TITLE
Search in 4.30 sometimes finds nothing

### ISSUE THREAD

**Issue by cdietrich** [eclipse-jdt/eclipse.jdt.core#1488] opened 2023-10-13 20:05 UTC
Xtexts Xbase content assist uses jdt search to provide proposals for jdt tyes
beginning with 4.30 we see regular test fails in
mwe

https://github.com/eclipse/mwe/issues/270

here are the trace logs for good and bad testcase

[goodcase.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12898453/goodcase.txt)
[badcase.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12898454/badcase.txt)

i have no clue how to start investigating

**Comment by LorenzoBettini** [comment] 2024-05-21 16:54
Anyone from JDT?
Can that be related to some synchronization issues introduced in JDT recently (some of which I helped reverting)?

**Comment by iloveeclipse** [comment] 2024-05-21 17:05
I believe there were some refactorings in the search code, @jukzi : could you please check if they were done in 4.30 time frame?

@cdietrich, @LorenzoBettini : could you try to provide **stable** test case that would fail? Or test setup that would reproduce the problem more reliably as "sometimes"?

**Comment by LorenzoBettini** [comment] 2024-05-21 17:13
@iloveeclipse Unfortunately that's the real problem: it happens sometimes and in the CI :'(

**Comment by jukzi** [comment] 2024-05-21 17:15
I am not aware of any search refactorings in JDT where i was involved.

**Comment by LorenzoBettini** [comment] 2024-05-22 13:29
@iloveeclipse some more context: in our UI tests we create projects programmatically. Doing that inside or outside a `WorkspaceModifyOperation` doesn't help. Maybe doing that within a `WorkspaceModifyOperation` seems to increase the chance of failures.

**Comment by LorenzoBettini** [comment] 2024-05-22 14:55
@iloveeclipse I remember I immediately hated that feature in my Eclipse installations, but we never disabled that for tests.

Something like this https://github.com/LorenzoBettini/xtext/commit/428c1e6dbec5d19af293307c20825888331404ee should disable it globally right?

**Comment by iloveeclipse** [comment] 2024-05-22 15:00
> Something like this [LorenzoBettini/xtext@428c1e6](https://github.com/LorenzoBettini/xtext/commit/428c1e6dbec5d19af293307c20825888331404ee) should disable it globally right?

I have a very little understanding about maven / tycho / surefire settings and which one need to be touched to get the desired effect. Add an assert in the test for the VM option (system property) to be set & you will see it.

**Comment by LorenzoBettini** [comment] 2024-05-22 17:09
@iloveeclipse adding that option in `.mvn/maven.config` doesn't change anything; as you said, maybe we should pass it directly to the test plugin.

I see two occurrences in jdt.core

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/75ade7e361012689112090df373e6e833c2c573b/org.eclipse.jdt.core.tests.model/pom.xml#L35

and

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/75ade7e361012689112090df373e6e833c2c573b/org.eclipse.jdt.apt.tests/pom.xml#L36

I'd say the second one is "more" standard. I'll try that

**Comment by jukzi** [comment] 2024-05-22 17:36
> Just in case, are you running with this option: `-DDetectVMInstallationsJob.disabled=true`?

don't waste your time on that - that problem was solved with https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/293

**Comment by jukzi** [comment] 2024-05-22 19:19
I am sure (but still human error prone).
jdt.core itself has multiple random failing tests that sometimes have the same issue of sometimes not finding everything expected. Does not make much sense to analyze downstream projects as long as this random fails are not fixed within JDT.

**Comment by LorenzoBettini** [comment] 2024-05-23 08:21
@iloveeclipse @jukzi That option seems to do something: https://github.com/eclipse/xtext/pull/3063

flakes are less, and they usually succeed after the first attempt.
Build time seems to also have decreased (by a small amount, so it might also be an impression).

It looks like there are still synchronization problems, which shouldn't be there, but at least that job detecting JVM doesn't seem to disturb anymore.

**Comment by iloveeclipse** [comment] 2024-05-23 08:26
@LorenzoBettini : thanks. 
I assume we can close this issue for now, especially we don't have a reproducer to work on. Feel free to open a new ticket if you have more fails or more data.

**Closed by iloveeclipse** 2024-05-23 08:26 UTC
Labels: bug, help wanted, java search

**Comment by LorenzoBettini** [comment] 2024-05-23 08:30
@iloveeclipse In any case; it would be really helpful to have some guidelines on how to properly synchronize with jobs of this kind...

**Comment by iloveeclipse** [comment] 2024-05-23 08:41
@LorenzoBettini : for search, index state is important, so you could do something like
`JavaModelManager.getIndexManager().waitForIndex(true, monitor);`

Or more complex example: 
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/75ade7e361012689112090df373e6e833c2c573b/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AbstractJavaModelTests.java#L4064-L4090
