### ISSUE TITLE
Enclosing method not found on anonymous class compiled by eclipse compiler

### ISSUE THREAD

**Issue by msevcenko** [eclipse-jdt/eclipse.jdt.core#1607] opened 2023-11-16 13:08 UTC
The enclosed test case demonstrates class that when compiled by eclipse 2023-09 compiler, generates invalid bytecode. The test case crashes on "Enclosing method not found" internal error.

The code compiled correctly e.g. in Eclipse 2022-06. And of course in official JDK compiler.

The problem seems to be when using anonymous inner class, in implicit constructor. Such class does not have enclosing method, but should return null, not crash.

Suprisingly, two levels of anonymous classes are needed to reproduce the error.

```
import java.lang.reflect.Method;
import java.util.Iterator;

import org.junit.Assert;
import org.junit.Test;

public class EclipseCompilerProblemReproducerTest {
	
	protected Iterator<Object> field1 = new Iterator<Object>() {
		@Override
		public boolean hasNext() {
			return false;
		}

		@Override
		public Object next() {
			return null;
		}
	};

	protected static Iterator<Object> start() {
		return new Iterator<Object>() {
			
			@SuppressWarnings("unused")
			protected Iterator<Object> field2 = new Iterator<Object>() {
				@Override
				public boolean hasNext() {
					return false;
				}

				@Override
				public Object next() {
					return null;
				}
			};

			@Override
			public boolean hasNext() {
				return false;
			}

			@Override
			public Object next() {
				return null;
			}
			
		};
	}
	
	@Test
	public void test() throws ClassNotFoundException {
		// outer field1 - good
		Method method1 = Class.forName(EclipseCompilerProblemReproducerTest.class.getName() + "$1").getEnclosingMethod();
		Assert.assertNull(method1);
		
		// inner field2 - fails
		Method method2 = Class.forName(EclipseCompilerProblemReproducerTest.class.getName() + "$2$1").getEnclosingMethod();
		Assert.assertNull(method2);
	}

}
```

**Comment by srikanth-sankaran** [comment] 2024-01-31 03:27
@msevcenko For future reference, we prefer snippets of this form without dependencies on junit

```
import java.lang.reflect.Method;
import java.util.Iterator;

public class X {

	protected Iterator<Object> field1 = new Iterator<Object>() {
		@Override
		public boolean hasNext() {
			return false;
		}

		@Override
		public Object next() {
			return null;
		}
	};

	protected static Iterator<Object> start() {
		return new Iterator<Object>() {

			@SuppressWarnings("unused")
			protected Iterator<Object> field2 = new Iterator<Object>() {
				@Override
				public boolean hasNext() {
					return false;
				}

				@Override
				public Object next() {
					return null;
				}
			};

			@Override
			public boolean hasNext() {
				return false;
			}

			@Override
			public Object next() {
				return null;
			}

		};
	}

	public static void main(String[] args) throws ClassNotFoundException {
		// outer field1 - good
		Method method = Class.forName(X.class.getName() + "$1").getEnclosingMethod();
		if (method != null) {
			throw new AssertionError("Enclosing method is non-null: " + method);
		} else {
			System.out.println("Enclosing method is null : good!");
		}

		// inner field2 - fails
		method = Class.forName(X.class.getName() + "$2$1").getEnclosingMethod();
		if (method != null) {
			throw new AssertionError("Enclosing method is non-null: " + method);
		} else {
			System.out.println("Enclosing method is null again : good!");
		}

	}
}
```

This test passes on master, the underlying problem having been fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1905

**Comment by srikanth-sankaran** [comment] 2024-01-31 03:28
Thanks for reporting this. Closing as duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1905

**Closed by srikanth-sankaran** 2024-01-31 03:28 UTC

**Comment by msevcenko** [comment] 2024-01-31 08:01
Thank you for fixing this issue.
