### ISSUE TITLE
Internal compiler error: org.eclipse.jdt.internal.compiler.lookup.SourceTypeCollisionException

### ISSUE THREAD

**Issue by Supun00SL** [eclipse-jdt/eclipse.jdt.core#2435] opened 2024-05-12 13:26 UTC
`Internal compiler error: org.eclipse.jdt.internal.compiler.lookup.SourceTypeCollisionException at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:168)`

  When I was trying to build my project, this error suddenly appeared. The mysterious thing is, I had just created an empty Java class. It means I can't create new Java classes in my project. If I delete this new Java class, the project builds successfully.

This error was appearing top of a Hibernate Meta Model class, 

Other than that, Hibernate meta models showing not found errors,

```
CalendarHolidays_ cannot be resolved to a variable
CalendarWeekendDays_ cannot be resolved to a variable
...
```

```
<dependency>
	<groupId>org.eclipse.jdt</groupId>
	<artifactId>org.eclipse.jdt.core</artifactId>
	<version>3.37.0</version>
</dependency>
``` 

Eclipse Version : 

```
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2023-12 (4.30.0)
Build id: 20231201-2043
```

**Comment by jukzi** [comment] 2024-05-13 07:41
Please add the stacktrace from the error log and describe a minimal reproducer for the problem.

**Comment by jukzi** [comment] 2024-06-25 14:50
Closing due to missing stacktrace

**Closed by jukzi** 2024-06-25 14:50 UTC
Labels: needinfo
