### ISSUE TITLE
GenericsRegressionTest.testBug434044_comment36 fails in I-Builds

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2545] opened 2024-06-10 05:57 UTC
the "capture" index does not match anymore in `testBug434044_comment36 - 1.7`
for example:
https://download.eclipse.org/eclipse/downloads/drops4/I20240608-0320/testresults/html/org.eclipse.jdt.core.tests.compiler_ep433I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
Invalid problem log . ----------- Expected ------------ ----------\n 1. ERROR in EclipseJava8Generics.java (at line 28)\n final Object propertyValue = typedProperty.getBar().doFoo(null);\n ^^^^^\n The method doFoo(String) is ambiguous for the type capture#3-of ? extends EclipseJava8Generics.AbstractFoo<?>\n ----------\n ------------ but was ------------ ----------\n 1. ERROR in EclipseJava8Generics.java (at line 28)\n final Object propertyValue = typedProperty.getBar().doFoo(null);\n ^^^^^\n The method doFoo(String) is ambiguous for the type capture#2-of ? extends EclipseJava8Generics.AbstractFoo<?>\n ----------\n ---------------------- ---------- expected:<...or the type capture#[3]-of ? extends Eclips...> but was:<...or the type capture#[2]-of ? extends Eclips...>

junit.framework.ComparisonFailure: Invalid problem log .
----------- Expected ------------
----------\n
1. ERROR in EclipseJava8Generics.java (at line 28)\n
final Object propertyValue = typedProperty.getBar().doFoo(null);\n
^^^^^\n
The method doFoo(String) is ambiguous for the type capture#3-of ? extends EclipseJava8Generics.AbstractFoo<?>\n
----------\n

------------ but was ------------
----------\n
1. ERROR in EclipseJava8Generics.java (at line 28)\n
final Object propertyValue = typedProperty.getBar().doFoo(null);\n
^^^^^\n
The method doFoo(String) is ambiguous for the type capture#2-of ? extends EclipseJava8Generics.AbstractFoo<?>\n
----------\n

---------------------- ----------
expected:<...or the type capture#[3]-of ? extends Eclips...> but was:<...or the type capture#[2]-of ? extends Eclips...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.checkCompilerLog(AbstractRegressionTest.java:1581)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3586)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3289)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runNegativeTest(AbstractRegressionTest.java:2854)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runNegativeTest(AbstractRegressionTest.java:2843)
at org.eclipse.jdt.core.tests.compiler.regression.GenericsRegressionTest.testBug434044_comment36(GenericsRegressionTest.java:4950)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:59)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by iloveeclipse** [comment] 2024-06-10 06:22
Duplicate of #2537

**Closed** 2024-06-10 07:07 UTC
Labels: bug, regression, test
