### ISSUE TITLE
How to get help

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.core#808] opened 2023-03-04 09:55 UTC
How to get help and where to report bugs from Eclipse? I reported many and none of them are being checked, fixes would be a dream I guess.

**Comment by iloveeclipse** [comment] 2023-03-04 11:06
See https://github.com/eclipse-platform

Since transition to github there is no common bug tracker anymore.

Regarding fixes: well, if the problem is important for some committer, you may have lick and it will be fixed. If not, see https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md how you can try to contribute.

Closing this one, as is is not an actual JDT bug.

**Closed by iloveeclipse** 2023-03-04 11:06 UTC
