### ISSUE TITLE
org.eclipse.jdt.internal.compiler.lookup.TypeBinding.signableName() doesn't honor its contract for anonymous types

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#2142] opened 2024-03-12 10:46 UTC
Using the example of TypeResolveTest.testBug576778 and using a DOM->Binding->IJavaElement chain to get the IJavaElement for the variable:

```java
public void testBug576778_ASTBindings() throws Exception {
	try {
		createJava11Project("P", new String[] {"src"});
		String source =    "package p;\n\n"
				+"public class X {\n"
				+ "  public static void main(String[] args) {\n"
				+ "   var runnable = new Runnable() {\n"
				+ "     public void run() {}\n"
				+ "   };\n"
				+ "   runnable.run();\n"
				+ "  }\n"
				+ "}\n";
		createFolder("/P/src/p");
		createFile("/P/src/p/X.java", source);
		waitForAutoBuild();
		ICompilationUnit unit = getCompilationUnit("/P/src/p/X.java");
		String select = "runnable";
		ASTParser parser = ASTParser.newParser(AST.getJLSLatest());
		parser.setSource(unit);
		parser.setProject(unit.getJavaProject());
		parser.setResolveBindings(true);
		Name node = (Name)new NodeFinder(parser.createAST(null), source.indexOf(select), select.length()).getCoveredNode(); 
		ILocalVariable variable = (ILocalVariable) node.resolveBinding().getJavaElement();
		String signature= variable.getTypeSignature();
		assertEquals("incorrect type", "Qvar;", signature);
	} finally {
		deleteProject("P");
	}
}
```

fails with 
```
java.lang.IllegalArgumentException: new java.lang.Runnable(){}
	at org.eclipse.jdt.core.Signature.createCharArrayTypeSignature(Signature.java:1109)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1305)
	at org.eclipse.jdt.core.dom.VariableBinding.getUnresolvedJavaElement(VariableBinding.java:270)
	at org.eclipse.jdt.core.dom.VariableBinding.getJavaElement(VariableBinding.java:160)
	at org.eclipse.jdt.core.tests.model.TypeResolveTests.testBug576778_ASTBindings(TypeResolveTests.java:1775)
...
```
Indeed, `new java.Runnable(){}` (returned by `ITypeBinding.signableName()` seems not accepted by `createTypeSignature`, however the `ITypeBinding.signableName()` specifies that it's output is supported as input of `createTypeSignature`.
This echo the initial report https://bugs.eclipse.org/bugs/show_bug.cgi?id=576778

So it looks like either `signableName()` returns an incorrect value, or `Signature.createTyeSignature()` should be capable of processing anonymous types.

**Comment by subyssurendran666** [comment] 2024-09-30 08:45
@mpalat could you please assign this ticket to me ?

**Comment by subyssurendran666** [comment] 2024-10-17 16:47
The issue is not reproducible.

The `ITypeBinding.signableName()` returns the signable name as `[j, a, v, a, ., l, a, n, g, ., R, u, n, n, a, b, l, e]`, which is fully compliant with the expectations described in the `Signature.createTypeSignature()` Javadoc.

@mickaelistria  could you please share your thoughts on this matter?

**Comment by mickaelistria** [comment] 2024-10-17 18:52
I don't remember the details and will not be able to dive in anytime soon. So if you think that the issue is either a wrong report, or that it got fixed in between, feel free to close. I'll reopen if needed later.

**Comment by mpalat** [comment] 2024-10-18 01:57
closing on behalf of @subyssurendran666 . @mickaelistria will reopen  if needed later

**Closed by mpalat** 2024-10-18 01:57 UTC
