### ISSUE TITLE
Call hierarchy/references search don't find callers of private methods in referenced libraries

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#375] opened 2022-09-07 08:28 UTC
Using 4.25, try to open Call Hierarchy (or search for references) on org.eclipse.ui.internal.views.log.LogView.doDeleteLog().
If org.eclipse.ui.views.log project is imported as source, there is a caller found.

If the project is **not imported** (but in the target platform), even if "Add all plugins to java workspace scope" is enabled, nothing is found. Same for org.eclipse.ui.internal.views.log.LogView.handleFilter().

Note: the callers are inside internal anonymous classes, may be this is relevant.

**Comment by trancexpress** [comment] 2022-09-07 10:11
Maybe the same as: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566435

**Comment by trancexpress** [comment] 2022-09-07 13:46
Looks like this code checks in the wrong anonymous type:

```
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2668)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3308)
        at org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.visit(MemberDeclarationVisitor.java:330)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1714)
        at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:693)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:484)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:437)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2596)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3308)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2872)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2047)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1363)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1542)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

In particular, the code added for https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127 looks like this:

```
						if (fileName.endsWith("jar") || fileName.endsWith(SuffixConstants.SUFFIX_STRING_class)) { //$NON-NLS-1$
							IOrdinaryClassFile classFile= binaryType.getPackageFragment().getOrdinaryClassFile(binaryType.getTypeQualifiedName() +
									"$" + Integer.toString(occurrenceCount) + SuffixConstants.SUFFIX_STRING_class);//$NON-NLS-1$
							anonType =  classFile.getType();
						}
```

During the call hierarchy computation of ```doDeleteLog()```, ```occurrenceCount``` is ```1``` in this code. This ```1``` is coming from: ```org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.getInTypeOccurrenceCountForBinaryAnonymousType(TypeDeclaration, char[], IJavaElement, int)```

Which was added for: https://bugs.eclipse.org/bugs/show_bug.cgi?id=469965

Here we actually want ```6```, to be in the correct anonymous type. If I set ```occurrenceCount``` "manually" (via the ```Debug Shell``` view), after the call to ```getInTypeOccurrenceCountForBinaryAnonymousType()```, the call hierarchy is computed as expected.

Adding a test for this will be slightly complicated, since we'll need a jar. For an actual fix, no idea yet. I assume we must fix ```getInTypeOccurrenceCountForBinaryAnonymousType()``` to not be a noop. At least during the call hierarchy computation, the method is filling a map with empty strings (since the type is anonymous, the type name is empty...): ```org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.inTypeOccurrencesCounts```.

**Comment by iloveeclipse** [comment] 2022-09-07 14:45
@trancexpress : this reminds me on the hack I wrote few years ago for the bytecode outline view.

The naming of anonymous classes differs depending on compiler & JLS used to compile them, see https://github.com/iloveeclipse/bytecodeoutline/blob/1e91be7e0e3f4d260741fa2ffeac5445bde3cb5c/org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/ui/JdtUtils.java#L535 and https://github.com/iloveeclipse/bytecodeoutline/blob/1e91be7e0e3f4d260741fa2ffeac5445bde3cb5c/org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/ui/JdtUtils.java#L1307

**Additionally** I see now the code doesn't work anymore because we have **nested** classes (NESTMEMBER), and they order is different again. 

I have to fix Bytecode Outline too...

**Comment by trancexpress** [comment] 2022-09-08 06:38
Seems like a direct regression from https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127. Reverting the change in ```MatchLocator.reportMatching(TypeDeclaration, IJavaElement, int, MatchingNodeSet, int)``` results in expected behavior. I'll see if the fix for the bug can be applied only for parentless cases (e.g. lambdas).

**Comment by trancexpress** [comment] 2022-09-08 09:37
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127#c16, as expected the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127 doesn't work if more anonymous types are added to an example.

**Comment by trancexpress** [comment] 2022-09-08 14:43
The current change is not nice, to say the least. But I can't think if anything else so far.

From my POV the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127 is extremely optimistic, and breaks very simple scenarios of searching and call hierarchy computations. This is too much, to fix only very specific cases.

Best case scenario we revert the changes from this file and open a ticket to deal with whatever this change was meant to deal with: https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/diff/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/matching/MatchLocator.java?id=f06de4b999ef266d99070d6e6ee7f897f16a1d0e

With this change reverted, I cannot reproduce a NPE that was reproduced by @stephan-herrmann here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127#c1

Also the ```accept``` method that is implemented in the lambda is not found, with and without the fix.

What **is** fixed by the change is this case:

```
final class MyDistinctOps {
    static <T> MyStatefulOp<T> makeRef() {
        return new MyStatefulOp<T>() {
			@SuppressWarnings("unused")
			@Override
		 	void opEvaluateParallel() {
                TerminalOp<T, Void> forEachOp = ForEachOps.makeRef(t -> {}, false);
			}
    @SuppressWarnings({ "unchecked", "rawtypes", "unused" })
	 MySink<T> opWrapSink(MySink<T> sink) {
           return new MySink.ChainedReference(sink) {

				@Override
				public void accept(Object t) {
                     downstream.accept(t);					
				}
            };
        }
        };
}

interface TerminalOp<E_IN, R> {}
final static class ForEachOps {
    public static <T> TerminalOp<T, Void> makeRef(IY<? super T> action,
                                                  boolean ordered) {
    	return null;
    }

}

abstract static class MyStatefulOp<T> {
	abstract void opEvaluateParallel();
}
}

interface MySink<T> extends IY<T> {
    static abstract class ChainedReference<T, E_OUT> implements MySink<T> {
    protected final MySink<T> downstream;

    public ChainedReference(MySink<T> downstream) {
        this.downstream = downstream;
    }
}
}

@FunctionalInterface
public interface IY<T> {
  public void accept(T t);
}	

```

Computing the call hierarchy / references of ```IY.accept()``` is fixed by the changes for https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127. But to me at least, this is done on accident. If I add more implementers of the interface in the method ```MyDistinctOps.makeRef()```, the call hierarchy / search results are incomplete again. See my comment here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127#c16

I'll keep trying to come up with a solution for ```org.eclipse.jdt.core.tests.model.JavaSearchBugs8Tests.testBug468127_0001()``` that doesn't break trivial cases of anonymous classes. But IMO cleanest would be to revert the change and open a GH issue for bug 468127, where we can "try again" to fix the case in the test (since I don't see any NPE with and without that change). As well as, I'm not sure how a NPE would be prevented by the code.

**Comment by iloveeclipse** [comment] 2022-09-08 15:50
> The current change is not nice, to say the least. But I can't think if anything else so far.
> 
> From my POV the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127 is extremely optimistic, and breaks very simple scenarios of searching and call hierarchy computations. This is too much, to fix only very specific cases.
> 
> Best case scenario we revert the changes from this file and open a ticket to deal with whatever this change was meant to deal with

Yep. After reverting [this patch](https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/51112/6/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/matching/MatchLocator.java) I don't see NPE as described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=468127#c1 *and* it fixes the issue here.

**Closed** 2022-09-19 14:35 UTC
