### ISSUE TITLE
Possible wrong implementation type returning on annotation usage in annotation value

### ISSUE THREAD

**Issue by myatmin** [eclipse-jdt/eclipse.jdt.core#1676] opened 2023-12-04 09:14 UTC
As below annotation value structure, ECJ returning implementation of `AnnotationValue` instated of `AnnotationMirror` for `@ExternalConversation` annotation.

```java
@MapperConfig(componentModel = "spring")
@SpringMapperConfig(externalConversions = @ExternalConversion(sourceType = String.class, targetType = Locale.class))
public interface MapstructConfig {}
```

Sample project can be found [here](https://github.com/mapstruct/mapstruct-spring-extensions/issues/57#issuecomment-1801217416).

Throwing exception is as below
```
java.lang.Exception: java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl cannot be cast to class javax.lang.model.element.AnnotationMirror (org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @183f9933; javax.lang.model.element.AnnotationMirror is in module java.compiler of loader 'platform')
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:406)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:338)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:273)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:188)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:594)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:490)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl cannot be cast to class javax.lang.model.element.AnnotationMirror (org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @183f9933; javax.lang.model.element.AnnotationMirror is in module java.compiler of loader 'platform')
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.mapstruct.extensions.spring.converter.ConverterMapperProcessor.toFromToMappings(ConverterMapperProcessor.java:160)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.mapstruct.extensions.spring.converter.ConverterMapperProcessor.getExternalConversionMappings(ConverterMapperProcessor.java:152)
	at org.mapstruct.extensions.spring.converter.ConverterMapperProcessor.buildAdapterDescriptor(ConverterMapperProcessor.java:137)
	at org.mapstruct.extensions.spring.converter.ConverterMapperProcessor.process(ConverterMapperProcessor.java:101)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 27 more
```

**Comment by kriegaex** [comment] 2023-12-28 04:12
I am experiencing a similar problem when trying to migrate a project using Maven Compiler for annotation proccessing and AspectJ Maven for compilation and aspect weaving to using AspectJ Maven only for both build steps. (AspectJ Compiler is an extended fork of Eclipse Java Compiler.)

No matter how much I put on the processor classpath, the exception always occurs, but only in the ECJ-based AspectJ Compiler (AJC), not in javac via Maven Compiler.

**Comment by kriegaex** [comment] 2023-12-29 03:19
@myatmin, I tried to reproduce your problem outside of Eclipse, modifying your sample POM to use ECJ from Maven Compiler using `<compilerId>eclipse</compilerId>`. No problems there. Can you somehow reproduce this problem from Maven with ECJ, too? Because my own example reproduces from Maven using AspectJ Maven Plugin. But it would be good to have apure ECJ reproducer, too. I do not think it is specific to AJC.

**Comment by kriegaex** [comment] 2023-12-29 03:45
Ok, I have modified the Maven project in which I was experimenting with AJC annotation processing to simply use ECJ for that build step instead, see [branch _jdt-core-1676_](https://github.com/kriegaex/spring-data-jpa/tree/jdt-core-1676). Either clone the repo and switch to that branch or just click the green "Code" button and then "download zip", if you just want that version without the Git history.

Direct ZIP download link:
https://codeload.github.com/kriegaex/spring-data-jpa/zip/refs/heads/jdt-core-1676

The problem occurs during annotation processing in the test compilation phase. To reproduce:

```text
$ mvn -pl spring-data-jpa clean test-compile -e
```

I am attaching the [build log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13790763/build.log).

**Comment by xmourgues** [comment] 2024-02-28 12:57
Hello,
We're stumbling on this issue while using org.hibernate.orm:hibernate-jpamodelgen:6.4.4.Final
Do you have any ETA for when this could be taken into account ?
Or any workaround ?

**Comment by jukzi** [comment] 2024-05-21 08:26
Why do you think javax.lang.model.element.AnnotationValue.getValue() should return a org.eclipse.jdt.internal.compiler.apt.model.AnnotationMirrorImpl instead of  org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl ?

to me it looks more like an error in ConverterMapperProcessor making a wrong assumption.

https://github.com/mapstruct/mapstruct-spring-extensions/blob/84bd656f8a64224496bda9332127ee3b7dc7b566/extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java#L149

**Comment by jukzi** [comment] 2024-05-21 12:43
stacktrace with hibernate annotation processor probably related to some annotation like

`@NamedQueries({ @NamedQuery(name =...`

```
 (org.eclipse.jdt.internal.compiler.apt.model.AnnotationValueImpl is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @65478756; javax.lang.model.element.AnnotationMirror is in module java.compiler of loader 'platform')
	at org.hibernate.processor.annotation.AnnotationMeta.addAuxiliaryMembersForRepeatableAnnotation(AnnotationMeta.java:139)
	at org.hibernate.processor.annotation.AnnotationMeta.addAuxiliaryMembers(AnnotationMeta.java:34)
	at org.hibernate.processor.annotation.AnnotationMetaEntity.init(AnnotationMetaEntity.java:452)
	at org.hibernate.processor.annotation.AnnotationMetaEntity.create(AnnotationMetaEntity.java:188)
	at org.hibernate.processor.HibernateProcessor.handleRootElementAnnotationMirrors(HibernateProcessor.java:496)
	at org.hibernate.processor.HibernateProcessor.processClasses(HibernateProcessor.java:302)
	at org.hibernate.processor.HibernateProcessor.process(HibernateProcessor.java:261)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:406)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:338)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:273)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:188)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jukzi** [comment] 2024-05-21 15:56
for hibernate the error is also in hibernate model gen, but not in JDT:
AnnotationValue is clearly documented to return a `List<? extends AnnotationValue>` - not a `List<? extends AnnotationMirror>`

https://docs.oracle.com/en/java/javase/21/docs/api/java.compiler/javax/lang/model/element/AnnotationValue.html

https://github.com/openjdk/jdk/blob/d999b81e7110751be402012e1ed41b3256f5895e/src/java.compiler/share/classes/javax/lang/model/element/AnnotationValue.java#L36

The code may only work in javac as openjdk may return a List of com.sun.tools.javac.code.Attribute.Compound which randomly implements both  AnnotationMirror and AnnotationValue 

JDT correctly returns a `List<? extends AnnotationValue>` where each AnnotationValue in the List then would return a AnnotationMirror as value.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/a7616421-2402-4a8f-b505-4a94d4271d29)
(screenshot debugging hibernate modelgen https://github.com/hibernate/hibernate-orm/blob/0f8ef48e7bd7a6f5a02cf23e1d1d3bdde0188e52/tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java#L138)

**closing as NOT-JDT**

lessons learned: jdt has a junit test that can be simply adapted to a similar construct: 
1. snippet can be put in
eclipse.jdt.core\org.eclipse.jdt.compiler.apt.tests\resources\targets\model9\q\SomeAnnotatedClass.java
2. asserts can be added to org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.testBug498022b(), 
3. need to create the APt jar first, by exporting
eclipse.jdt.core\org.eclipse.jdt.compiler.apt.tests\apttestprocessors8.jardesc
4. junit test can be run with org.eclipse.jdt.compiler.apt.tests.Java9ElementsTests.testBug498022b(),

**Closed by jukzi** 2024-05-21 15:56 UTC
Labels: invalid

**Comment by kriegaex** [comment] 2024-05-22 08:19
@jukzi, I am surprised you are closing this. Did you try my reproducer from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1676#issuecomment-1871706787? If it works with Javac and fails with ECJ, I would argue that there is a problem in ECJ, after all.

**Comment by JanWiemer** [comment] 2024-05-22 08:26
See https://hibernate.atlassian.net/jira/software/c/projects/HHH/boards/31?search=meta&selectedIssue=HHH-18149

**Comment by kriegaex** [comment] 2024-05-22 08:45
Oh OK, it only works in Javac by chance. I will have to trust you on this. Thanks for the explanation.

**Comment by stephan-herrmann** [comment] 2024-05-22 14:00
> If it works with Javac and fails with ECJ, I would argue that there is a problem in ECJ, after all.

that's a very popular trap to step into :smile:

**Comment by fhackenberger** [comment] 2025-01-09 15:30
So the workaround is to use Hibernate from the 6.2 series, or the (probably fixed) 6.5.3.Final release, which should have the fix included. The complete 6.3 and 6.4 series have that bug present.

**Comment by kriegaex** [comment] 2025-01-10 05:09
@fhackenberger, thanks for the feedback. In my [branch _jdt-core-1676_](https://github.com/kriegaex/spring-data-jpa/tree/jdt-core-1676), I have just given this a quick spin, changing `<hibernate>6.4.0.Final</hibernate>` to `<hibernate>6.6.4.Final</hibernate>` in the parent POM. The build is passing now. This is just evidence, but not proof that it is actually a Hibernate problem. I just want to contribute this quick test without independently confirming your statement, because I did not research in depth. But it looks as if you are right.

**Comment by fhackenberger** [comment] 2025-01-10 08:20
@kriegaex Ah interesting, the [HHH-18149](https://hibernate.atlassian.net/jira/software/c/projects/HHH/boards/31?search=meta&selectedIssue=HHH-18149) issue mentioned that it was backported to 6.5, but didn't mention 6.4 at all. Great to see that the latest 6.4 is also fixed. Thanks for looking into that!

**Comment by kriegaex** [comment] 2025-01-10 08:57
@fhackenberger, you misread my message. I did not say that it works on 6.4. The opposite is true. 6.4 is what Spring Data JPA used while reproducing the problem. 🙂

**Comment by fhackenberger** [comment] 2025-01-10 12:10
@kriegaex Thx for pointing that out, I mistook the 6.6.4 as 6.4.4. Okay so it would still be a question which 6.6 series versions are affected below the 6.6.4.Final which is fine according to you.

**Comment by kriegaex** [comment] 2025-01-10 13:21
I just had a few minutes for a quick test. It should be pretty easy to check the commits for 6.6 and 6.5 back port to find out.
