### ISSUE TITLE
No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range 

### ISSUE THREAD

**Issue by ChiGK** [eclipse-jdt/eclipse.jdt.core#140] opened 2022-06-15 04:09 UTC
This error occurred in project compilation！！！

```
Failed to collect dependencies at org.eclipse.jdt:org.eclipse.jdt.core:jar:3.29.0 -> org.eclipse.platform:org.eclipse.core.resources:jar:3.14.0 -> org.eclipse.platform:org.eclipse.core.expressions:jar:3.5.100 -> org.eclipse.platform:org.eclipse.core.runtime:jar:3.12.0 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range -> [Help 1]
```

**Comment by ChiGK** [comment] 2022-06-15 04:16
There are no more `org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0`  in the Maven repository

**Comment by iloveeclipse** [comment] 2022-06-15 06:09
Duplicate of https://github.com/eclipse-equinox/equinox.bundles/issues/54

**Closed by iloveeclipse** 2022-06-15 06:09 UTC
