### ISSUE TITLE
NPE below LambdaExpression.copy()

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1264] opened 2023-08-03 12:12 UTC
Using latest build I20230802-1800.
Open snippet below in the IDE.
```
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.stream.Stream;

public class Snippet {
	public static void main(String[] args) {
		Collection<File> rootDirectories = new ArrayList<>();
		Stream<Object> directories = rootDirectories.stream()
				.map(dir -> dir.listFiles(File::isDirectory));
		System.out.println(directories);
	}
}
```
Hold "Ctrl" and hover over the "arrows" in lambda expression in the `main()` method.
Exception reported:
```
java.lang.NullPointerException
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.copy(LambdaExpression.java:1125)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.cachedResolvedCopy(LambdaExpression.java:988)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.resolveExpressionExpecting(LambdaExpression.java:1026)
	at org.eclipse.jdt.internal.compiler.lookup.ConstraintExpressionFormula.inputVariables(ConstraintExpressionFormula.java:519)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.lambda$1(InferenceContext18.java:604)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.collectingInnerBounds(InferenceContext18.java:538)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.addJDK_8153748ConstraintsFromFunctionalExpr(InferenceContext18.java:604)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.addJDK_8153748ConstraintsFromExpression(InferenceContext18.java:574)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.addJDK_8153748ConstraintsFromInvocation(InferenceContext18.java:559)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.inferInvocationType(InferenceContext18.java:423)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedGenericMethodBinding.computeCompatibleMethod18(ParameterizedGenericMethodBinding.java:273)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedGenericMethodBinding.computeCompatibleMethod(ParameterizedGenericMethodBinding.java:92)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:841)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:798)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod0(Scope.java:1767)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod(Scope.java:1668)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getMethod(Scope.java:3094)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:1023)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:838)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:393)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1508)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1633)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1086)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinks(JavaElementHyperlinkDetector.java:124)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
```

**Comment by iloveeclipse** [comment] 2023-08-03 12:16
@srikanth-sankaran : this seem to be a regression from ed4bdac88b5b96e7bbdebc86d54fff2bce23325e. 
Also see issue #1263 which could be related?

**Comment by srikanth-sankaran** [comment] 2023-08-04 04:27
> Also see issue #1263 which could be related?

Likely a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1195

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1195#issuecomment-1612277800 for a growing list of duplicates.

It matches the scenario that the concerned method uses pattern matching instanceof expression.

**Comment by iloveeclipse** [comment] 2023-08-04 09:19
> Likely a duplicate of #1195

Not sure if it is really a duplicate, since we have here NPE in the "lambda copy" code that was added to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=571467.

**Comment by srikanth-sankaran** [comment] 2023-08-04 11:14
> > Likely a duplicate of #1195
> 
> 
> 
> Not sure if it is really a duplicate, since we have here NPE in the "lambda copy" code that was added to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=571467.

I meant #1263 is likely a duplicate of #1195 not the present one.

**Closed** 2023-08-07 09:09 UTC
Labels: bug, regression
