### ISSUE TITLE
Code not compiling with JDT but ok with javac

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.core#2850] opened 2024-08-22 08:17 UTC
This code is not compiling with JDT, error "Type Object cannot be safely cast to Test.ListA<? extends Test.A>" but with javac it ok

```
public class Test {

  public static void main(String[] args) {
    final var i = new Object();
    if (i instanceof ListA<? extends A> list) {
      System.out.println(list);
    }
  }

  interface ListA<T extends A> {

  }

  class A {

  }
}
```

**Comment by jukzi** [comment] 2024-08-22 11:07
probably duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/273

**Comment by RoiSoleil** [comment] 2024-08-22 14:18
Looks like the same for sure ;) Sorry

**Closed** 2024-08-23 05:20 UTC
Labels: javac
