### ISSUE TITLE
BootstrapMethodError for method reference in records implementing an interface

### ISSUE THREAD

**Issue by knutae** [eclipse-jdt/eclipse.jdt.core#1084] opened 2023-05-23 15:16 UTC
The following program:

```java
import java.util.stream.Stream;

public class RecordInterface {
    interface Base {
        String name();
    }

    record FooRecord(String name) implements Base {}

    record BarRecord(String name) implements Base {}

    public static void main(String[] args) {
        var foo = new FooRecord("foo");
        var bar = new BarRecord("bar");
        System.out.println(Stream.of(foo, bar).map(Base::name).toList());
    }
}
```

Triggers the unexpected exception when being compiled and run through the eclipse plugin (vscode-java, but also happens in Eclipse):

```
Exception in thread "main" java.lang.BootstrapMethodError: bootstrap method initialization exception
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
        at RecordInterface.main(RecordInterface.java:15)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class java.lang.Record; not a subtype of implementation type interface RecordInterface$Base
        at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:271)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
        ... 4 more
```

Changing the method reference `Base::name` to `x -> x.name()` is a workaround for the bug.

I checked that manually compiling and running the class with `javac` and `java` (openjdk 17.0.7) does not trigger any errors.

**Comment by iloveeclipse** [comment] 2023-05-23 15:19
I can't reproduce with I20230522-1800 build.
Can you please try **latest** build from https://download.eclipse.org/eclipse/downloads/ ?

**Comment by knutae** [comment] 2023-05-23 15:38
Ok, I was not able to reproduce with the latest version (I20230523-0600) or with (4.28M3). The bug is present in 4.27 (`java -jar ecj-4.27.jar -17 RecordInterface.java && java RecordInterface`).

**Comment by iloveeclipse** [comment] 2023-05-23 16:16
Thanks, closing as fixed.

**Closed by iloveeclipse** 2023-05-23 16:16 UTC
Labels: needinfo
