### ISSUE TITLE
[Sealed types][Enhanced Switch] Exhaustiveness in pattern matching switch is wrong

### ISSUE THREAD

**Issue by jbyunes** [eclipse-jdt/eclipse.jdt.core#3166] opened 2024-10-26 07:34 UTC
As designed in **JEP 441: Pattern Matching for switch, Switches and enum constants** the following code is correct as it is exhaustive:

```
sealed interface CardClassification permits Suit, Tarot {}
public enum Suit implements CardClassification { CLUBS, DIAMONDS, HEARTS, SPADES }
final class Tarot implements CardClassification {}
static void exhaustiveSwitchWithBetterEnumSupport(CardClassification c) {
    switch (c) {
        case Suit.CLUBS -> {
            System.out.println("It's clubs");
        }
        case Suit.DIAMONDS -> {
            System.out.println("It's diamonds");
        }
        case Suit.HEARTS -> {
            System.out.println("It's hearts");
        }
        case Suit.SPADES -> {
            System.out.println("It's spades");
        }
        case Tarot t -> {
            System.out.println("It's a tarot");
        }
    }
}

```
Eclipse Version: 2024-09 (4.33.0) Build id: 20240905-0614, compiler compliance 22 is activated,  reports it as an error and necessitate a `default` case which is obviously wrong:
<img width="533" alt="Capture d’écran 2024-10-26 à 09 29 57" src="https://github.com/user-attachments/assets/0ca9cefd-b517-469c-80e4-4492d9528042">

The code can be successfully compiled with any external Java compiler ≥21.

**Comment by srikanth-sankaran** [comment] 2024-10-26 08:21
There have been numerous bug fixes in this area since 4.33. Are you able to test a recent I build to see if your problem is still there ??

**Comment by srikanth-sankaran** [comment] 2024-10-26 08:27
This is most likely the same issue as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2720

**Comment by srikanth-sankaran** [comment] 2024-10-26 11:47
This modified fuller program compiles and runs on master and prints:

```
sealed interface CardClassification permits Suit, Tarot {}
enum Suit implements CardClassification { CLUBS, DIAMONDS, HEARTS, SPADES }
final class Tarot implements CardClassification {}
public class X {
static void exhaustiveSwitchWithBetterEnumSupport(CardClassification c) {
    switch (c) {
        case Suit.CLUBS -> {
            System.out.println("It's clubs");
        }
        case Suit.DIAMONDS -> {
            System.out.println("It's diamonds");
        }
        case Suit.HEARTS -> {
            System.out.println("It's hearts");
        }
        case Suit.SPADES -> {
            System.out.println("It's spades");
        }
        case Tarot t -> {
            System.out.println("It's a tarot");
        }
    }
}
	public static void main(String[] args) {
		exhaustiveSwitchWithBetterEnumSupport(Suit.CLUBS);
		exhaustiveSwitchWithBetterEnumSupport(Suit.DIAMONDS);
		exhaustiveSwitchWithBetterEnumSupport(Suit.HEARTS);
		exhaustiveSwitchWithBetterEnumSupport(Suit.SPADES);
		exhaustiveSwitchWithBetterEnumSupport(new Tarot());
	}
}
```

compiles fine on master/HEAD and when run prints as expected:

```
It's clubs
It's diamonds
It's hearts
It's spades
It's a tarot
```

**Comment by srikanth-sankaran** [comment] 2024-10-26 11:58
Yes, I am able to confirm that the problem shows up before commit 44940179280b2aeaf0f17af299076151e60ddca0 and goes away with it. Closing as a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2720

**Closed by srikanth-sankaran** 2024-10-26 11:58 UTC
