### ISSUE TITLE
Switch Pattern Matching: Null case interaction with guarded cases.

### ISSUE THREAD

**Issue by sundquis** [eclipse-jdt/eclipse.jdt.core#1558] opened 2023-11-05 11:03 UTC
I am running Version: 2023-09 (4.29.0), Build id: 20230907-1323, with the Marketplace plugin for Java 21 Support and  have my execution environment at Java 21.

When I run
<pre>
public static void foo( Object obj ) {
	switch ( obj ) {
		case null 				-> System.out.println( "NULL" );
		case Integer x when x > 0 		-> System.out.println( "Positive: " + x );
		case Integer x when x < 0 		-> System.out.println( "Negative: " + x );
		case Integer x 				-> System.out.println( "Integer: " + x );
		case String x when x.length() > 4	-> System.out.println( "Long: " + x );
		case String x 				-> System.out.println( "String: " + x );
		default 				-> System.out.println( "Other: " + obj );
	}
}

public static void main( String[] args ) {
	Stream.of( 0, 42, -42, "hello", "hi" ).forEach( obj -> foo( obj ) );
}
</pre>
I expect to get
> Integer: 0
> Positive: 42
> Negative: -42
> Long: hello
> String: hi

But I get
> Integer: 0
> Positive: 42
> Integer: -42
> Long: hello
> Other: hi

The exact matching depends on the location of the null case. For example, moving null to the second case
<pre>
...
	switch ( obj ) {
		case Integer x when x > 0 		-> System.out.println( "Positive: " + x );
		case null 				-> System.out.println( "NULL" );
		case Integer x when x < 0 		-> System.out.println( "Negative: " + x );
...
</pre>
produces 
> Other: 0
> Positive: 42
> Negative: -42
> Long: hello
> Other: hi

If the null case is positioned last, above default, then the results are correct:
> Integer: 0
> Positive: 42
> Negative: -42
> Long: hello
> String: hi

I did confirm that if I compile externally, using javac 21.0.1 from Oracle, I do get the correct behavior.

**Comment by iloveeclipse** [comment] 2023-11-05 15:19
Looks like a duplicate of #1466

**Comment by iloveeclipse** [comment] 2023-11-05 15:21
> I just noticed that a switch over a sealed type compiles after I have added a single case, even though I have not exhausted all permitted types. The Oracle compiler (javac 21.0.1) correctly flags this as an error.

Please report a dedicated ticket for this.

**Comment by mpalat** [comment] 2023-11-13 09:23
as mentioned in 1574 fixed - closing

**Closed by mpalat** 2023-11-13 09:23 UTC
