### ISSUE TITLE
Sealed interface does not infer permitted types if it's nested in a record

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#1791] opened 2023-12-26 21:35 UTC
The following code results in a compilation error:
```java
public record T1() {

	public sealed interface Inter {

		record I1() implements Inter {} // error: The type I1 that implements a sealed interface T1.Inter should be a permitted subtype of T1.Inter
	}
}
```

However, if `T1` is changed to a class or an interface, then the error disappears.

Version: 2023-09 (4.29)
Build id: I20230903-1000
Java 21

**Comment by snjeza** [comment] 2023-12-27 02:31
I can't reproduce the issue in Eclipse master. It is reproducible in Eclipse 2023-09(4.29) and Eclipse 2023-12 (4.30)

**Comment by nlisker** [comment] 2023-12-27 04:34
So was it fixed recently?

**Comment by srikanth-sankaran** [comment] 2023-12-27 10:00
> So was it fixed recently?

Yes. See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1641 fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1713

**Comment by srikanth-sankaran** [comment] 2023-12-27 10:01
Closing as duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1641

**Closed by srikanth-sankaran** 2023-12-27 10:01 UTC

**Comment by nlisker** [comment] 2023-12-27 14:38
Thanks. @srikanth-sankaran  Can you have a look at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1753? It skipped triage.
