### ISSUE TITLE
Exported jar has broken characters with UTF-8

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.core#2771] opened 2024-07-29 11:18 UTC
I feel like I tried everything, Text file encoding is UTF-8, UTF-8 is enabled on Windows 11, -Dfile.encoding=UTF-8 is added to eclipse.ini, I tried to build iwth build.xml, I tried to convert it to UTF-8 with scripts, but still files with UTF-8 characters are broken after exporting. Earlier I was using Cp1250 and I think only some classes have their own UTF-8 encoding, but when I try to do it with UTF-8 in Eclipse, characters are broken.

**Comment by iloveeclipse** [comment] 2024-07-29 12:47
1) Please provide clear steps to reproduce, ideally with a small self containing project.
2) Please provide your Eclipse & Java versions.

**Comment by andreasdc** [comment] 2024-07-29 14:33
1. Hmm, I had encoding cp1250, I tried changing the encoding to UTF-8 in Eclipse, it broke some special characters, I then changed the encoding of all .java files to UTF-8, special characters work, but not when the jar is exported.
2. Java 22
Version: 2024-06 (4.32.0)
Build id: 20240606-1231

**Comment by andreasdc** [comment] 2024-07-29 14:45
Project and jar in the attachment, but I still see it kind of broken.
[test.zip](https://github.com/user-attachments/files/16415024/test.zip)

**Comment by stephan-herrmann** [comment] 2024-07-29 21:15
You might start by explaining what you mean by "broken".

**Comment by andreasdc** [comment] 2024-07-29 21:16
» char is shown as �

> You might start by explaining what you mean by "broken".

**Comment by stephan-herrmann** [comment] 2024-07-29 21:26
> > You might start by explaining what you mean by "broken".
> For example » char is shown as �

keep going, e.g.:
* how was the original char entered?
* how did you confirm the correct char was saved?
* where did it show up broken?
* any hints that the result was caused by exporting as jar?

Quick observation: I see the source file already containing �, binary: 0xEF 0xBF 0xBD.

Where in your zip file should we find char '»'?

**Comment by andreasdc** [comment] 2024-07-29 21:28
> > > You might start by explaining what you mean by "broken".
> > > For example » char is shown as �
> 
> keep going, e.g.:
> 
> * how was the original char entered?
> * how did you confirm the correct char was saved?
> * where did it show up broken?
> * any hints that the result was caused by exporting as jar?
> 
> Quick observation: I see the source file already containing �, binary: 0xEF 0xBF 0xBD.
> 
> Where in your zip file should we find char '»'?

I press ALT + 1 7 5
Correct char is not being saved.
It showed in Eclipse already, but when I had it in Eclipse correctly, it was broken after exporting.
I don't understand the part about hints.
This � should be », I typed that in Eclipse.

**Comment by stephan-herrmann** [comment] 2024-07-29 21:38
> I press ALT + 1 7 5

On my machine this doesn't produce any special character. To check whether it's a problem with your input (e.g., keyboard driver) or with the editor you could try pasting the character from somewhere else into Eclipse.

> Correct char is not being saved.

This demonstrates your problem is between typing on the keyboard and saving the .java source file, right? 

> It showed in Eclipse already

What showed in Eclipse?

> but when I had it in Eclipse correctly, it was broken after exporting.

not specific enough for me to react to

> I don't understand the part about hints.

I wanted to find out whether where in the process the assumed bug happens. Your answer above indicates that it happens long before the export as jar.

**Comment by stephan-herrmann** [comment] 2024-07-29 21:40
> Project and jar in the attachment, but I see it kind broken in the Eclipse already. [test.zip](https://github.com/user-attachments/files/16415024/test.zip)

For reproducing the issue it would help to define the encoding at the project level, which would show up in a file `.settings/org.eclipse.core.resources.prefs`.

**Comment by andreasdc** [comment] 2024-07-29 22:17
> > I press ALT + 1 7 5
> 
> On my machine this doesn't produce any special character. To check whether it's a problem with your input (e.g., keyboard driver) or with the editor you could try pasting the character from somewhere else into Eclipse.
> 
> > Correct char is not being saved.
> 
> This demonstrates your problem is between typing on the keyboard and saving the .java source file, right?
> 
> > It showed in Eclipse already
> 
> What showed in Eclipse?
> 
> > but when I had it in Eclipse correctly, it was broken after exporting.
> 
> not specific enough for me to react to
> 
> > I don't understand the part about hints.
> 
> I wanted to find out whether where in the process the assumed bug happens. Your answer above indicates that it happens long before the export as jar.

It was kind of true, it works in this project, but in some of my projects I have broken characters too. I have backup of workspace in Cp1250 encoding, how to change it good to UTF-8?
I tried changing the setting or converting it with this script, but it breaks some characters.
`import os
import chardet

def convert_to_utf8(file_path):
    try:
        with open(file_path, 'rb') as f:
            raw_data = f.read()
        detected = chardet.detect(raw_data)
        encoding = detected['encoding']
        confidence = detected['confidence']
        
        if encoding and confidence > 0.5 and encoding.lower() != 'utf-8':
            print(f"Converting {file_path} from {encoding} to UTF-8")
            with open(file_path, 'r', encoding=encoding, errors='ignore') as f:
                content = f.read()
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
        else:
            print(f"No change needed for {file_path} (encoding: {encoding}, confidence: {confidence})")
    except Exception as e:
        print(f"Failed to convert {file_path}: {str(e)}")

def main():
    project_dir = "C:/Users/User/Desktop/Programy/eclipse/workspace"
    for root, dirs, files in os.walk(project_dir):
        for file in files:
            if file.endswith('.java'):
                file_path = os.path.join(root, file)
                convert_to_utf8(file_path)

if __name__ == "__main__":
    main()
`

**Comment by stephan-herrmann** [comment] 2024-07-30 17:49
I cannot comment on your script, frankly I'm not even sure which language it is written in.

The internet has plenty of hints on tools for such conversion.

I'm closing this issue, as I haven't seen evidence that there is a bug in JDT.

**Closed by stephan-herrmann** 2024-07-30 17:49 UTC
Labels: needinfo

**Comment by andreasdc** [comment] 2024-07-31 01:07
> I cannot comment on your script, frankly I'm not even sure which language it is written in.
> 
> The internet has plenty of hints on tools for such conversion.
> 
> I'm closing this issue, as I haven't seen evidence that there is a bug in JDT.

It was written in python, I did that it Powershell too, no good results.
Maybe it has plenty of tools, but it results in broken characters, how can I fix that?

**Comment by andreasdc** [comment] 2024-07-31 01:33
After changing text encoding to utf-8, some projects has proper characters, but most of them have broken characters. When I open the .java file directly the character looks correct, but after exporting and in Eclipse it is broken.

**Comment by stephan-herrmann** [comment] 2024-07-31 09:01
I cannot help you regarding conversion of existing files.

If you want a JDT committer to further analyze your problem, we need the following:
* a step-by-step description how to reproduce your problem **starting from an fresh new java project in Eclispe**, including all relevant options that are configured for that project.
* a clear description of the expected behavior
* a clear description of the deviant behavior

And by clear description I mean something way more precise than "it's broken" or "in Eclipse it is broken", such statements simply don't help us understanding the situation on your machine.

BTW, I'm now unsubscribing from this issue.

**Comment by andreasdc** [comment] 2024-07-31 13:05
Fresh new java project, I'm talking about my old projects that have broken characters (I explained that earlier, special characters look different than they are). 
I change encoding to UTF-8 or I convert the files to UFT-8 manually and characters are broken. When I open this in notepad it looks properly, in eclipse and after compiling it's broken.
Eclipse is so hard to work with sometimes and I can't even report simple bugs...
