### ISSUE TITLE
Content assist does not work after switch and lambda

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.core#193] opened 2022-07-06 09:50 UTC
If you have
```
import java.nio.file.StandardCopyOption;

@SuppressWarnings("nls")
public class EclipseTest {
    
    private void a(StandardCopyOption option) throws Exception {
	switch (option) {
	case ATOMIC_MOVE:
	    break;
	}
    }

    public void b() throws Exception {
	Runnable r = () -> {
	};

    }

    private fi  <==== Empty content assist box 
    
}
```

If you add the `private fi` and autocomplete then several suggestions are shown.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/10562923/177520625-81ea4c40-d428-49d5-b848-8382701cec69.png">

vs

<img width="221" alt="image" src="https://user-images.githubusercontent.com/10562923/177520721-a2d66501-39bb-4a5d-8c07-c7f6ea5bfbc6.png">

Note that it depends on the other statements in the file, the content assist usually works fine for members at the end of a file.

**Comment by ktatavarthi** [comment] 2022-07-06 12:16
This was working in 4.16 Eclipse. This is a regression.

**Comment by jubax** [comment] 2022-10-21 11:05
This content assist regression still exists in 2022-09 (4.25.0).

**Comment by jubax** [comment] 2022-11-29 13:18
I debugged a bit and I found that
```
import java.nio.file.StandardCopyOption;

@SuppressWarnings("nls")
public class EclipseTest {
    
    private void a(StandardCopyOption option) throws Exception {
	switch (option) {
	case ATOMIC_MOVE:
	    break;
	}
        Runnable r = () -> {};
        fina<==== Empty content assist box 
    }
    
}
```
is sufficient to reproduce the error. The completion AST for that program is
```
import java.nio.file.StandardCopyOption;
public @SuppressWarnings("nls") class EclipseTest {
  public EclipseTest() {
  }
  private void a(StandardCopyOption option) throws Exception {
    Runnable r;
    <CompleteOnName:fina>;
  }
}
```
and at some point we land in `AssistParser.fallBackToSpringForward()`. In that method the current token is `TokenNameBeginCaseExpr = 72` and `this.referenceContext` is a MethodDeclaration `() {}`, so something went wrong with the lambda.

After that `CompletionScanner.ungetToken()` is called, which leads to a "Single cell array overflow" `ArrayIndexOutOfBoundsException`.

I'm not sure if I can really make progress from here, but maybe this comment helps anyone who actually understands what is going on.

**Comment by jubax** [comment] 2023-03-21 09:42
@ktatavarthi, I wonder if there is a timeline for fixing this. I tried to fix it myself, but I guess I won't find time to continue working on that (sorry).

**Comment by trancexpress** [comment] 2023-03-21 19:20
From the SDKs I have downloaded, it works in:
```
Eclipse SDK
Version: 2020-09 (4.17)
Build id: I20200803-1800
```
But doesn't work in:
```
Eclipse SDK
Version: 2020-09 (4.17)
Build id: I20200812-0710
```

First commit I see this with is: 5845a8071ec80e046fc8d5b85b90098700d4bbd0 (unfortunately, a Java 15 branch merge commit)

From the merged commits, this is the one that introduces the regression: 73e843b3ad1076d2dbe78fac7e9422c3e823cd2e (and it changes a lot of code)

**Comment by trancexpress** [comment] 2023-03-21 20:10
This is actually a compiler bug and content assist not working is a result of that. Using the snippet from the description, `javac` shows the following errors:

```
➜  src javac EclipseTest.java 
EclipseTest.java:19: error: <identifier> expected
    private fi
              ^
1 error
```

Whereas `ecj` (4.27 M1) shows the following errors:

```
➜  src /usr/lib/jvm/java-17-openjdk/bin/java -jar /data/eclipses/ecj-4.27M1.jar -source 17 -target 17 -nowarn EclipseTest.java
----------
1. ERROR in /data/workspaces/runtime-Eclipse/TestGH193/src/EclipseTest.java (at line 11)
        }
        ^
Syntax error, insert "}" to complete ClassBody
----------
2. ERROR in /data/workspaces/runtime-Eclipse/TestGH193/src/EclipseTest.java (at line 14)
        Runnable r = () -> {
                        ^^
Syntax error on token "BeginCaseExpr", delete this token
----------
3. ERROR in /data/workspaces/runtime-Eclipse/TestGH193/src/EclipseTest.java (at line 17)
        }
        ^
Syntax error on token "}", delete this token
----------
4. ERROR in /data/workspaces/runtime-Eclipse/TestGH193/src/EclipseTest.java (at line 19)
        private fi
                ^^
Syntax error, insert "VariableDeclarators" to complete LocalVariableDeclaration
----------
5. ERROR in /data/workspaces/runtime-Eclipse/TestGH193/src/EclipseTest.java (at line 19)
        private fi
                ^^
Syntax error, insert ";" to complete LocalVariableDeclarationStatement
----------
5 problems (5 errors)
```

**Comment by iloveeclipse** [comment] 2024-05-08 13:28
I can't reproduce this bug anymore on I20240507-2220.

**Closed by iloveeclipse** 2024-05-08 13:28 UTC
Labels: bug, regression, compiler
