### ISSUE TITLE
The project was not built since its build path is incomplete. Cannot find the class file for java.lang.constant.DynamicConstantDesc

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#3023] opened 2024-09-27 05:46 UTC
Today I changed some sources (no settings no JDK changes, project build successful before, nothing in the error log) on a project and get this error markers:

- The project was not built since its build path is incomplete. Cannot find the class file for java.lang.constant.DynamicConstantDesc. Fix the build path then try building this project
- The type java.lang.constant.DynamicConstantDesc cannot be resolved. It is indirectly referenced from required type java.lang.constant.ConstantDesc

![grafik](https://github.com/user-attachments/assets/175ac85d-4ead-4f26-bb56-c5f7110016aa)

The Project is using java 17
![grafik](https://github.com/user-attachments/assets/829c6d71-5c7c-427a-b075-8ce9f379c143)

This is very similar to
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1842

and really hurts user experience with using JDT/Eclipse:

1. Obviously I can't "Fix the build path" as I have not changed anything there and all looks sane
2. `java.lang` can not be added to the build path anyways
3. cleaning multiple times does not change anything, so it seems something internally in JDT is wrecked

even though as last time it was claimed that the compiler can't do anything thing, I really think batch-compiler should somehow better handle such internal failures for *synthetic jdk classes* automatically injected, as a user **I have zero influence** nor any chance to find such a problem, e.g searching my whole codebase for `java.lang.constant.DynamicConstantDesc` or `java.lang.constant.ConstantDesc` will obviously not reveal any match, I can't "change" my JDK so if there is any problem with that I need guidance what is the problem. Most of the time one needs to restart eclipse and clean all projects to getting out of such situation see also for example:

- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1807

**Comment by jukzi** [comment] 2024-09-27 05:53
sounds like duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2877

**Comment by laeubi** [comment] 2024-09-27 06:30
In this case I needed to restart + clean all projects to make the problem go away.

**Closed** 2024-09-27 06:44 UTC
Labels: bug
