### ISSUE TITLE
Eclipse fails but IntelliJ work fine on the same source

### ISSUE THREAD

**Issue by MyhreAndersen** [eclipse-jdt/eclipse.jdt.core#1418] opened 2023-09-22 11:05 UTC
Tested with Version: 2023-09 (4.29.0) Build id: 20230907-1323

I'm working on understanding the new java.lang.classfile API.
Tried to compile https://github.com/Glavo/classfile/tree/main

I get a long list of errors from the underlying Java compiler:
- Cycle detected: a cycle exists in the type hierarchy between CustomAttribute and UnboundAttribute
- ChainedClassBuilder cannot be resolved to a variable
- The hierarchy of the type CodeImpl is inconsistent
Could it be an Eclipse or Java option that I have overlooked?

It would be nice if someone else tried to compile https://github.com/Glavo/classfile/tree/main

It works perfectly fine with IntelliJ IDEA 2023.

[WorkSpace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12700036/WorkSpace.log)
2 (Community Edition)

**Comment by iloveeclipse** [comment] 2023-09-22 15:24
Cloned, started ./gradlew, got build error:
```
$ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
...........10%............20%............30%............40%............50%............60%............70%............80%...........90%............100%

Welcome to Gradle 8.1.1!

Here are the highlights of this release:
 - Stable configuration cache
 - Experimental Kotlin DSL assignment syntax
 - Building with Java 20

For more details see https://docs.gradle.org/8.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'classfile'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.aya-prover.upstream:build-util:0.0.11.
     Required by:
         project :
      > No matching variant of org.aya-prover.upstream:build-util:0.0.11 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1.1' but:
          - Variant 'apiElements' capability org.aya-prover.upstream:build-util:0.0.11 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
          - Variant 'javadocElements' capability org.aya-prover.upstream:build-util:0.0.11 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
          - Variant 'runtimeElements' capability org.aya-prover.upstream:build-util:0.0.11 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
          - Variant 'sourcesElements' capability org.aya-prover.upstream:build-util:0.0.11 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
```

Please give instructions how to setup your project.

**Comment by MyhreAndersen** [comment] 2023-09-22 20:30
It's too late in Norway - I will replay tomorrow

**Comment by stephan-herrmann** [comment] 2023-09-23 00:13
Apparently, those "errors" are not compile-errors but an exception thrown by the compiler, pasted here for better visibility:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.needsUncheckedConversion(org.eclipse.jdt.internal.compiler.lookup.TypeBinding)" because "argumentType" is null
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.checkInvocationArgument(ASTNode.java:377)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.checkInvocationArguments(ASTNode.java:463)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:956)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolveTypeExpecting(Expression.java:1147)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.resolveTypeInternal(SwitchExpression.java:526)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.resolveType(SwitchExpression.java:463)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolvePolyExpressionArguments(ASTNode.java:777)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:1027)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:835)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.resolve(ReturnStatement.java:337)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:905)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Surely this must be fixed, but we do need to observe compilation in the original project, or even better: a self-contained reproducing example :)

**Comment by stephan-herrmann** [comment] 2023-09-23 00:18
> Tested with Version: 2023-09 (4.29.0) Build id: 20230907-1323

Interestingly, the workspace log says "eclipse.buildId=4.28.0.20230608-1200"

> [WorkSpace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12700036/WorkSpace.log)
> 2 (Community Edition)

The last line looks misplaced :)

**Comment by MyhreAndersen** [comment] 2023-09-23 06:28
Here is the project that fails:
[GlavoClassFile.Zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12705781/GlavoClassFile.Zip)

**Comment by MyhreAndersen** [comment] 2023-09-24 14:41
Hi Glavo ! I have tried to compile your java.lang.classfile API (
https://github.com/Glavo/classfile/tree/main) with Eclipse. It didn't go
well. Therefore I have reported it to this issue thread to Eclipse.

**Comment by stephan-herrmann** [comment] 2023-09-24 15:27
> Here is the project that fails: [GlavoClassFile.Zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12705781/GlavoClassFile.Zip)

I could reproduce using these steps:
* Extract from the zip only folder GlavoClassFile/GlavoClassFile/lib
* Import that folder as a project into eclipse
* Remove from .classpath the gradle classpath container (as in my JDT dev workspace I don't have gradle)
* Add the following libraries instead:
  * org.obectweb.asm  and org.objectweb.asm.tree, both in version 9.5.0 
  * JUnit library (junit 5)
* at that point I see 146 errors, where those about hierarchy cycles are among them

I didn't, however, see any exceptions thrown by JDT.

**Comment by MyhreAndersen** [comment] 2023-09-24 15:32
You said:

   - at that point I see 146 errors, where those about hierarchy cycles are
   among them

IntelliJ gives no errors.

**Comment by stephan-herrmann** [comment] 2023-09-24 16:01
> IntelliJ gives no errors.

that would be "javac compiles without errors", right?
(IntelliJ, to the best of my knowledge doesn't implement a Java compiler).

**Comment by MyhreAndersen** [comment] 2023-09-24 16:09
IntelliJ reports using javac from jdk22 (log said: javac 22 was used to
compile java sources).

I now continue to work in IntellliJ where everything works - no errors.
Sorry if I have mixed up several Eclipse releases and taken .log files from
the wrong versions.
The problem is all the error messages that Eclipse gives and not IntelliJ
(which works perfectly OK) and which prevents me from testing 'classfile'.
I am most familiar with Eclipse and would like to continue, but then the
system must work.

**Comment by stephan-herrmann** [comment] 2023-09-24 16:11
Here's a shorthand of a highly reduced stacktrace showing circularity:
```
* connectTypeHierarchy(UnboundAttribute)
* resolveSuperType(Attribute<T>)
* detectHierarchyCycle(org.glavo.classfile.Attribute<A>, Attribute<T>)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.Attribute<A>)
* resolveSuperType(WritableElement<A>)
* detectHierarchyCycle(org.glavo.classfile.WritableElement<T>, WritableElement<A>)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.WritableElement<T>)
* resolveSuperType(ClassfileElement)
* detectHierarchyCycle(org.glavo.classfile.ClassfileElement, ClassfileElement)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.ClassfileElement)
* ClassScope(org.glavo.classfile.ClassfileElement).connectPermittedTypes()
* findPermittedType(AttributedElement)
* detectHierarchyCycle(org.glavo.classfile.AttributedElement, AttributedElement)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.AttributedElement)
* ClassScope(org.glavo.classfile.AttributedElement).connectPermittedTypes()
* findPermittedType(ClassModel)
* detectHierarchyCycle(org.glavo.classfile.ClassModel, ClassModel)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.ClassModel)
* resolveSuperType(CompoundElement<ClassElement>)
* resolveTypeArgument(ClassElement)
* detectHierarchyCycle(org.glavo.classfile.ClassElement, ClassElement)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.ClassElement)
* ClassScope(org.glavo.classfile.ClassElement).connectPermittedTypes()
* findPermittedType(AccessFlags)
* detectHierarchyCycle(org.glavo.classfile.AccessFlags, AccessFlags)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.AccessFlags)
* resolveSuperType(MethodElement)
* detectHierarchyCycle(org.glavo.classfile.MethodElement, MethodElement)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.MethodElement)
* ClassScope(org.glavo.classfile.MethodElement).connectPermittedTypes()
* findPermittedType(CodeModel)
* detectHierarchyCycle(org.glavo.classfile.CodeModel, CodeModel)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.CodeModel)
* resolveSuperType(CompoundElement<CodeElement>)
* resolveTypeArgument(CodeElement)
* detectHierarchyCycle(org.glavo.classfile.CodeElement, CodeElement)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.CodeElement)
* ClassScope(org.glavo.classfile.CodeElement).connectPermittedTypes()
* findPermittedType(CustomAttribute)
* detectHierarchyCycle(org.glavo.classfile.CustomAttribute<T>, CustomAttribute)
* connectTypeHierarchyWithoutMembers(org.glavo.classfile.CustomAttribute<T>)
* resolveSuperType(UnboundAttribute.CustomAttribute<T>)
* detectHierarchyCycle(org.glavo.classfile.impl.UnboundAttribute<T>, UnboundAttribute.CustomAttribute<T>)
* => isHierarchyBeingActivelyConnected(org.glavo.classfile.impl.UnboundAttribute<T>) == true
```

This shows, that UnboundAttribute indeed indirectly "depends" on itself. In this graph of dependencies, two kinds of edges may be questioned:
* traveling to permitted types (`connectPermittedTypes()`)
* traveling to type arguments (`resolveTypeArgument`)

@mpalat  It looks like you added `connectPermittedTypes()` to `connectTypeHierarchy()` via https://bugs.eclipse.org/bugs/show_bug.cgi?id=563806, right? I agree that permitted types are related to type hierarchies, but I believe `connectTypeHierarchy()` should only look to supertypes, whereas permitted types are subtypes, right?

Ergo: should we move `connectPermittedTypes()` to the recently added phase `CompilationUnitScope.connectTypeHierarchy2()` where already the related `connectImplicitPermittedTypes()` is invoked. Or do you see reasons doing `connectPermittedTypes()` "as early as possible"?

**Comment by stephan-herrmann** [comment] 2023-09-24 16:12
> but then the system must work.

no-one argues that bugs should stay :)

**Comment by stephan-herrmann** [comment] 2023-09-24 16:15
> Here's a shorthand of a highly reduced stacktrace showing circularity:

frankly, I can't remember ever seeing such a complex inheritance structure ... :) - so its no big wonder, our test suite didn't detect this until now, but **thanks for the report**, as it helps us to improve the compiler.

**Comment by MyhreAndersen** [comment] 2023-09-24 16:24
I am not the author of that API so I suggest you continue communication with
Glavo ***@***.***>

p.s. The API is now included in the java.jdk.internal.classfile.

**Comment by MyhreAndersen** [comment] 2023-09-24 18:36
For your info: This is the guy behind api:
https://www.youtube.com/watch?v=pcg-E_qyMOI

**Comment by stephan-herrmann** [comment] 2023-09-24 21:26
Thanks for trying to connect people. Incidentally I know Brian Goetz and I've seen the [JEP draft](https://openjdk.org/jeps/8280389).

OTOH, from my previous comments you should see that I already essentially know what needs to be done on JDT side. Also the "needinfo" label has been removed.

**Comment by stephan-herrmann** [comment] 2023-09-28 15:35
> @mpalat It looks like you added `connectPermittedTypes()` to `connectTypeHierarchy()` via https://bugs.eclipse.org/bugs/show_bug.cgi?id=563806, right? I agree that permitted types are related to type hierarchies, but I believe `connectTypeHierarchy()` should only look to supertypes, whereas permitted types are subtypes, right?

@mpalat  did you see my question?

**Comment by MyhreAndersen** [comment] 2023-09-28 15:54
I just tried to use the new Classfil APi.
You must communicate directly with Brian Goetz
<https://inside.java/u/BrianGoetz>

**Comment by stephan-herrmann** [comment] 2023-09-28 17:26
> I must repeat: I am NOT the author of that API

Why should authorship of that code be relevant for fixing this bug in eclipse?

**Comment by mpalat** [comment] 2023-10-03 04:46
> > @mpalat It looks like you added `connectPermittedTypes()` to `connectTypeHierarchy()` via https://bugs.eclipse.org/bugs/show_bug.cgi?id=563806, right? I agree that permitted types are related to type hierarchies, but I believe `connectTypeHierarchy()` should only look to supertypes, whereas permitted types are subtypes, right?
> 
> @mpalat did you see my question?

@stephan-herrmann I was out of office for a little over a week and just back to office. Will take a look.

**Comment by srikanth-sankaran** [comment] 2024-06-13 06:11
It is unclear whether the merged PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1464 helped in this ticket or not. In any case I still see calls to `connectPermittedTypes` from `org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchyWithoutMembers()` - we do have a bunch of open tickets with inconsistent/cyclic hierarchy problems (eg https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2093 where "connecting" permitted types  may have a finger in the pie. 

I think that operation should be moved completely away - there is some documentation of some particular corner case necessitating : see the comment above `org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectPermittedTypes()` but IMP that scenario calls for a different fix altogether. I'll follow up

**Comment by brychcy** [comment] 2024-06-13 18:53
This sounds very much like https://bugs.eclipse.org/bugs/show_bug.cgi?id=495953 where I had isolated a test case:

```
public interface AU1RegKey<O extends AURegObject<O>> extends AURegBase<O> {
}
--
public interface AURegBase<O extends AURegObject<O>> extends AURegType<O> {
}
--
public interface AURegObject<O extends AURegObject<O>> extends AU1RegKey<O> {
}
--
public interface AURegType<O extends AURegObject<O>> {
}

```

**Comment by stephan-herrmann** [comment] 2024-06-20 11:33
> we do have a bunch of open tickets with inconsistent/cyclic hierarchy problems (eg #2093 where "connecting" permitted types may have a finger in the pie.
> 
> I think the `connectPermittedTypes` operation should be moved completely away - there is some documentation of some particular corner case necessitating : see the comment above `org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectPermittedTypes()` but IMO that scenario calls for a different fix altogether. I'll follow up

@srikanth-sankaran did #2561 help for this one, too?

**Comment by stephan-herrmann** [comment] 2024-08-25 21:23
I replayed the steps from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1418#issuecomment-1732597133 (with slight variations) in current RC1.

I had a few hiccups during project configuration, but in the end I got it to compile without throwing StackOverflowError, nor reporting any cycles.

Also Till's example from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1418#issuecomment-2166553794 *compiles* fine by now. Only editor / reconciler still report "The hierarchy of the type AU1RegKey is inconsistent".

If that latter problem is relevant for anyone, please file a new ticket.

Closing as the original problem can no longer be reproduced, perhaps it was resolved indeed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2561

**Closed by stephan-herrmann** 2024-08-25 21:23 UTC
Labels: bug, compiler, javac
