### ISSUE TITLE
Look up for installed JVMs fails at startup of Eclipse 2023-09 M2

### ISSUE THREAD

**Issue by minduch** [eclipse-jdt/eclipse.jdt.core#1272] opened 2023-08-06 14:48 UTC
Eclipse 2023-09 M2 nearly always shows the error below at startup on Windows and macOS (haven't tested on Linux):

```
eclipse.buildId=4.29.0.I20230726-1800
java.version=17.0.8
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/minduch/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.java.product -keyring /Users/minduch/.eclipse_keyring

org.eclipse.core.jobs
Error
Sun Aug 06 16:26:02 CEST 2023
An internal error occurred during: "Look up for installed JVMs".

java.lang.UnsupportedOperationException: remove
	at java.base/java.util.Iterator.remove(Iterator.java:102)
	at java.base/java.util.Collection.removeIf(Collection.java:577)
	at org.eclipse.jdt.internal.launching.DetectVMInstallationsJob.run(DetectVMInstallationsJob.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This happens with Eclipse product as well as our own Eclipse-based product. It happens on Windows x64 as well as the above on macOS using Apple M2 silicon.

I think it might be JustJ-related, because I have changed the VM using the `eclipse.ini` setting `-vm` to use another VM located outside of Eclipse, not using JustJ. This error also disapears when setting the `-vm` for macOS to an external VM.

**Comment by minduch** [comment] 2023-08-06 14:55
Correction: this problem can still happen every time, e.g. on macOS Aarch64 using our product event if e.g. OpenJDK 20.0.2 is used as an external VM thus not using JustJ JRE with the `-vm` switch in `eclipse.ini`.

**Comment by minduch** [comment] 2023-08-06 15:16
Question: could it be that the List of VM's is using a list such as `List<...> vmList = Arrys.asList(...)`? This would be the typical behavior of such code. If so, then the `Arrays.asList()` needs to be placed in an `ArrayList` such as:

```java
ArrayList<...> vmList = new ArrayList<>(Arrays.asList(...));
```

instead of e.g.:

```java
List<...> vmList = Arrays.asList(...);
vmList.remove(0); // --> This would cause the "java.lang.UnsupportedOperationException: remove" exception
```

Actually, looking at the code of `DetectVMInstallationsJob` shows the error for macOS at lines 65-66:

```java
				systemVMs = Arrays.asList(MacInstalledJREs.getInstalledJREs(monitor));
				systemVMs.removeIf(t -> knownVMs.contains(t.getInstallLocation()));
```

If this code is rewritten to below code, it would make it work.

```java
				systemVMs = new ArryaList<>(Arrays.asList(MacInstalledJREs.getInstalledJREs(monitor)));
				systemVMs.removeIf(t -> knownVMs.contains(t.getInstallLocation()));
```

The problem for other OS would be solved by modifying the line 55 in `DetectVMInstallationsJob.run()`:

```java
		Collection<File> candidates = computeCandidateVMs();
```

to

```java
		Collection<File> candidates = new HashSet<>(computeCandidateVMs());
```

**Comment by iloveeclipse** [comment] 2023-08-06 17:17
This is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/289 and is fixed in master already via https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/292.

**Closed by iloveeclipse** 2023-08-06 17:17 UTC
