### ISSUE TITLE
Multiple NPEs in CodeStream.retrieveLocalType()

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2436] opened 2024-05-13 06:37 UTC
Fresh OOmph setup of platform workspace (https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) leads to `Internal compiler error`
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/9fb5b078-7c40-463e-891a-3ae38776a9fe)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/fadc96d7-503e-4a30-b89b-ae7c3e1030a2)

org.eclipse.jdt.core Java Development Tools Core	3.38.0.v20240506-1155

```
Errors occurred during the build.
Errors running builder 'Java Builder' on project 'org.eclipse.ecf.identity'.
Cannot read field "declaringClass" because "this.methodDeclaration.binding" is null
Errors running builder 'Java Builder' on project 'org.eclipse.emf.common'.
Cannot read the array length because the return value of "org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.syntheticOuterLocalVariables()" is null

Internal compiler error: java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.syntheticOuterLocalVariables()" is null at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7693)
Internal compiler error: java.lang.NullPointerException: Cannot read field "declaringClass" because "this.methodDeclaration.binding" is null at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7671)
```

 error log:

```
java.lang.NullPointerException: Cannot read field "declaringClass" because "this.methodDeclaration.binding" is null
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7671)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7712)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload(CodeStream.java:317)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6287)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6186)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:319)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.generateCode(IfStatement.java:221)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.generateCode(TryStatement.java:590)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.generateCode(IfStatement.java:221)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.Initializer.generateCode(Initializer.java:70)
	at org.eclipse.jdt.internal.compiler.ast.Clinit.generateCode(Clinit.java:321)
	at org.eclipse.jdt.internal.compiler.ast.Clinit.generateCode(Clinit.java:132)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.syntheticOuterLocalVariables()" is null
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7693)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7712)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload(CodeStream.java:317)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6287)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6186)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:319)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.generateCode(IfStatement.java:221)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.internalGenerateCode(ConstructorDeclaration.java:462)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.generateCode(ConstructorDeclaration.java:312)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:825)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:755)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:825)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:755)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
Java Model Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:324)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:346)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:186)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:92)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1311)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:189)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:125)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:139)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:100)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:421)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:177)
Caused by: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
```

```
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.syntheticOuterLocalVariables()" is null
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7693)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7712)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload(CodeStream.java:317)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6287)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6186)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:319)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.generateCode(IfStatement.java:221)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.internalGenerateCode(ConstructorDeclaration.java:462)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.generateCode(ConstructorDeclaration.java:312)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:825)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:755)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:825)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:755)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1074)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1110)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:280)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:346)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:186)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:92)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1311)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:189)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:125)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:139)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:100)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:421)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:177)

```

```
eclipse.buildId=4.32.0.I20240512-1800
java.version=21.0.2
java.vendor=Eclipse Adoptium

```

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/c21ff10d-26b2-477d-9257-c2a6e0874d28)

**Comment by iloveeclipse** [comment] 2024-05-13 06:39
Duplicate of #2434

**Closed** 2024-05-14 04:34 UTC
Labels: bug, regression
