### ISSUE TITLE
False positive Potential resource leak for defered closing

### ISSUE THREAD

**Issue by basilevs** [eclipse-jdt/eclipse.jdt.core#3267] opened 2024-11-08 09:48 UTC
Following snippet demonstrates a false positive when closing is defered:

```
import java.io.Closeable;
import java.io.FileInputStream;
import java.io.IOException;

import com.google.common.io.Closer;

public class T {
    public static void main(String[] args) throws IOException {
        try (Closer closer = Closer.create()) {
            closer.register(new FileInputStream("")); //Potential resource leak: '<unassigned Closeable value>' may not be closed
            deferedClose(new FileInputStream("")); //Potential resource leak: '<unassigned Closeable value>' may not be closed
        }
    }

    public static void deferedClose(Closeable thisArgumentIsDefintelyClosedEventuallyIPromise) throws IOException {
        thisArgumentIsDefintelyClosedEventuallyIPromise.close();
    }
}

```

Guava's Closer.register() defers the closing and returns the argument.

If this is impossible to fix in general case, there should be a way to declare a method parameter to be closed eventually. (with a parameter annotation?)

**Comment by stephan-herrmann** [comment] 2024-11-08 18:30
> If this is impossible to fix in general case, there should be a way to declare a method parameter to be closed eventually. (with a parameter annotation?)

You guessed right! :)

If `Closer` where written like this ...
```
class Closer implements AutoCloseable {
	@Owning AutoCloseable ac;
	public static @Owning Closer create() {
		return new Closer();
	}
	public void register(@Owning AutoCloseable rc) {
		this.ac = rc;
	}
	@Override
	public void close() {
		try {
			this.ac.close();
		} catch (Exception e) {
			// silent
		}
	}
}
```
...  then recent versions of JDT / ecj would exactly understand that pattern, and all you'd need to do were adding `@Owning` also to the parameter of `deferedClose()` (and enable corresponding options in the compiler preferences).

Given that the original Closer is not annotated like that, you will have to wait for one more enhancement: #2258

Closing this issue as a duplicate of that one.

**Closed by stephan-herrmann** 2024-11-08 18:30 UTC
