### ISSUE TITLE
NPE in java builder - no stacktrace 4.32.0.I20240522-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2484] opened 2024-05-23 06:08 UTC
heavy regression: i just updated my eclipse installation with newest i build and got errors during the following autobuild:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/12b3e065-6c85-4be7-9fd1-2a5c15cf9994)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/cc7a0368-f6d1-4dd8-bf84-515c6c15fe86)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/b8e241a0-88aa-465e-97a7-1f393b1adfc1)

probably related to the next error in the log:
```
java.lang.AssertionError: Attempt to push null on operand stack!
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:62)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7714)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload_3(CodeStream.java:394)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6279)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6181)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.generateCode(SingleNameReference.java:520)
	at org.eclipse.jdt.internal.compiler.ast.Statement.generateArguments(Statement.java:440)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.generateCode(MessageSend.java:625)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.generateCode(LocalDeclaration.java:174)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:373)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:324)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

recent changes in this stacktrace:
565cabe5b1f680bf0d910231f626ee320f3f8392
@srikanth-sankaran can you look into this?

**Comment by jukzi** [comment] 2024-05-23 06:12
logfile:
```
eclipse.buildId=4.32.0.I20240522-1800
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.emf.ecore 2 0 2024-05-23 07:57:25.427
!MESSAGE Both 'org.eclipse.cbi.p2repo.p2.maven' and 'org.eclipse.m2e.model.edit' register a package for 'http://maven.apache.org/POM/4.0.0'

!ENTRY org.eclipse.egit.ui 2 0 2024-05-23 07:57:47.924
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\jkubitz'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.core.resources 4 2 2024-05-23 07:59:05.249
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException

!ENTRY org.eclipse.core.resources 4 2 2024-05-23 07:59:05.666
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException

!ENTRY org.eclipse.core.resources 4 2 2024-05-23 07:59:20.414
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException

!ENTRY org.eclipse.core.resources 4 75 2024-05-23 07:59:52.312
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2024-05-23 07:59:52.312
!MESSAGE Errors running builder 'Java Builder' on project 'org.eclipse.jdt.core.tests.compiler'.
!STACK 0
java.lang.NullPointerException
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2024-05-23 07:59:52.312
!MESSAGE Errors running builder 'Java Builder' on project 'org.eclipse.jdt.launching'.
!STACK 0
java.lang.NullPointerException
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2024-05-23 07:59:52.312
!MESSAGE Errors running builder 'Java Builder' on project 'org.eclipse.equinox.p2.ui.discovery'.
!STACK 0
java.lang.NullPointerException

!ENTRY org.eclipse.core.resources 4 2 2024-05-23 07:59:55.136
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.AssertionError: Attempt to push null on operand stack!
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:62)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7714)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload_3(CodeStream.java:394)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6279)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6181)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.generateCode(SingleNameReference.java:520)
	at org.eclipse.jdt.internal.compiler.ast.Statement.generateArguments(Statement.java:440)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.generateCode(MessageSend.java:625)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.generateCode(LocalDeclaration.java:174)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:87)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:373)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:324)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)

!ENTRY org.eclipse.core.resources 4 2 2024-05-23 07:59:55.806
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException

```

**Comment by srikanth-sankaran** [comment] 2024-05-23 06:28
@jukzi - I am a bit unclear what I should do to reproduce the problem. What should I try to build ? Thanks for pointers

**Comment by jukzi** [comment] 2024-05-23 06:35
i don't know yet if and how it is reproducible (my workspace is broken now and i still try to figure out how to repair). According to the error message it happened when for example building "org.eclipse.jdt.core.tests.compiler"

**Comment by srikanth-sankaran** [comment] 2024-05-23 06:37
> i don't know yet if and how it is reproducible (my workspace is broken now and i still try to figure out how to repair). According to the error message it happened when for example building "org.eclipse.jdt.core.tests.compiler"

That gets built and run as a part of CI testing - no ?

**Comment by jukzi** [comment] 2024-05-23 06:38
the compiler in the CI build may be pinned to a certain version - but i don't know exactly.

**Comment by srikanth-sankaran** [comment] 2024-05-23 06:40
> the compiler in the CI build may be pinned to a certain version - but i don't know exactly.

The tests should be run against the PR - so they should be getting built with the latest I would think

**Comment by iloveeclipse** [comment] 2024-05-23 06:47
@jukzi : just in case: which exact batch compiler version do you have?

**Comment by jukzi** [comment] 2024-05-23 06:49
17.05.24, 00:11	Eclipse.org	Eclipse Compiler for Java(TM)	3.38.0.v20240516-0852	org.eclipse.jdt.core.compiler.batch

After eclipse restart and "clean all projects" my workspace is fine again, the error did not happened again.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/522242a8-9aaa-4470-b435-c5f1bce64f60)

**Comment by jukzi** [comment] 2024-05-23 07:10
Could not reproduce with a complete new OOmphed installation.

**Comment by iloveeclipse** [comment] 2024-05-23 07:13
What surprises me is the NPE without stack reported. Usually that happens if the JVM seen this NPE many times already, so stack isn't reported anymore.
So I've changed code at `OperandStack.push(OperandStack.java:61)` and inverted condition, so the error is almost always reported. However, I can't get same dialog like in the ticket here, I see **no** NPE's reported at all and the dialog title is a bit different (note the `Build has encountered a problem` vs `Building has encountered a problem`), and no NPE but assert reported:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/3cc22120-f5ea-43ef-9cec-9ca72162667a)

So I wonder how the original build was triggered? I've tried clean build, incremental build on file change, build after crash - they all report no NPE  but assert error.

**Comment by iloveeclipse** [comment] 2024-05-23 07:19
@jukzi : do you have m2e installed (I don't have)? Could it be, that one is related to "empty" NPE's during the build?

**Comment by srikanth-sankaran** [comment] 2024-05-23 07:29
> What surprises me is the NPE without stack reported. Usually that happens if the JVM seen this NPE many times already, so stack isn't reported anymore. So I've changed code at `OperandStack.push(OperandStack.java:61)` and inverted condition, so the error is almost always reported. However, I can't get same dialog like in the ticket here, I see **no** NPE's reported at all and the dialog title is a bit different (note the `Build has encountered a problem` vs `Building has encountered a problem`), and no NPE but assert reported: ![image](https://private-user-images.githubusercontent.com/964108/333076845-3cc22120-f5ea-43ef-9cec-9ca72162667a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDg3MzAsIm5iZiI6MTcxNjQ0ODQzMCwicGF0aCI6Ii85NjQxMDgvMzMzMDc2ODQ1LTNjYzIyMTIwLWY1ZWEtNDNlZi05Y2VjLTljYTcyMTYyNjY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzEzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjk2YjIwNmM1MTA3ZmM5ZDExM2M2ZWQ1YmU4MzZiMWU1OTRhOWI2OWU1MGJmYWRmZDAxMWNlZTM2NDkxY2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.48fBu3hXNeZbZW9M_mZ7I5uO9-DHsE0s3ValsfOjJ2c)
> 
> So I wonder how the original build was triggered? I've tried clean build, incremental build on file change, build after crash - they all report no NPE but assert error.

Changing the condition there only results in the assertion failure being thrown, it doesn't inject an NPE, so it is not surprising that NPE doesn't surface. If anything by short circuiting some code the NPE may be blocked from triggering. 

The assertion spot is the not the problem spot. The NPE is originating somewhere else and is propagated to here. Earlier code would have silently added the null pointer to operand stack - but the operand stack could have been off - Prior to the fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2234 operand stacks were tracked **only** for a method that had an exception handling switch expression. The fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2234  turns them on always (for JDK > 6 but after PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2442 for JDK >= 14) 

The rationale for this is, due to very low coverage of switch expression tests there are so many defects that are not surfacing - with the operand stack tracking happening unconditionally, we have uncovered and fixed ~25 verify errors scenarios

**Comment by iloveeclipse** [comment] 2024-05-23 07:29
The `Build` vs `Building` - that is the job name, used here `org.eclipse.ui.internal.statushandlers.LabelProviderWrapper.getMainMessage(StatusAdapter)`. 
The "usual" build job name in SDK is `Building`. 
So `Build` is most likely the job started by Oomph?
Oomph usually disables autobuild, performs setup and enables autobuild.
Not sure if that is then triggered as `Build` job, but I also unable to reproduce the NPE with that sequence (without Oomph).

**Comment by jukzi** [comment] 2024-05-23 08:10
> @jukzi : do you have m2e installed (I don't have)? Could it be, that one is related to "empty" NPE's during the build?

looks like m2e is installed:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/176fa4d3-931a-4b1b-a35e-244eb8cf49d4)

It sounds plausible, that any unknown NPE later caused the OperandStack error, so that OperandStack ist not the cause but only a follow up error.

**Comment by jukzi** [comment] 2024-05-23 10:07
@srikanth-sankaran  i guess it would help to move the null check from org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(TypeBinding) to
org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(int, int) - which should just never return null but either a TypeBinding or a more detailed exception what did go wrong.

**Comment by srikanth-sankaran** [comment] 2024-06-20 04:32
> @srikanth-sankaran i guess it would help to move the null check from org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(TypeBinding) to org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(int, int) - which should just never return null but either a TypeBinding or a more detailed exception what did go wrong.

Not really, we could be operating with `org.eclipse.jdt.internal.compiler.codegen.OperandStack.NullStack` where is acceptable for `org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(int, int) ` to return `null` (and even otherwise in a few other scenarios it may return null)

This defect has not been observed in about a month's time - I am inclined to close it with no action with the promise that it will be acted upon promptly with highest priority if spotted and reopened. Thanks!

**Closed by srikanth-sankaran** 2024-06-20 04:32 UTC
Labels: bug, regression
