### ISSUE TITLE
[regression] content assist fails to find Type when class defines record below

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdt/eclipse.jdt.core#757] opened 2023-02-16 10:36 UTC
Tested with https://download.eclipse.org/eclipse/updates/4.27-I-builds/I20230215-0610

Given this code:

```java
import java.util.Map;
import java.util.Set;

public class WTF {
	
  Set<String> set = new TreeSet<>();
  
  record Workflow(String name) {
  };
}
```

Completion on `TreeSet|` fails to propose the proper `java.util.TreeSet` import, as long as the record definition is below the completion site. Remove the record or move it upward, and it works again.

![Feb-16-2023 11-28-58](https://user-images.githubusercontent.com/148698/219341126-1830aae8-9496-4f9d-aaf9-04db5ddbadbe.gif)

I checked it worked against 2023-03-M1.

I found it while testing our latest jdt.ls build. cc @rgrunber, @testforstephen

**Comment by fbricon** [comment] 2023-02-16 10:49
Hope this better conveys how bad this is:
![Feb-16-2023 11-47-36](https://user-images.githubusercontent.com/148698/219344500-25466b4c-f88a-4960-b829-35f37a8cd1f9.gif)

**Comment by rgrunber** [comment] 2023-02-16 14:54
Does the errors also appear in the problems view ? If not, maybe another case of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/342 ? Although that was present since 2022-09.

**Comment by rgrunber** [comment] 2023-02-16 16:20
The regression appears to have started with a5490e7d89 (https://github.com/eclipse-jdt/eclipse.jdt.core/issues/667) .

**Comment by iloveeclipse** [comment] 2023-02-16 16:46
> The regression appears to have started with [a5490e7](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/a5490e7d89f52f9c327148196129b7d07780e49c) (#667) .

@gayanper : could you please have a look?

**Comment by gayanper** [comment] 2023-02-17 17:59
> > The regression appears to have started with [a5490e7](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/a5490e7d89f52f9c327148196129b7d07780e49c) (#667) .
> 
> @gayanper : could you please have a look?

Will have a look

**Comment by rgrunber** [comment] 2023-02-22 18:00
Version: 2023-03 (4.27)
Build id: I20230218-1800

Fixed with the above build, so closing.

**Closed by rgrunber** 2023-02-22 18:00 UTC
Labels: bug
