### ISSUE TITLE
[Patterns] Record Patterns can cause VerifyError

### ISSUE THREAD

**Issue by marschall** [eclipse-jdt/eclipse.jdt.core#1796] opened 2023-12-30 15:09 UTC
**JDT Version**

Version: 3.19.300.v20231201-0110
Build id: I20231201-0110

**Description**

[JEP 440: Record Patterns](https://openjdk.org/jeps/440) can cause to miscompiles leading to `java.lang.VerifyError`.

**Exception**

```
Exception in thread "main" java.lang.VerifyError: Stack map does not match the one at exception handler 209
Exception Details:
  Location:
    com/acme/Reproducer$SExpressionPrinter21Record.printTo(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V @209: astore
  Reason:
    Type 'com/acme/Reproducer$Expression' (current frame, locals[1]) is not assignable to 'java/lang/StringBuilder' (stack map, locals[1])
  Current Frame:
    bci: @18
    flags: { }
    locals: { 'com/acme/Reproducer$SExpressionPrinter21Record', 'com/acme/Reproducer$Expression', 'java/lang/StringBuilder', 'com/acme/Reproducer$Expression', top, 'com/acme/Reproducer$Expression' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @209
    flags: { }
    locals: { 'com/acme/Reproducer$SExpressionPrinter21Record', 'java/lang/StringBuilder' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0000000: 2b3a 0519 05c1 0027 9900 2419 054e 2dc0
    0000010: 0027 b600 2936 0419 05c0 0027 1905 c000
    0000020: 2758 2c15 04b6 002d 57a7 00b9 2c10 28b6
    0000030: 0031 572b 3a09 1909 c100 3499 0042 1909
    0000040: 3a06 1906 c000 34b6 0036 3a07 1906 c000
    0000050: 34b6 003a 3a08 1909 c000 3419 09c0 0034
    0000060: 582c 123d b600 3f57 2a19 072c b600 1b2c
    0000070: 1020 b600 3157 2a19 082c b600 1b2b 3a0d
    0000080: 190d c100 4299 0042 190d 3a0a 190a c000
    0000090: 42b6 0044 3a0b 190a c000 42b6 0045 3a0c
    00000a0: 190d c000 4219 0dc0 0042 582c 1246 b600
    00000b0: 3f57 2a19 0b2c b600 1b2c 1020 b600 3157
    00000c0: 2a19 0c2c b600 1b2c 1029 b600 3157 a700
    00000d0: 143a 06bb 0048 5919 06b6 004a 1906 b700
    00000e0: 4dbf b1                                
  Exception Handler Table:
    bci [18, 21] => handler: 209
    bci [71, 74] => handler: 209
    bci [81, 84] => handler: 209
    bci [145, 148] => handler: 209
    bci [155, 158] => handler: 209
  Stackmap Table:
    same_frame(@44)
    same_frame_extended(@125)
    same_frame_extended(@199)
    full_frame(@209,{Object[#1],Object[#24]},{Object[#75]})
    full_frame(@226,{Object[#1],Object[#82],Object[#24]},{})

	at com.acme.Reproducer.main(Reproducer.java:12)
```

**Reproducer**

```java
package com.acme;

import java.util.Objects;

import com.acme.Reproducer.Expression.ConstantExpression;
import com.acme.Reproducer.Expression.PlusExpression;
import com.acme.Reproducer.Expression.TimesExpression;

public class Reproducer {

  public static void main(String[] args) {
    SExpressionPrinter printer = new SExpressionPrinter21Record();
    Expression twoPlusThree = new PlusExpression(new ConstantExpression(2), new ConstantExpression(3));
    System.out.println(printer.print(twoPlusThree));
  }

  interface SExpressionPrinter {

    String print(Expression e);

  }

  static final class SExpressionPrinter21Record implements SExpressionPrinter {

    @Override
    public String print(Expression e) {
      Objects.requireNonNull(e);
      StringBuilder buffer = new StringBuilder();
      printTo(e, buffer);
      return buffer.toString();
    }

    private void printTo(Expression e, StringBuilder buffer) {
      if (e instanceof ConstantExpression(int i)) {
        buffer.append(i);
      } else {
        buffer.append('(');
        if (e instanceof PlusExpression(Expression a, Expression b)) {
          buffer.append("+ ");
          printTo(a, buffer);
          buffer.append(' ');
          printTo(b, buffer);
        }
        if (e instanceof TimesExpression(Expression a, Expression b)) {
          buffer.append("* ");
          printTo(a, buffer);
          buffer.append(' ');
          printTo(b, buffer);
        }
        buffer.append(')');
      }
    }
  }

  sealed interface Expression {

    int evaluate();

    record ConstantExpression(int i) implements Expression {

      @Override
      public int evaluate() {
        return i;
      }

    }

    record PlusExpression(Expression a, Expression b) implements Expression {

      @Override
      public int evaluate() {
        return Math.addExact(a.evaluate(), b.evaluate());
      }

    }

    record TimesExpression(Expression a, Expression b) implements Expression {

      @Override
      public int evaluate() {
        return Math.multiplyExact(a.evaluate(), b.evaluate());
      }

    }

  }

}

```

**javap ECJ**

```
Classfile /Users/marschall/git/ncau-java21/ncau-java21-language/target/classes/com/acme/Reproducer$SExpressionPrinter21Record.class
  Last modified 30 Dec 2023; size 2219 bytes
  SHA-256 checksum 1bf976036dbecaf5c72713093bc0208405838291058326e6bbad6de55b648a7e
  Compiled from "Reproducer.java"
final class com.acme.Reproducer$SExpressionPrinter21Record implements com.acme.Reproducer$SExpressionPrinter
  minor version: 0
  major version: 65
  flags: (0x0030) ACC_FINAL, ACC_SUPER
  this_class: #1                          // com/acme/Reproducer$SExpressionPrinter21Record
  super_class: #3                         // java/lang/Object
  interfaces: 1, fields: 0, methods: 3, attributes: 3
Constant pool:
   #1 = Class              #2             // com/acme/Reproducer$SExpressionPrinter21Record
   #2 = Utf8               com/acme/Reproducer$SExpressionPrinter21Record
   #3 = Class              #4             // java/lang/Object
   #4 = Utf8               java/lang/Object
   #5 = Class              #6             // com/acme/Reproducer$SExpressionPrinter
   #6 = Utf8               com/acme/Reproducer$SExpressionPrinter
   #7 = Utf8               <init>
   #8 = Utf8               ()V
   #9 = Utf8               Code
  #10 = Methodref          #3.#11         // java/lang/Object."<init>":()V
  #11 = NameAndType        #7:#8          // "<init>":()V
  #12 = Utf8               LineNumberTable
  #13 = Utf8               LocalVariableTable
  #14 = Utf8               this
  #15 = Utf8               Lcom/acme/Reproducer$SExpressionPrinter21Record;
  #16 = Utf8               print
  #17 = Utf8               (Lcom/acme/Reproducer$Expression;)Ljava/lang/String;
  #18 = Methodref          #19.#21        // java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
  #19 = Class              #20            // java/util/Objects
  #20 = Utf8               java/util/Objects
  #21 = NameAndType        #22:#23        // requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
  #22 = Utf8               requireNonNull
  #23 = Utf8               (Ljava/lang/Object;)Ljava/lang/Object;
  #24 = Class              #25            // java/lang/StringBuilder
  #25 = Utf8               java/lang/StringBuilder
  #26 = Methodref          #24.#11        // java/lang/StringBuilder."<init>":()V
  #27 = Methodref          #1.#28         // com/acme/Reproducer$SExpressionPrinter21Record.printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #28 = NameAndType        #29:#30        // printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #29 = Utf8               printTo
  #30 = Utf8               (Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #31 = Methodref          #24.#32        // java/lang/StringBuilder.toString:()Ljava/lang/String;
  #32 = NameAndType        #33:#34        // toString:()Ljava/lang/String;
  #33 = Utf8               toString
  #34 = Utf8               ()Ljava/lang/String;
  #35 = Utf8               e
  #36 = Utf8               Lcom/acme/Reproducer$Expression;
  #37 = Utf8               buffer
  #38 = Utf8               Ljava/lang/StringBuilder;
  #39 = Class              #40            // com/acme/Reproducer$Expression$ConstantExpression
  #40 = Utf8               com/acme/Reproducer$Expression$ConstantExpression
  #41 = Methodref          #39.#42        // com/acme/Reproducer$Expression$ConstantExpression.i:()I
  #42 = NameAndType        #43:#44        // i:()I
  #43 = Utf8               i
  #44 = Utf8               ()I
  #45 = Methodref          #24.#46        // java/lang/StringBuilder.append:(I)Ljava/lang/StringBuilder;
  #46 = NameAndType        #47:#48        // append:(I)Ljava/lang/StringBuilder;
  #47 = Utf8               append
  #48 = Utf8               (I)Ljava/lang/StringBuilder;
  #49 = Methodref          #24.#50        // java/lang/StringBuilder.append:(C)Ljava/lang/StringBuilder;
  #50 = NameAndType        #47:#51        // append:(C)Ljava/lang/StringBuilder;
  #51 = Utf8               (C)Ljava/lang/StringBuilder;
  #52 = Class              #53            // com/acme/Reproducer$Expression$PlusExpression
  #53 = Utf8               com/acme/Reproducer$Expression$PlusExpression
  #54 = Methodref          #52.#55        // com/acme/Reproducer$Expression$PlusExpression.a:()Lcom/acme/Reproducer$Expression;
  #55 = NameAndType        #56:#57        // a:()Lcom/acme/Reproducer$Expression;
  #56 = Utf8               a
  #57 = Utf8               ()Lcom/acme/Reproducer$Expression;
  #58 = Methodref          #52.#59        // com/acme/Reproducer$Expression$PlusExpression.b:()Lcom/acme/Reproducer$Expression;
  #59 = NameAndType        #60:#57        // b:()Lcom/acme/Reproducer$Expression;
  #60 = Utf8               b
  #61 = String             #62            // +
  #62 = Utf8               +
  #63 = Methodref          #24.#64        // java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #64 = NameAndType        #47:#65        // append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #65 = Utf8               (Ljava/lang/String;)Ljava/lang/StringBuilder;
  #66 = Class              #67            // com/acme/Reproducer$Expression$TimesExpression
  #67 = Utf8               com/acme/Reproducer$Expression$TimesExpression
  #68 = Methodref          #66.#55        // com/acme/Reproducer$Expression$TimesExpression.a:()Lcom/acme/Reproducer$Expression;
  #69 = Methodref          #66.#59        // com/acme/Reproducer$Expression$TimesExpression.b:()Lcom/acme/Reproducer$Expression;
  #70 = String             #71            // *
  #71 = Utf8               *
  #72 = Class              #73            // java/lang/MatchException
  #73 = Utf8               java/lang/MatchException
  #74 = Methodref          #75.#32        // java/lang/Throwable.toString:()Ljava/lang/String;
  #75 = Class              #76            // java/lang/Throwable
  #76 = Utf8               java/lang/Throwable
  #77 = Methodref          #72.#78        // java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
  #78 = NameAndType        #7:#79         // "<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
  #79 = Utf8               (Ljava/lang/String;Ljava/lang/Throwable;)V
  #80 = Utf8               I
  #81 = Utf8               StackMapTable
  #82 = Class              #83            // com/acme/Reproducer$Expression
  #83 = Utf8               com/acme/Reproducer$Expression
  #84 = Utf8               SourceFile
  #85 = Utf8               Reproducer.java
  #86 = Utf8               InnerClasses
  #87 = Class              #88            // com/acme/Reproducer
  #88 = Utf8               com/acme/Reproducer
  #89 = Utf8               Expression
  #90 = Utf8               ConstantExpression
  #91 = Utf8               PlusExpression
  #92 = Utf8               TimesExpression
  #93 = Utf8               SExpressionPrinter
  #94 = Utf8               SExpressionPrinter21Record
  #95 = Utf8               NestHost
{
  com.acme.Reproducer$SExpressionPrinter21Record();
    descriptor: ()V
    flags: (0x0000)
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #10                 // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 23: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lcom/acme/Reproducer$SExpressionPrinter21Record;

  public java.lang.String print(com.acme.Reproducer$Expression);
    descriptor: (Lcom/acme/Reproducer$Expression;)Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=3, locals=3, args_size=2
         0: aload_1
         1: invokestatic  #18                 // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
         4: pop
         5: new           #24                 // class java/lang/StringBuilder
         8: dup
         9: invokespecial #26                 // Method java/lang/StringBuilder."<init>":()V
        12: astore_2
        13: aload_0
        14: aload_1
        15: aload_2
        16: invokevirtual #27                 // Method printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
        19: aload_2
        20: invokevirtual #31                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        23: areturn
      LineNumberTable:
        line 27: 0
        line 28: 5
        line 29: 13
        line 30: 19
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      24     0  this   Lcom/acme/Reproducer$SExpressionPrinter21Record;
            0      24     1     e   Lcom/acme/Reproducer$Expression;
           13      11     2 buffer   Ljava/lang/StringBuilder;
}
SourceFile: "Reproducer.java"
InnerClasses:
  static #89= #82 of #87;                 // Expression=class com/acme/Reproducer$Expression of class com/acme/Reproducer
  public static final #90= #39 of #82;    // ConstantExpression=class com/acme/Reproducer$Expression$ConstantExpression of class com/acme/Reproducer$Expression
  public static final #91= #52 of #82;    // PlusExpression=class com/acme/Reproducer$Expression$PlusExpression of class com/acme/Reproducer$Expression
  public static final #92= #66 of #82;    // TimesExpression=class com/acme/Reproducer$Expression$TimesExpression of class com/acme/Reproducer$Expression
  static #93= #5 of #87;                  // SExpressionPrinter=class com/acme/Reproducer$SExpressionPrinter of class com/acme/Reproducer
  static final #94= #1 of #87;            // SExpressionPrinter21Record=class com/acme/Reproducer$SExpressionPrinter21Record of class com/acme/Reproducer
NestHost: class com/acme/Reproducer

```

**javap javac**

```
Classfile /Users/marschall/git/ncau-java21/ncau-java21-language/target/classes/com/acme/Reproducer$SExpressionPrinter21Record.class
  Last modified 30 Dec 2023; size 2133 bytes
  SHA-256 checksum c075a4848e5e81b9f922b4e2a998984de45483eec1700aefecb8530445d1151b
  Compiled from "Reproducer.java"
final class com.acme.Reproducer$SExpressionPrinter21Record implements com.acme.Reproducer$SExpressionPrinter
  minor version: 0
  major version: 65
  flags: (0x0030) ACC_FINAL, ACC_SUPER
  this_class: #17                         // com/acme/Reproducer$SExpressionPrinter21Record
  super_class: #2                         // java/lang/Object
  interfaces: 1, fields: 0, methods: 3, attributes: 3
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Methodref          #8.#9          // java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
   #8 = Class              #10            // java/util/Objects
   #9 = NameAndType        #11:#12        // requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
  #10 = Utf8               java/util/Objects
  #11 = Utf8               requireNonNull
  #12 = Utf8               (Ljava/lang/Object;)Ljava/lang/Object;
  #13 = Class              #14            // java/lang/StringBuilder
  #14 = Utf8               java/lang/StringBuilder
  #15 = Methodref          #13.#3         // java/lang/StringBuilder."<init>":()V
  #16 = Methodref          #17.#18        // com/acme/Reproducer$SExpressionPrinter21Record.printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #17 = Class              #19            // com/acme/Reproducer$SExpressionPrinter21Record
  #18 = NameAndType        #20:#21        // printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #19 = Utf8               com/acme/Reproducer$SExpressionPrinter21Record
  #20 = Utf8               printTo
  #21 = Utf8               (Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
  #22 = Methodref          #13.#23        // java/lang/StringBuilder.toString:()Ljava/lang/String;
  #23 = NameAndType        #24:#25        // toString:()Ljava/lang/String;
  #24 = Utf8               toString
  #25 = Utf8               ()Ljava/lang/String;
  #26 = Class              #27            // com/acme/Reproducer$Expression$ConstantExpression
  #27 = Utf8               com/acme/Reproducer$Expression$ConstantExpression
  #28 = Methodref          #26.#29        // com/acme/Reproducer$Expression$ConstantExpression.i:()I
  #29 = NameAndType        #30:#31        // i:()I
  #30 = Utf8               i
  #31 = Utf8               ()I
  #32 = Methodref          #13.#33        // java/lang/StringBuilder.append:(I)Ljava/lang/StringBuilder;
  #33 = NameAndType        #34:#35        // append:(I)Ljava/lang/StringBuilder;
  #34 = Utf8               append
  #35 = Utf8               (I)Ljava/lang/StringBuilder;
  #36 = Methodref          #13.#37        // java/lang/StringBuilder.append:(C)Ljava/lang/StringBuilder;
  #37 = NameAndType        #34:#38        // append:(C)Ljava/lang/StringBuilder;
  #38 = Utf8               (C)Ljava/lang/StringBuilder;
  #39 = Class              #40            // com/acme/Reproducer$Expression$PlusExpression
  #40 = Utf8               com/acme/Reproducer$Expression$PlusExpression
  #41 = Methodref          #39.#42        // com/acme/Reproducer$Expression$PlusExpression.a:()Lcom/acme/Reproducer$Expression;
  #42 = NameAndType        #43:#44        // a:()Lcom/acme/Reproducer$Expression;
  #43 = Utf8               a
  #44 = Utf8               ()Lcom/acme/Reproducer$Expression;
  #45 = Methodref          #39.#46        // com/acme/Reproducer$Expression$PlusExpression.b:()Lcom/acme/Reproducer$Expression;
  #46 = NameAndType        #47:#44        // b:()Lcom/acme/Reproducer$Expression;
  #47 = Utf8               b
  #48 = String             #49            // +
  #49 = Utf8               +
  #50 = Methodref          #13.#51        // java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #51 = NameAndType        #34:#52        // append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #52 = Utf8               (Ljava/lang/String;)Ljava/lang/StringBuilder;
  #53 = Class              #54            // com/acme/Reproducer$Expression$TimesExpression
  #54 = Utf8               com/acme/Reproducer$Expression$TimesExpression
  #55 = Methodref          #53.#42        // com/acme/Reproducer$Expression$TimesExpression.a:()Lcom/acme/Reproducer$Expression;
  #56 = Methodref          #53.#46        // com/acme/Reproducer$Expression$TimesExpression.b:()Lcom/acme/Reproducer$Expression;
  #57 = String             #58            // *
  #58 = Utf8               *
  #59 = Class              #60            // java/lang/Throwable
  #60 = Utf8               java/lang/Throwable
  #61 = Class              #62            // java/lang/MatchException
  #62 = Utf8               java/lang/MatchException
  #63 = Methodref          #59.#23        // java/lang/Throwable.toString:()Ljava/lang/String;
  #64 = Methodref          #61.#65        // java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
  #65 = NameAndType        #5:#66         // "<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
  #66 = Utf8               (Ljava/lang/String;Ljava/lang/Throwable;)V
  #67 = Class              #68            // com/acme/Reproducer$SExpressionPrinter
  #68 = Utf8               com/acme/Reproducer$SExpressionPrinter
  #69 = Utf8               Code
  #70 = Utf8               LineNumberTable
  #71 = Utf8               LocalVariableTable
  #72 = Utf8               this
  #73 = Utf8               Lcom/acme/Reproducer$SExpressionPrinter21Record;
  #74 = Utf8               print
  #75 = Utf8               (Lcom/acme/Reproducer$Expression;)Ljava/lang/String;
  #76 = Utf8               e
  #77 = Utf8               Lcom/acme/Reproducer$Expression;
  #78 = Utf8               buffer
  #79 = Utf8               Ljava/lang/StringBuilder;
  #80 = Utf8               I
  #81 = Utf8               StackMapTable
  #82 = Utf8               SourceFile
  #83 = Utf8               Reproducer.java
  #84 = Utf8               NestHost
  #85 = Class              #86            // com/acme/Reproducer
  #86 = Utf8               com/acme/Reproducer
  #87 = Utf8               InnerClasses
  #88 = Utf8               SExpressionPrinter21Record
  #89 = Class              #90            // com/acme/Reproducer$Expression
  #90 = Utf8               com/acme/Reproducer$Expression
  #91 = Utf8               Expression
  #92 = Utf8               ConstantExpression
  #93 = Utf8               PlusExpression
  #94 = Utf8               TimesExpression
  #95 = Utf8               SExpressionPrinter
{
  com.acme.Reproducer$SExpressionPrinter21Record();
    descriptor: ()V
    flags: (0x0000)
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 23: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lcom/acme/Reproducer$SExpressionPrinter21Record;

  public java.lang.String print(com.acme.Reproducer$Expression);
    descriptor: (Lcom/acme/Reproducer$Expression;)Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=3, locals=3, args_size=2
         0: aload_1
         1: invokestatic  #7                  // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
         4: pop
         5: new           #13                 // class java/lang/StringBuilder
         8: dup
         9: invokespecial #15                 // Method java/lang/StringBuilder."<init>":()V
        12: astore_2
        13: aload_0
        14: aload_1
        15: aload_2
        16: invokevirtual #16                 // Method printTo:(Lcom/acme/Reproducer$Expression;Ljava/lang/StringBuilder;)V
        19: aload_2
        20: invokevirtual #22                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        23: areturn
      LineNumberTable:
        line 27: 0
        line 28: 5
        line 29: 13
        line 30: 19
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      24     0  this   Lcom/acme/Reproducer$SExpressionPrinter21Record;
            0      24     1     e   Lcom/acme/Reproducer$Expression;
           13      11     2 buffer   Ljava/lang/StringBuilder;
}
SourceFile: "Reproducer.java"
NestHost: class com/acme/Reproducer
InnerClasses:
  static final #88= #17 of #85;           // SExpressionPrinter21Record=class com/acme/Reproducer$SExpressionPrinter21Record of class com/acme/Reproducer
  static #91= #89 of #85;                 // Expression=class com/acme/Reproducer$Expression of class com/acme/Reproducer
  public static final #92= #26 of #89;    // ConstantExpression=class com/acme/Reproducer$Expression$ConstantExpression of class com/acme/Reproducer$Expression
  public static final #93= #39 of #89;    // PlusExpression=class com/acme/Reproducer$Expression$PlusExpression of class com/acme/Reproducer$Expression
  public static final #94= #53 of #89;    // TimesExpression=class com/acme/Reproducer$Expression$TimesExpression of class com/acme/Reproducer$Expression
  static #95= #67 of #85;                 // SExpressionPrinter=class com/acme/Reproducer$SExpressionPrinter of class com/acme/Reproducer

```

**Files**

- [Reproducer.java.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13798388/Reproducer.java.txt) (GitHub doesn't support .java)
- [ecj.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13798382/ecj.txt)
- [javac.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13798383/javac.txt)

**Comment by srikanth-sankaran** [comment] 2024-01-02 04:20
Even smaller reproducer:

```
public record X(int i) {

  public static void main(String[] args) {
    new Printer().print(new X(42), new StringBuilder());
  }

  static final class Printer {

    private void print(X e, StringBuilder buffer) {
      if (e instanceof X(int i)) {
      }
    }
  }
}
```

**Comment by srikanth-sankaran** [comment] 2024-01-02 04:21
I'll take a look - tentatively targeting for 4.31 M1

**Comment by srikanth-sankaran** [comment] 2024-01-02 04:49
@mpalat - assigning to you since you expressed interest - Please adjust milestone as you see fit. Thanks!

**Comment by srikanth-sankaran** [comment] 2024-01-22 09:21
> Looks like #1816 fixes this issue. would wait until that merges.

Per here: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1816#issuecomment-1885105678 that PR doesn't address the problem.  

If you want me to take over let me know. Thanks,

**Comment by mpalat** [comment] 2024-02-01 03:20
> > Looks like #1816 fixes this issue. would wait until that merges.
> 
> Per here: [#1816 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1816#issuecomment-1885105678) that PR doesn't address the problem.
> 
> If you want me to take over let me know. Thanks,

Sure Srikanth.. that would be helpful. I will reassign to you. thanks

**Comment by srikanth-sankaran** [comment] 2024-02-07 00:42
@marschall I have a point fix for the problem that works with the reduced test case I came up with. The reduced test case you have provided has external dependencies such as `import com.acme.Reproducer.Expression.ConstantExpression;` - the full test case has even more  external dependencies such as

```
import com.acme.Reproducer.Expression.ConstantExpression;
import com.acme.Reproducer.Expression.PlusExpression;
import com.acme.Reproducer.Expression.TimesExpression;
```

Where would I find these class sources so I can stub out the irrelevant portions and come up with a full self-standing test case.

I worry that I can release a fix for the minimal test case but that won't test the full case. Thanks for your help here

**Comment by srikanth-sankaran** [comment] 2024-02-07 00:43
Can you attach a zipped up version of the project in the original problem report - top comment above ? In a form that can be imported as a project into a workspace ? TIA

**Comment by srikanth-sankaran** [comment] 2024-02-07 01:22
The generated code has wrong stack map table entries:

```
  private void print(X, java.lang.StringBuilder);
    descriptor: (LX;Ljava/lang/StringBuilder;)V
    flags: (0x0002) ACC_PRIVATE
    Code:
      stack=4, locals=8, args_size=3
         0: aload_1
         1: astore        6
         3: aload         6
         5: instanceof    #16                 // class X
         8: ifeq          55
        11: aload         6
        13: astore        5
        15: aload         5
        17: checkcast     #16                 // class X
        20: invokevirtual #18                 // Method X.i:()I
        23: istore_3
        24: aload         6
        26: checkcast     #16                 // class X
        29: aload         6
        31: checkcast     #16                 // class X
        34: pop2
        35: goto          55

        38: astore        7
        40: new           #22                 // class java/lang/MatchException
        43: dup
        44: aload         7
        46: invokevirtual #24                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
        49: aload         7
        51: invokespecial #30                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        54: athrow
        55: return
      Exception table:
         from    to  target type
            20    23    38   Class java/lang/Throwable
      LineNumberTable:
        line 10: 0
        line 12: 35
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      56     0  this   LX$Printer;
            0      38     1     e   LX;
           55       1     1     e   LX;
            0      38     2 buffer   Ljava/lang/StringBuilder;
           55       1     2 buffer   Ljava/lang/StringBuilder;
           24      11     3     i   I
      StackMapTable: number_of_entries = 2
        frame_type = 255 /* full_frame */
          offset_delta = 38
          locals = [ class X$Printer, class java/lang/StringBuilder ]
          stack = [ class java/lang/Throwable ]
        frame_type = 255 /* full_frame */
          offset_delta = 16
          locals = [ class X$Printer, class X, class java/lang/StringBuilder ]
          stack = []
```

Stack map claims the exception handler at PC 38 is entered with ` locals = [ class X$Printer, class java/lang/StringBuilder ]` that is missing the argument of type `X` - resulting in Verify error.

The code in `org.eclipse.jdt.internal.compiler.codegen.CodeStream.addPatternAccessorExceptionHandler(BlockScope, boolean)` that closes various live ranges is highly suspect. Correction: Badly broken.

**Comment by srikanth-sankaran** [comment] 2024-02-08 06:54
The dance we want to do for (non-try blocks) is to transform:      

```
  [modifiers] [returnType] f(formal parameter declarations) {
     local declarations;
     some-code that among other things invokes pattern accessor
 }
```
into

```
 [modifiers] [returnType] f(formal parameter declarations) {
    try {
        local declarations;
	some-code that among other things invokes a record accessor
	} catch (Throwable t) {
	        // synthesize and throw MatchException
	}
}
```

So the synthesized catch block gets entered with initial frame.

**Comment by marschall** [comment] 2024-02-08 15:45
> @marschall I have a point fix for the problem that works with the reduced test case I came up with. The reduced test case you have provided has external dependencies such as `import com.acme.Reproducer.Expression.ConstantExpression;` - the full test case has even more external dependencies such as
> 
> ```
> import com.acme.Reproducer.Expression.ConstantExpression;
> import com.acme.Reproducer.Expression.PlusExpression;
> import com.acme.Reproducer.Expression.TimesExpression;
> ```
> 
> Where would I find these class sources so I can stub out the irrelevant portions and come up with a full self-standing test case.
> 
> I worry that I can release a fix for the minimal test case but that won't test the full case. Thanks for your help here

These are inner classes in inner classes they are in the reproducer in the first comment https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1796#issue-2060772248

**Comment by srikanth-sankaran** [comment] 2024-02-08 19:14
> > @marschall I have a point fix for the problem that works with the reduced test case I came up with. The reduced test case you have provided has external dependencies such as `import com.acme.Reproducer.Expression.ConstantExpression;` - the full test case has even more external dependencies such as
> > ```
> > import com.acme.Reproducer.Expression.ConstantExpression;
> > import com.acme.Reproducer.Expression.PlusExpression;
> > import com.acme.Reproducer.Expression.TimesExpression;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where would I find these class sources so I can stub out the irrelevant portions and come up with a full self-standing test case.
> > I worry that I can release a fix for the minimal test case but that won't test the full case. Thanks for your help here
> 
> These are inner classes in inner classes they are in the reproducer in the first comment [#1796 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1796#issue-2060772248)

Duh! Silly me. I am able to verify that the fix I have works with the full test case too and the behavior matches javac. Thanks. Stay tuned for the fix.

**Closed** 2024-02-09 09:12 UTC
Labels: bug, compiler

**Comment by marschall** [comment] 2024-02-12 10:09
Thanks a lot for picking this up and fixing it so quickly. Looking forward to a milestone build with the fixes.

**Comment by marschall** [comment] 2024-02-26 19:45
I verified it as fixed in RC1.
