### ISSUE TITLE
[Reconciler][Sealed types] Inconsistent type hierarchy with sealed classes

### ISSUE THREAD

**Issue by asdfjkluiop** [eclipse-jdt/eclipse.jdt.core#62] opened 2022-05-05 02:22 UTC
I recently changed a lot of interfaces in a rather large project of mine to be sealed and I think I found an ECJ bug in the process. I have 3 interfaces and 3 classes with the following hierarchy:

`public sealed interface Interface1 permits Class1, Interface2`
`public sealed interface Interface2 extends Interface1 permits Class2, Interface3`
`public sealed interface Interface3 extends Interface2 permits Class3`

`public non-sealed class Class1 implements Interface1`
`public non-sealed class Class2 extends Class1 implements Interface2`
`public final class Class3 extends Class2 implements Interface3`

In this setup `Class2` will have an error which says
> The hierarchy of the type Class2 is inconsistent

The thing is `Class2` still successfully compiles and runs with no problem. It also shows no error in the eclipse package explorer tree, it's not until you open the class in the code viewer that this error is shown. It also builds fine with javac which is why I'm not sure if it's an ECJ bug or something else. This bug seems to be triggered by having multiple permits on `Interface2`. That is if I remove `Interface3` from the permits list on `Interface2` then the error on `Class2` goes away, of course `Interface3` no longer compiles but that's to be expected. Any number of permits on `Interface2` will cause this with the exception of a single permit. This issue also only seems to show itself on a class which extends another class and not on `Class1` for example. The eclipse version is 2022-03 with JDK 17

**Comment by jarthana** [comment] 2022-05-05 07:04
I am unable to reproduce this issue. By any chance, are there multiple packages involved? If so, that could be same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=577872.

Could you put these in a reproducible Java project and attach here?

**Comment by asdfjkluiop** [comment] 2022-05-05 19:50
Actually yes they interfaces were in a separate package from the classes, I forgot to mention that in my original report. This is a sample project that shows the issue.
[test.tar.gz](https://github.com/eclipse-jdt/eclipse.jdt.core/files/8635553/test.tar.gz)

**Comment by srikanth-sankaran** [comment] 2024-06-13 09:43
> Actually yes, the interfaces were in a separate package from the classes, I forgot to mention that in my original report. This is a sample project that shows the issue. [test.tar.gz](https://github.com/eclipse-jdt/eclipse.jdt.core/files/8635553/test.tar.gz)

Thanks @asdfjkluiop - I think this test.tar.gz file has a problem. javac 22 complains:

```
$ ~/jdk/jdk-22/jdk-22/bin/javac -d /tmp/blah --module-source-path . `find . -name '*.java'`
./ninja.scoopta.software.test/ninja/scoopta/software/test/Interface3.java:5: error: class is not allowed to extend sealed class: Interface2 (as it is not listed in its 'permits' clause)
public sealed interface Interface3 extends Interface2 permits Class3 {
              ^
1 error
```

With the PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2561, the inconsistent hierarchy problem goes away but I am left with the same error that javac reports. Inspecting the files, I find that the attached files are in variance with your own description at the top of this defect report - So we are good. Expecting to close this soon

**Comment by srikanth-sankaran** [comment] 2024-06-13 09:51
> > Actually yes, the interfaces were in a separate package from the classes, I forgot to mention that in my original report. This is a sample project that shows the issue. [test.tar.gz](https://github.com/eclipse-jdt/eclipse.jdt.core/files/8635553/test.tar.gz)
> 
> Thanks @asdfjkluiop - I think this test.tar.gz file has a problem. javac 22 complains:
> 
> ```
> $ ~/jdk/jdk-22/jdk-22/bin/javac -d /tmp/blah --module-source-path . `find . -name '*.java'`
> ./ninja.scoopta.software.test/ninja/scoopta/software/test/Interface3.java:5: error: class is not allowed to extend sealed class: Interface2 (as it is not listed in its 'permits' clause)
> public sealed interface Interface3 extends Interface2 permits Class3 {
>               ^
> 1 error
> ```
> 
> With the PR #2561, the inconsistent hierarchy problem goes away but I am left with the same error that javac reports. Inspecting the files, I find that the attached files are in variance with your own description at the top of this defect report - So we are good. Expecting to close this soon

Ah, I see you mention experimenting with removing some of the permitted types - so please ignore

**Closed** 2024-06-14 08:27 UTC
Labels: compiler
