### ISSUE TITLE
null analysis with external annotations not working

### ISSUE THREAD

**Issue by Unrated** [eclipse-jdt/eclipse.jdt.core#514] opened 2022-11-04 14:33 UTC
Eclipse shows the following two warnings:
![grafik](https://user-images.githubusercontent.com/2292915/199999549-b0b89368-3164-40c6-b9e5-5b8204ebd78c.png)
![grafik](https://user-images.githubusercontent.com/2292915/200000693-72260dc4-9ed8-4649-a705-d5e7c34cdd4a.png)

External Annotations File "Optional.eea":

> class java/util/Optional
> empty
>  <T:Ljava/lang/Object;>()Ljava/util/Optional<TT;>;
>  <1T:Ljava/lang/Object;>()L1java/util/Optional<T1T;>;

**Comment by stephan-herrmann** [comment] 2022-11-08 20:26
Thanks for reporting.

Could you please attach a complete, tiny Eclipse project exhibiting the problem (zipped)? Be sure to include configuration files like `.project`, `.classpath`, `.settings/*`.

TIA

BTW: how did you create the .eea file? Did the Annotate command in the class file editor work, or was it manually created / imported from somewhere else?

**Comment by Unrated** [comment] 2022-11-11 12:11
.eea file was created by annotation via the file editor (ctrl+1).

[eclipsebug.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9990108/eclipsebug.zip)

**Comment by Unrated** [comment] 2023-01-24 12:07
bump. all my projects are full of errors :(

**Comment by stephan-herrmann** [comment] 2023-01-24 13:55
Sorry, the provided eclipsebug.zip had escaped my attention.

On importing the contained projects into a fresh workspace of 2022-12 (4.26) I could not reproduce any problems. 

Note, that you did not ship your compiler settings for the project, so I configured the workspace to enable annotation based null analysis. After that hovers over all relevant locations in Bug.java showed the desired null annotations. No warnings reported.

Two ideas:
* perhaps your compiler settings contained some other tweaks? Please ensure that all relevant settings are made _on the project_ so that `.settings/org.eclipse.jdt.core.prefs` contains all we need.
* Perhaps you had other stuff in your workspace that influenced the compiler? To find out you may want to do the same that I did: open eclipse on a fresh workspace and import your projects. Does it still show the problems?

**Comment by jukzi** [comment] 2024-02-14 13:23
Closing as not enough information provided. Please reopen with reproducer if any.

**Closed by jukzi** 2024-02-14 13:23 UTC
Labels: needinfo, null
