### ISSUE TITLE
[Patterns] The method xzy(Predicate<? super java.lang.String>) is not applicable for the arguments (Predicate<? super java.lang.String>)

### ISSUE THREAD

**Issue by danijelz** [eclipse-jdt/eclipse.jdt.core#2144] opened 2024-03-12 12:32 UTC
Test case:
```
public class X {
  public boolean foo(List<String> list, Object obj) {
    return obj instanceof String str && list.stream().allMatch(str::contains);
  }
}
```

The JDT compiler reports:
`The method allMatch(java.util.function.Predicate<? super java.lang.String>) in the type Stream<String> is not applicable for the arguments (java.util.function.Predicate<? super java.lang.String>)`

**Comment by srikanth-sankaran** [comment] 2024-03-14 01:40
This is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1759 - I can confirm the defect is present on 4.30 and is fixed on 4.31. Please upgrade.

**Closed** 2024-03-14 01:45 UTC
