### ISSUE TITLE
CCE: LocalDeclaration cannot be cast to class ForeachStatement

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1263] opened 2023-08-03 12:08 UTC
Using latest build I20230802-1800.
Open `org.eclipse.jdt.internal.launching.DetectVMInstallationsJob` class in the IDE.
Hold "Ctrl" and hover over the "arrows" in lambda expressions in the `run()` method.

Exception reported:
```
java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.LocalDeclaration cannot be cast to class org.eclipse.jdt.internal.compiler.ast.ForeachStatement (org.eclipse.jdt.internal.compiler.ast.LocalDeclaration and org.eclipse.jdt.internal.compiler.ast.ForeachStatement are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2f9236d8)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeEnhancedForStatement(Parser.java:3435)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:8471)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13145)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2139)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1979)
	at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:349)
	at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:312)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1081)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinks(JavaElementHyperlinkDetector.java:124)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
```

**Comment by srikanth-sankaran** [comment] 2023-08-04 04:26
Likely a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1195 

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1195#issuecomment-1612277800 for a growing list of duplicates.

It matches the scenario that the concerned method uses pattern matching instanceof expression.

**Comment by srikanth-sankaran** [comment] 2023-09-05 09:31
The PR under test for #1195 i.e. https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1349 fixes this problem too

**Comment by srikanth-sankaran** [comment] 2023-09-11 10:37
Here is a simple extract from the concerned file:

```
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Set;

public class DetectVMInstallationsJob  {

	protected void run() {
		Collection<File> candidates = null;
		Set<File> knownVMs = null;
		Collection<Object> systemVMs = Collections.EMPTY_LIST;
		if ("".equals("")) {
				systemVMs = new ArrayList<>();
				systemVMs.removeIf(t -> knownVMs.contains(null));
				for (int systemVM : new int[] { 10 }) {
					candidates.removeIf(t -> t.equals(null));
				}
		}
		for (File f : candidates) {
			String install = null;
			if (!(install instanceof String vm && vm.hashCode() != 0)) {
			}
		}
	}
}
```

**Comment by srikanth-sankaran** [comment] 2023-09-12 06:47
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1349 fixes this problem and includes a regression test from this issue. Having established clearly this is a duplicate of #1195 and is subsumed by the fix for it, I will close this issue as duplicate

**Comment by srikanth-sankaran** [comment] 2023-09-12 06:49
Duplicate of #1195

**Closed by srikanth-sankaran** 2023-09-12 06:49 UTC
Labels: bug
