### ISSUE TITLE
Search seems to work, but gives me: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.util.HashtableOfPackage.get(char[])" because "this.knownPackages" is null

### ISSUE THREAD

**Issue by davidmichaelkarr** [eclipse-jdt/eclipse.jdt.core#263] opened 2022-07-26 20:51 UTC
I've been using 2022-06 since it was released, and I use "Java Search" reasonably often.  For some reason, every Java search I run today seems to give me search results, and I have no idea whether the results are deficient, but I also get an error dialog saying this:

An internal error occurred during: "Java Search".
Cannot invoke "org.eclipse.jdt.internal.compiler.util.HashtableOfPackage.get(char[])" because "this.knownPackages" is null

The stacktrace from the log is here:

!ENTRY org.eclipse.core.jobs 4 2 2022-07-26 08:45:11.515
!MESSAGE An internal error occurred during: "Java Search".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.util.HashtableOfPackage.get(char[])" because "this.knownPackages" is null
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getPackage0(PackageBinding.java:176)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1135)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:155)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:481)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.accept(MatchLocator.java:382)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:336)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3467)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3174)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:523)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:627)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2891)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2774)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:2344)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:1572)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1169)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:607)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2055)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1416)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1535)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:676)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by stephan-herrmann** [comment] 2022-08-17 20:37
I believe this happens when your search found a type via a not-accessible package (for error-free packages `knownPackages` is initialized once and for all right in the constructor). Do you have any such error in your workspace? Or perhaps, a package was found to not exist, but later a type of that package was found in a wrong directory?

I'm not saying it's fair to throw NPE in that situation, but it might help finding the offending code and construct a test case from it. Just from looking at the exception I was unable to create a reproducing compiler test -- so perhaps this problem is search-specific.

**Comment by jukzi** [comment] 2024-06-25 15:01
Closing due to missing information

**Closed by jukzi** 2024-06-25 15:01 UTC
Labels: bug, java search, needinfo
