### ISSUE TITLE
RenamePackageTests.testImportFromMultiRoots4 failure

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#638] opened 2023-01-13 06:55 UTC
Since I20230112-1800 `RenamePackageTests.testImportFromMultiRoots4` fails on all platforms.
This is a regression from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/532

See https://download.eclipse.org/eclipse/downloads/drops4/I20230112-1800/testResults.php

```
invalid update in file A.java [in a.b.c [in srcPrg [in RenamePack1]]] package a.b.c class A class ARunner void run() B.BRunner br expected:<package a.b.c; [import p.ATest; ]public class A { pu...> but was:<package a.b.c; []public class A { pu...>

org.junit.ComparisonFailure: invalid update in file A.java [in a.b.c [in srcPrg [in RenamePack1]]]
package a.b.c
class A
class ARunner
void run()
B.BRunner br expected:<package a.b.c;

[import p.ATest;

]public class A {
pu...> but was:<package a.b.c;

[]public class A {
pu...>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.eclipse.jdt.ui.tests.refactoring.GenericRefactoringTest.assertEqualLines(GenericRefactoringTest.java:651)
at org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.helperMultiProjects(RenamePackageTests.java:488)
at org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.testImportFromMultiRoots4(RenamePackageTests.java:1349)
```

@gayanper : could you please check? I can reproduce it locally & fail disappears after reverting https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8844381127d65995e0c01ae2ce1d91ca0bdc6707 .

**Comment by gayanper** [comment] 2023-01-13 07:22
I will have a look, its strange why the merge build and PR build’s didn’t fail. How can we make sure this will not happen? Is there a way for force all tests to execute on a PR ?

**Comment by iloveeclipse** [comment] 2023-01-13 08:30
> I will have a look, its strange why the merge build and PR build’s didn’t fail

The test is in **jdt.ui** repo :-)
https://download.eclipse.org/eclipse/downloads/drops4/I20230112-1800/testresults/html/org.eclipse.jdt.ui.tests.refactoring_ep427I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by gayanper** [comment] 2023-01-15 07:51
@iloveeclipse seems the last i-build is passing all the jdt.ui.refactoring tests. You can close the issue if we don’t see any other side effects

**Comment by jukzi** [comment] 2023-05-24 10:35
Can not reproduce. seems to be fixed. should be closed.

**Closed** 2023-05-24 15:33 UTC
Labels: bug, regression
