### ISSUE TITLE
Compilation with multiple --add-exports and --release fails with ecj

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-jdt/eclipse.jdt.core#114] opened 2022-06-03 09:02 UTC
Raising this based on [Multiple --add-exports options fail with JDK 17](https://github.com/eclipse/tycho/issues/619) 

Example code 
```
import com.sun.imageio.plugins.png.PNGImageReader;
import com.sun.imageio.plugins.png.PNGImageReaderSpi;

public class Foo {
		private String unused;
}
```

The above code can be compiled with

1. <java 11vm> -jar ecj-I20220601-1800.jar --release 11 --add-exports java.desktop/com.sun.imageio.plugins.gif=ALL-UNNAMED --add-exports java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED Foo.java 
2. <java 11vm> -jar ecj-I20220601-1800.jar --release 17 --add-exports java.desktop/com.sun.imageio.plugins.gif=ALL-UNNAMED --add-exports java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED Foo.java 
3. <java 17vm> -jar ecj-I20220601-1800.jar --release 17 --add-exports java.desktop/com.sun.imageio.plugins.gif=ALL-UNNAMED --add-exports java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED Foo.java 
4. \<java17vm\> -jar ecj-I20220601-1800.jar -source 11 -target 11 --add-exports java.desktop/com.sun.imageio.plugins.gif=ALL-UNNAMED --add-exports java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED Foo.java 

but fails with 
1. <java 17vm> -jar ecj-I20220601-1800.jar --release 11 --add-exports java.desktop/com.sun.imageio.plugins.gif=ALL-UNNAMED --add-exports java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED Foo.java 

Notifications:
@akurtakov

**Comment by sravanlakkimsetti** [comment] 2022-06-17 10:41
-  java.desktop/com.sun.imageio.plugins.gif
- java.desktop/com.sun.imageio.plugins.png
are not available in ct.sym. But they are part of java.desktop.jmod. 

Need some guidance here on how to proceed. 
Should we search all the existing modules in current jvm if the exported package not available in ct.sym or issue with ct.sym

@stephan-herrmann Can you please help me here?

**Comment by sravanlakkimsetti** [comment] 2022-06-21 09:57
@iloveeclipse Can you please help in this regard?

**Comment by stephan-herrmann** [comment] 2022-06-21 12:07
At a first brief look I made some confusing observations, will try to produce some useful answer today. In general our expert for the infamous ct.sym would be Jay, no?

**Comment by iloveeclipse** [comment] 2022-06-21 12:28
I see that add exports are added correct in `org.eclipse.jdt.internal.core.ModuleUpdater.computeModuleUpdates(IClasspathEntry)` -> `org.eclipse.jdt.internal.core.ModuleUpdater.addModuleUpdate(String, Consumer<IUpdatableModule>, UpdateKind)`.

I also see the `packageUpdates` arriving correctly in `org.eclipse.jdt.internal.core.builder.NameEnvironment.collectModuleEntries(ClasspathLocation, IPath, boolean, Set<String>, String, IModule, Map<String, IModulePathEntry>)` and in `org.eclipse.jdt.internal.core.builder.ClasspathLocation.updates` being called from `org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(IWorkspaceRoot, JavaProject, SimpleLookupTable)`. Finally this lands in `org.eclipse.jdt.internal.core.builder.NameEnvironment.binaryLocations`.

Also I see it being properly set in `org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.addExports(char[], char[][])` and `org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.addResolvedExport(PlainPackageBinding, char[][])`.

Stack:
```
Thread [Worker-2: Building] (Suspended)	
	BinaryModuleBinding(ModuleBinding).addResolvedExport(PlainPackageBinding, char[][]) line: 359	
	BinaryModuleBinding(ModuleBinding).addExports(char[], char[][]) line: 286	
	IUpdatableModule$AddExports.accept(IUpdatableModule) line: 46	
	IUpdatableModule$AddExports.accept(Object) line: 1	
	ModuleUpdater.applyModuleUpdates(IUpdatableModule, IUpdatableModule$UpdateKind) line: 115	
	NameEnvironment.applyModuleUpdates(IUpdatableModule, IUpdatableModule$UpdateKind) line: 797	
	BinaryModuleBinding(ModuleBinding).completeIfNeeded(IUpdatableModule$UpdateKind) line: 259	
	BinaryModuleBinding(ModuleBinding).getExports() line: 201	
	BinaryModuleBinding.getExports() line: 174	
	BinaryModuleBinding.getDeclaredPackage(char[]) line: 213	
	ModuleBinding$UnNamedModule(ModuleBinding).getVisiblePackage(PackageBinding, char[]) line: 602	
	ModuleBinding$UnNamedModule(ModuleBinding).getTopLevelPackage(char[]) line: 551	
	LookupEnvironment.getTopLevelPackage(char[]) line: 1683	
	CompilationUnitScope.getDefaultImports() line: 685	
	CompilationUnitScope.checkAndSetImports() line: 240	
	LookupEnvironment.completeTypeBindings() line: 513	
	Compiler.internalBeginToCompile(ICompilationUnit[], int) line: 881	
	Compiler.beginToCompile(ICompilationUnit[]) line: 394	
	Compiler.compile(ICompilationUnit[], boolean) line: 444	
	Compiler.compile(ICompilationUnit[]) line: 426	
	BatchImageBuilder(AbstractImageBuilder).compile(SourceFile[], SourceFile[], boolean) line: 379	
	BatchImageBuilder.compile(SourceFile[], SourceFile[], boolean) line: 214	
	BatchImageBuilder(AbstractImageBuilder).compile(SourceFile[]) line: 311	
	BatchImageBuilder.build() line: 79	
	JavaBuilder.buildAll() line: 273	
	JavaBuilder.build(int, Map, IProgressMonitor) line: 188	
	BuildManager$2.run() line: 1024	
	SafeRunner.run(ISafeRunnable) line: 45	
	BuildManager.basicBuild(int, IncrementalProjectBuilder, Map<String,String>, MultiStatus, IProgressMonitor) line: 254	
	BuildManager.basicBuild(IBuildConfiguration, int, IBuildContext, ICommand[], MultiStatus, IProgressMonitor) line: 311	
	BuildManager$1.run() line: 400	
	SafeRunner.run(ISafeRunnable) line: 45	
	BuildManager.basicBuild(IBuildConfiguration, int, IBuildContext, MultiStatus, IProgressMonitor) line: 403	
	BuildManager.basicBuildLoop(IBuildConfiguration[], IBuildConfiguration[], int, MultiStatus, IProgressMonitor, int, boolean) line: 514	
	BuildManager.basicBuildLoop(IBuildConfiguration[], IBuildConfiguration[], int, MultiStatus, IProgressMonitor) line: 462	
	BuildManager.build(IBuildConfiguration[], IBuildConfiguration[], int, IProgressMonitor) line: 544	
	AutoBuildJob.doBuild(IProgressMonitor) line: 161	
	AutoBuildJob.run(IProgressMonitor) line: 255	
	Worker.run() line: 63	
```

But I fails to see where is that all finally results in compilation error.

**Comment by iloveeclipse** [comment] 2022-06-21 12:29
Here is the project to play with [Bug114.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/8948855/Bug114.zip)

**Comment by stephan-herrmann** [comment] 2022-06-21 16:22
First part of the confusion I mentioned: I cannot reproduce the problem with the following build of jdk-17:

    openjdk 17 2021-09-14
    OpenJDK Runtime Environment (build 17+35-2724)
    OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

but I can reproduce with

    openjdk 18-ea 2022-03-22
    OpenJDK Runtime Environment (build 18-ea+33-2077)
    OpenJDK 64-Bit Server VM (build 18-ea+33-2077, mixed mode, sharing)

(_please excuse the arbitrary selection of builds_)

**Comment by stephan-herrmann** [comment] 2022-06-21 18:52
PR #156 lets the batch compiler detect and report the error, then abort.

In the IDE, JDT/UI should raise an error in the Buildpath dialog. Would it still need an error from the compiler then?

**Comment by stephan-herrmann** [comment] 2022-06-21 21:26
Batch compiler has been fixed via PR #156, but the issue remains open for the IDE scenario.

**Comment by sravanlakkimsetti** [comment] 2022-06-22 05:05
Thanks @stephan-herrmann for the fix. In IDE we are getting 
![image](https://user-images.githubusercontent.com/77106773/174947539-79557f7d-0ae3-43d6-859b-a454fcad5ae5.png)

the import {0} cannot be resolved. Lets see what jdt ui team requires. @noopur2507 Can you please review this and let us know if any thing required from JDT compiler sode?

**Comment by iloveeclipse** [comment] 2022-06-22 05:13
I think there must be a dedicated error reported as marker, as soon as the illegal compiler config is found, plus ideally the classpath configuration page on project should disallow adding exports if release is set or vice versa.

**Comment by stephan-herrmann** [comment] 2022-06-25 09:05
With #168 merged the same error will now be reported in the IDE (as a build path error, aborting the build of the affected project).

**Comment by stephan-herrmann** [comment] 2022-06-25 09:06
No further action planned in JDT/Core, I'll still consider a validation in JDT/UI's Build Path dialog, too.

**Closed by stephan-herrmann** 2022-06-25 09:06 UTC
Labels: bug
