### ISSUE TITLE
Restricted Identifier Error in Eclipse when using Mockitos when 

### ISSUE THREAD

**Issue by vg-scylla** [eclipse-jdt/eclipse.jdt.core#1536] opened 2023-10-30 08:23 UTC
Eclipse shows an Error (Syntax error on token "RestrictedIdentifierWhen", delete this token) when using the Mockito when method which is a static import.

The error is just shown for the first occurence of a 'when' in a test Method.

If i see it correctly 'when' is a restricted identifiers in a 'switch case' statement.

Workarround is to use the fully qualified name org.mockito.Mockito.when.

I use the following version:

Eclipse JDT (Java Development Tools) Patch with Java 21 support for 2023-09 development stream 1.2.300.v20230920-0334_BETA_JAVA21 org.eclipse.jdt.java21patch.feature.group Eclipse.org

[RestrictedIdentifierWhenExample.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13202346/RestrictedIdentifierWhenExample.txt)

**Comment by iloveeclipse** [comment] 2023-10-30 15:42
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/456.

**Closed by iloveeclipse** 2023-10-30 15:42 UTC
