### ISSUE TITLE
When JRE 8 is installed along with either JDK 11, eclipse core framework is picking default java as Java 8 even though the default java is JDK 11

### ISSUE THREAD

**Issue by manasa523** [eclipse-jdt/eclipse.jdt.core#2514] opened 2024-06-03 07:49 UTC
We have one application which is built using eclipse core framework. When JRE 8 is installed along with either JDK 11, eclipse core framework of that application is picking default java as Java 8 even though the default java is JDK 11

So, when we open the application, it is failing with 

**Incompatible JVM

Version 1.8.0_341 of the JVM is not suitable for this product. Version: 11 or greater is required**

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/169026741/d6639d63-a16d-405e-b028-e03fada43792)

**Comment by iloveeclipse** [comment] 2024-06-03 08:33
It is not JDT bug, it is more related to how equinox works, but also not a bug there.
If Eclipse starts, it uses whatever is set in environment as default. 
So please make sure you either set environment right so Java 11 is default or change eclipse.ini to pick up whatever Java version you would like to see.

Closing as not a bug.

**Closed by iloveeclipse** 2024-06-03 08:33 UTC

**Comment by iloveeclipse** [comment] 2024-06-03 08:48
So check your eclipse.ini for the Java 8 being required there.

**Comment by manasa523** [comment] 2024-06-03 08:53
> So check your eclipse.ini for the Java 8 being required there.

We need to open application using default jdk-11, but it's failing with error as "required java 11 or greater version" even though default is JDK-11 on system.

Queries:
1.If default java version on system and installed java version of eclipse are same, then will eclipse.ini is updated?
2.Do we need to add required java path in eclipse.ini file to open application if multiple java versions are installed on system?
