### ISSUE TITLE
StackOverflowError on autocomplete imports on modular projects

### ISSUE THREAD

**Issue by AGT96** [eclipse-jdt/eclipse.jdt.core#2169] opened 2024-03-15 11:20 UTC
Hello:

I found a bug when I autocomplete a import on JDK11 onwards based projects. When a JDK11+ is added to the module path in the project settings and I use the autocomplete feature on imports a java.lang.StackOverflowError is throwed.

I m using CTRL + Space to autocomplete imports on class imports section.

Can you fix this?

Anything tell me please.

[stacktrace.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14614708/stacktrace.txt)

![IMG1](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/20f02a65-7272-4c79-b77a-c7699a1d1265)
![IMG2](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/2f799381-95fd-4e19-b878-d1c7e40c3e33)

**Comment by AGT96** [comment] 2024-03-15 11:43
https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/3dae16a1-4fff-4ed2-80d9-a60b12ef6dd3

**Comment by AGT96** [comment] 2024-03-15 12:21
![stacktrace img autocomplete bug on jdk11+ eclipe ide](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/683e5f35-3ef7-4f58-b6dd-632676c632ac)

**Comment by AGT96** [comment] 2024-03-17 11:56
This bug appears when install the e(fx)clipse plugin. However if this plugin is not installed, the autocomplete doesn't show the suggestions to autocomplete the import and the exception is not thrown in this case.

**Comment by iloveeclipse** [comment] 2024-04-15 15:42
Relevant part of the stack
```
java.lang.StackOverflowError
	at org.eclipse.jdt.internal.core.JavaModelCache.getInfo(JavaModelCache.java:139)
	at org.eclipse.jdt.internal.core.JavaModelManager.getInfo(JavaModelManager.java:2289)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:306)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.JavaProject.getModuleDescription(JavaProject.java:3763)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findPackagesFromRequires(SearchableEnvironment.java:356)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findPackagesFromRequires(SearchableEnvironment.java:368)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findPackagesFromRequires(SearchableEnvironment.java:368)
... and so on with findPackagesFromRequires
```

**Comment by jukzi** [comment] 2024-04-16 15:55
@AGT96 please try to increase stacksize and report if that help. for example start eclipse with
`eclipse -vmargs -Xss100m `

**Comment by AGT96** [comment] 2024-04-16 15:56
> @AGT96 please try to increase stacksize and report if that help. for example start eclipse with
> `eclipse -vmargs -Xss100m `

Thanks, I will try it.

**Comment by AGT96** [comment] 2024-04-17 07:33
Hi, with the argument -vmargs -Xss100m doesn't work, it throws the same error mentioned above.

**Comment by iloveeclipse** [comment] 2024-04-17 07:36
> Hi, with the argument -vmargs -Xss100m doesn't work, it throws the same error mentioned above.

So looks like a cycle in module graph. Should be fixed with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2346.

**Comment by jukzi** [comment] 2024-04-17 07:57
> it throws the same error mentioned above.

But with a much longer stacktrace?

**Comment by AGT96** [comment] 2024-04-17 08:00
> > it throws the same error mentioned above.
> 
> But with a much longer stacktrace?

@jukzi Yes, with the longer stacktrace.

**Comment by jukzi** [comment] 2024-04-17 08:05
since a  cycle in module graph is forbidden please report a bug to the plugins used.

**Comment by iloveeclipse** [comment] 2024-04-17 08:14
> since a cycle in module graph is forbidden please report a bug to the plugins used.

Not necessarily, as our code might have a bug too. In order to **know** where the bug is one should debug the concrete example. But since the current code uses recursive algorithm it doesn't scale anyway and will fail on complex graphs, independently if this issue here is caused by a real cycle or not.

**Closed** 2024-04-19 08:31 UTC
Labels: bug

**Comment by iloveeclipse** [comment] 2024-04-19 08:32
@AGT96 : please try **tomorrow** SDK build from https://download.eclipse.org/eclipse/downloads/, it should contain a fix.

**Comment by AGT96** [comment] 2024-04-19 08:38
@iloveeclipse Okey, What SDK i need download to try the fix?

**Comment by iloveeclipse** [comment] 2024-04-19 08:55
> What SDK i need download to try the fix?

**Latest integration** build tomorrow, the url should be https://download.eclipse.org/eclipse/downloads/drops4/I20240419-1800/ (if the nightly build would not fail for some reason).

**Comment by AGT96** [comment] 2024-04-19 09:09
@iloveeclipse I will download tomorrow to test it.

**Comment by AGT96** [comment] 2024-04-21 11:02
Hi: 

I tried the fix with the latest integration build. The autocomplete feature on modular projects works properly now, even with the e(fx)clipse plugin installed.

Thanks a lot for your attention and support !!

**Comment by AGT96** [comment] 2024-04-21 11:19
Here is the test:

https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/10d7963f-207b-4004-895f-5ae142626afa

**Comment by AGT96** [comment] 2024-04-21 11:21
The fix test:

https://github.com/eclipse-jdt/eclipse.jdt.core/assets/42464066/84234736-4641-4876-a13a-2f6576590a9a
