### ISSUE TITLE
False positive potential null pointer access warning, inside a statement controlled by boolean expression that guarantees a non-null 

### ISSUE THREAD

**Issue by Jack-McKalling** [eclipse-jdt/eclipse.jdt.core#3077] opened 2024-04-08 20:20 UTC
```
final Object obj = ...
final boolean test = obj != null;
if (test) {
    obj.getClass();
}
```
This gives a potential null pointer access warning on `obj.getClass();`, but it cannot be null.

I think this happens just because of the code prior to it including a null check somewhere. But in this case, the compiler should be able to figure out that the statement is conditioned by a boolean that already specifically claims that the object is not null.

Workaround; it works fine if the boolean declaration is moved into the condition as a literal expression like `if (obj != null)`
But the simplicity of above code should be recoverable in the first place.

**Comment by iloveeclipse** [comment] 2024-10-14 11:28
> Can't it just be transferred? There are no templates to comply with.

Done

**Comment by iloveeclipse** [comment] 2024-10-14 11:32
Complete example:
```
public class Snippet {
    public static void main(String[] args) {
        final Object obj = someCode();
        final boolean test = obj != null;
        if (test) {
            obj.getClass(); // Potential null pointer access: The variable obj may be null at this location
        }
    }

    private static Object someCode() {
        return null;
    }
}
```

@stephan-herrmann : is this is because ecj doesn't do dataflow analysis?

**Comment by srikanth-sankaran** [comment] 2024-10-14 11:41
This is a long standing issue and one that keeps coming up. 

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=538421 and its 28 duplicates

From that ticket I quote Stephan: 

```
The current null analysis in ECJ does not recognize a certain class of patterns where nullness of one variable could theoretically be inferred more precisely due to correlation to another variable.

Simple example:

   String m(boolean f) {
      String s = null;
      if (f)
         s = "good";
      // more stuff here
      if (f)
         return s.toUpperCase(); // expect no warning
      return "";
   }

Our current implementation has a very compact representation of nullness information, consisting basically of 6 bits per variable (at each point in the flow). This fixed-size representation is not able to capture any correlation information concerning an unknown number of other variables. Hence in the above example at the marked location, ECJ can only see that "s" can be either null or nonnull on some paths and it will raise a warning against the dereference.

This RFE captures the request to implement a new null analysis that would capture correlation information in order to 'understand' that examples like the above are indeed null-safe.

I'm saying "new null analysis", because I don't believe that extending the current implementation to include correlation analysis is a viable strategy. Aside from matters of code complexity, it should be kept in mind that the current analysis has been designed for small footprint (mem and cpu), good enough to be invoked on every key stroke as you type in a Java editor. The new null analysis will probably not fulfill this criterion.

This could imply, that in addition to a new analysis, we'd also need new infrastructure to invoke this analysis at selected points in time.

I should mention that no-one in the JDT team currently has the time to even start working on a detailed design of this feature, not to mention implement it, hence marking the RFE as helpwanted.
```

**Comment by srikanth-sankaran** [comment] 2024-10-14 11:43
I don't see the value in keeping this ticket open, but will wait a day for any response.

**Comment by Jack-McKalling** [comment] 2024-10-14 12:14
I understand how this issue is duplicating that one. I had no idea where to leave this report though, I can't keep up with your move between github/bugzilla, or the existing reports on the right platform.

It seems the issue you're linking to is the one I was looking for, although it is not currently open. If you say that's where the issue is tracked, and if that's the one that has enough information for it (not) to get fixed, then I wouldn't mind this one getting closed. You make a lot of sense in your explanation so I don't doubt the current stance on whether it can get fixed yet.

**Comment by stephan-herrmann** [comment] 2024-10-15 12:59
Thanks @srikanth-sankaran  for making the connection.

I mirrored the bugzilla RFE into github so we can mark this (and future requests) as duplicates more easily.

=> Closing as duplicate of #3088

**Closed by stephan-herrmann** 2024-10-15 12:59 UTC
