### ISSUE TITLE
[build][test] testBug573589_StaticImport failure 

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3083] opened 2024-10-15 05:07 UTC
Failure found in: https://download.eclipse.org/eclipse/downloads/drops4/I20241014-0530/testresults/html/org.eclipse.jdt.core.tests.compiler_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html

Occasionally.

org.eclipse.jdt.core.tests.eval.TestAll | testBug573589_StaticImport - 16 | Failure | Evaluation should not have problems : Bug573589 cannot be resolved to a type

-- | -- | -- | --

junit.framework.AssertionFailedError: Evaluation should not have problems : Bug573589 cannot be resolved to a type
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest.testBug573589_StaticImport(EvaluationContextWrapperTest.java:109)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:57)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by mpalat** [comment] 2024-10-15 05:12
Additional info: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573589

**Comment by mpalat** [comment] 2024-10-15 05:13
@gayanper Would you be able to take a look at this issue?

**Comment by iloveeclipse** [comment] 2024-10-15 05:23
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2998

**Closed by iloveeclipse** 2024-10-15 05:23 UTC
Labels: build test failure

**Comment by mpalat** [comment] 2024-10-15 05:32
@iloveeclipse Thanks for flagging this as duplicate.
A basic question of git on searching issues - The[ search with testBug573589_StaticImport ](https://github.com/eclipse-jdt/eclipse.jdt.core/issues?q=is%3Aissue+is%3Aopen+testBug573589_StaticImport+in%3A+title+) did not yield any result for me. how did you search?

**Comment by iloveeclipse** [comment] 2024-10-15 05:40
> how did you search?

I know every failed test :-)

**Comment by gayanper** [comment] 2024-10-15 11:08
Sure i can take look and see
