### ISSUE TITLE
False Positive Potential Resource Leak Warnings With Inherited AutoCloseable Classes

### ISSUE THREAD

**Issue by geoffblandrbs** [eclipse-jdt/eclipse.jdt.core#2129] opened 2024-03-11 08:20 UTC
Copied from [Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574270)

This worked fine in Eclipse 2019.06 but has been broken in each version since. This affects us as we have many "cached" resources that are giving false positives potentially masking real issues if we need to mark all the false positives to ignore.

Example code. We have a wrapper class that encapsulates a resource, here we just keep it for the life of application and provide a reference to any other class that needs it. Note we provide the reference in two ways. 

```
package test_utilities;

import javax.sql.DataSource;

public class ExampleResourceWrapper {

	private static ExampleResource internalDataSourceSingleton;

	public ExampleResourceWrapper() {
		initialise();
	}

	private static void initialise() {
		if (internalDataSourceSingleton == null) {
			// Keeps the database open until we shutdown
		  internalDataSourceSingleton = new ExampleResource();
		}
	}
	
	public static DataSource getDataSource1() {
		return internalDataSourceSingleton;
	}
	
	public static ExampleResource getDataSource2() {
		return internalDataSourceSingleton;
	}
}

```
The `ExampleResource` class just subclasses an `AutoCloseable` class to show the issue.

```
package test_utilities;

import org.apache.commons.dbcp2.BasicDataSource;

public class ExampleResource extends BasicDataSource {
	// Just a wrapper
}

```
Here's some code using the cached resource and showing the issue:

```
package test_utilities;

import javax.sql.DataSource;

public class ExampleResourceLeak {

	public static void main(String[] args) {

		// As expected no warning here 
		DataSource ds1 = ExampleResourceWrapper.getDataSource1();
		
		// False positive "potential resource leak" warning here
		DataSource ds2 = ExampleResourceWrapper.getDataSource2();

		// Code just to remove the not used warning
		ds1.getClass();
		ds2.getClass();
	}

}

```

So why does `ExampleResourceWrapper.getDataSource1()` work as expected and not show an error but `ExampleResourceWrapper.getDataSource2()` shows the False positive "potential resource leak" warning.

**Comment by jukzi** [comment] 2024-03-11 09:21
If you can show a screenshot that you can reproduce it with 4.31 RC2 
https://download.eclipse.org/eclipse/downloads/drops4/S-4.31RC2-202402290520/
then please boil the reproducer down to a single file that does not need 3rd party dependencies like javax.

**Comment by geoffblandrbs** [comment] 2024-03-11 11:51
As requested, I have tested in 4.31 RC2 and found the issue is now different but it is still not really working as I would expected. I also tested in 12-23 and found the same behaviour as in  4.31 RC2.

Now instead of non-inherited auto-closable classes working as expected but inherited autoclosable classes throwing a false-positive warning. Both inherited and non-inherited classes throw the exception or don’t inconsistently. 

To recap, 

- Eclipse 2019.06 – no warnings. 
- Eclipse later than 2019.06 to 22-21 – inherited auto-closable class throws false-positive warning.
- Eclipse 23-12 and 4.31RC2 – auto-closable class sometimes throws false-positive warning. 

I have rewritten the demo as a single class as requested and to not use a third-party library/class.

Here is a screen shot of the code in 4.31 RC2 showing the issue. 

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/6451079/c0dad552-e162-46b4-9a3b-d52337491077)

Here is a screen shot of the code in 4.31 RC2 showing the warning is inconsistent, using a different autoclosable class does not show a warning. 

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/6451079/7766463e-d3ff-4748-9bd5-c51777b632b0)

In my view a warning should only be raised where the resource has been created - not merely accessed, so the second case seems to be better. But in the wrapper class initialise method() probably instead should have the warning about a resource not being closed.

**Comment by geoffblandrbs** [comment] 2024-03-11 11:53
Here's the code:

Shows warning:

`package resource_leak_warning_test;

import java.io.FileNotFoundException;
import java.io.PrintStream;

/**
 * All-in-one class that shows the false positive with resource leaks
 */
public class AllInOneExampleResourceLeakWarnIssue1 {
	
	/**
	 * Just wrap an auto-closable for example
	 */
	public static class ExampleResource extends PrintStream {
		// Just a wrapper
		public ExampleResource(String fileName) throws FileNotFoundException {
			super(fileName);
		}
	}	
	
	/**
	 * Wrap an auto-closable to show false-positive resource warning.
	 */
	public static class ExampleResourceWrapper {

	    // Cache the resource and keep it open until we shutdown
		private static ExampleResource internalDataSourceSingleton;

		public ExampleResourceWrapper() throws FileNotFoundException {
			initialise();
		}

		private static void initialise() throws FileNotFoundException {
			if (internalDataSourceSingleton == null) {
			  // Potentially could warn about resource here
			  internalDataSourceSingleton = new ExampleResource("Testfile");
			}
		}
		
		public static PrintStream getDataSource1() {
			return internalDataSourceSingleton;
		}
		
		public static ExampleResource getDataSource2() {
			return internalDataSourceSingleton;
		}
	}

	
	public static void main(String[] args) {

		// Should not warning here
		PrintStream ds1 = ExampleResourceWrapper.getDataSource1();

		// Should not warning here
		PrintStream ds2 = ExampleResourceWrapper.getDataSource2();

		// Code just to remove the not used warning
		ds1.getClass();
		ds2.getClass();
	}

}
`

Does not show warning:

`package resource_leak_warning_test;

import java.io.StringWriter;

/**
 * All-in-one class that shows the false positive with resource leaks
 */
public class AllInOneExampleResourceLeakWarnIssue2 {
	
	/**
	 * Just wrap an auto-closable for example
	 */
	public static class ExampleResource extends StringWriter {
		// Just a wrapper
	}	
	
	/**
	 * Wrap an auto-closable to show false-positive resource warning.
	 */
	public static class ExampleResourceWrapper {

	    // Cache the resource and keep it open until we shutdown
		private static ExampleResource internalDataSourceSingleton;

		public ExampleResourceWrapper() {
			initialise();
		}

		private static void initialise() {
			if (internalDataSourceSingleton == null) {
			  // Potentially could warn about resource here
			  internalDataSourceSingleton = new ExampleResource();
			}
		}
		
		public static StringWriter getDataSource1() {
			return internalDataSourceSingleton;
		}
		
		public static ExampleResource getDataSource2() {
			return internalDataSourceSingleton;
		}
	}

	
	public static void main(String[] args) {

		// Should not warning here
		StringWriter ds1 = ExampleResourceWrapper.getDataSource1();

		// Should not warning here
		StringWriter ds2 = ExampleResourceWrapper.getDataSource2();

		// Code just to remove the not used warning
		ds1.getClass();
		ds2.getClass();
	}

}
`

As inheritance now seems to have no affect in the latest Eclipse versions here are simplified versions of the demo code:

`package resource_leak_warning_test;

import java.io.FileNotFoundException;
import java.io.PrintStream;

/**
 * All-in-one class that shows the false positive with resource leaks
 */
public class AllInOneExampleResourceLeakWarnIssue1b {
	
	/**
	 * Wrap an auto-closable to show false-positive resource warning.
	 */
	public static class ExampleResourceWrapper {

	    // Cache the resource and keep it open until we shutdown
		private static PrintStream internalDataSourceSingleton;

		public ExampleResourceWrapper() throws FileNotFoundException {
			initialise();
		}

		private static void initialise() throws FileNotFoundException {
			if (internalDataSourceSingleton == null) {
			  // Potentially could warn about resource closure here
			  internalDataSourceSingleton = new PrintStream("Testfile");
			}
		}
		
		public static PrintStream getDataSource1() {
			return internalDataSourceSingleton;
		}
	}

	
	public static void main(String[] args) {

		// Should not warning here
		PrintStream ds1 = ExampleResourceWrapper.getDataSource1();

		// Code just to remove the not used warning
		ds1.getClass();
	}

}
`

`package resource_leak_warning_test;

import java.io.StringWriter;

/**
 * All-in-one class that shows the false positive with resource leaks
 */
public class AllInOneExampleResourceLeakWarnIssue2b {
	
	/**
	 * Wrap an auto-closable to show false-positive resource warning.
	 */
	public static class ExampleResourceWrapper {

	    // Cache the resource and keep it open until we shutdown
		private static StringWriter internalDataSourceSingleton;

		public ExampleResourceWrapper() {
			initialise();
		}

		private static void initialise() {
			if (internalDataSourceSingleton == null) {
				  // Potentially could warn about resource closure here
			  internalDataSourceSingleton = new StringWriter();
			}
		}
		
		public static StringWriter getDataSource1() {
			return internalDataSourceSingleton;
		}
	}

	
	public static void main(String[] args) {

		// Should not warning here
		StringWriter ds1 = ExampleResourceWrapper.getDataSource1();

		// Code just to remove the not used warning
		ds1.getClass();
	}

}
`

**Comment by jukzi** [comment] 2024-03-11 11:59
Probably @stephan-herrmann would fix it if any.

**Comment by stephan-herrmann** [comment] 2024-03-14 22:03
Indeed the "all-in-one" source files help investigation, as I can use those to test various compiler versions from a command line, thanks.

This is what I see:

* AllInOneExampleResourceLeakWarnIssue1
  * I consistently see two warnings with **all versions** from 4.2 (2012) up to 4.31 (now) => I cannot reproduce any difference between version.
* AllInOneExampleResourceLeakWarnIssue2.java
  * `StringWriter` is what we call a resource-free closeable,  meaning: it doesn't hold any gc-resistant resource and hence closing is not required. It is internally white-listed to avoid useless warnings.

Remains the question: Is the warning in AllInOneExampleResourceLeakWarnIssue1 justified?

Note that the warning says: "_Potential_ resource leak" which expresses that the regular mode of analysis is not sure whether the method returning a resource delivers a fresh resource (which the client must close) or a shared one (where responsibility to close is undefined). Here "normal mode" refers to flow analysis *per method*, in contrast to inter-procedural flow analysis, which is in general impractical for a compiler.

Incidentally, to fill that gap we just now shipped an enhancement that allows you to tell the compiler what is your intention.  You may want to have a look at https://eclipse.dev/eclipse/news/4.31/jdt.php#annotation-based-resource-analysis - Indeed marking (the return of) methods `getDataSource*` as `@NotOwning` suffices to avoid the warning in question.

Trying this example just now, I realize that the new feature still doesn't perfectly handle *static* fields, which I'll address shortly.

**Comment by geoffblandrbs** [comment] 2024-03-18 09:42
Stephan,

Thank you for the detailed response – that is very helpful and clears up a lot of what I had been wondering about.

The annotation-based resource analysis fix sounds like a much better solution. For us this is a much better way of doing things, stating “intent” rather than “leaving it to the compiler”. This would resolve our issues and be a big improvement.

Your explanation of per method analysis and not being able to analyse inter-procedure flow makes sense, I had kind of assumed this is how it worked. 

Your explanation for `AllInOneExampleResourceLeakWarnIssue2` and `StringWriter` being white-listed makes sense, interesting to find out that there is a white-list here of “safe” resources. This explains why some resources have warnings and some don’t. 

For `AllInOneExampleResourceLeakWarnIssue1` I made a mistake here and should have gone back and tested this under 2019.6 at the time; indeed, when tested this shows both warnings there too with 2019.6. However, we do have a lot of resource warnings under later Eclipse versions that aren’t warning in 2019.6. I will need to do some more testing and find out what these cases are doing differently and write a new test class to illustrate.

**Comment by geoffblandrbs** [comment] 2024-03-26 11:28
Sorry about the delay trying to find some spare time to get back to this. 

Here's an code example of a false positive, Eclipse 2019-06 does not warn for this but subsequent Eclipse versions do, including 2024-03.

```
import java.io.IOException;
import java.nio.channels.ClosedChannelException;
import java.nio.channels.FileLock;

public class ExampleResourceLeakWarningForReference {

	public static void releaseFileLock(FileLock lockToRelease) throws IOException {
		if (lockToRelease != null) {
			try {
				lockToRelease.release();
				// The channel() method is not creating a new channel - no warning should be raised here. 
				if (lockToRelease.channel() != null && lockToRelease.channel().isOpen()) {
					lockToRelease.channel().close();
				}
				lockToRelease.close();
			}
			catch (@SuppressWarnings("unused") ClosedChannelException e) {
				// already released so do nothing
			}
		}
	}
}

```

**Comment by geoffblandrbs** [comment] 2024-03-26 11:51
Here's a second example, this one affects a lot of our code where we have an internal resource that this class manages. 

Eclipse 2019-06 does not warn for this but subsequent Eclipse versions do, including 2024-03.

```
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.SocketAddress;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLServerSocket;
import javax.net.ssl.SSLServerSocketFactory;

public class ExampleResourceLeakWarningInternalResource implements AutoCloseable {
	
  private SSLServerSocket sslServerSocket;
	
  public ExampleResourceLeakWarningInternalResource(int aSecurePort, SSLContext aSSLContext) throws IOException {
    sslServerSocket = initialise(aSSLContext, aSecurePort);
  }

  @SuppressWarnings("static-method")
  private SSLServerSocket initialise(SSLContext aSSLContext, int aPort) throws IOException {
    SSLServerSocketFactory secure_server_socket_factory = aSSLContext.getServerSocketFactory();
    // No warning here for Eclipse 2019.06 but warnings for later Eclipse versions
    SSLServerSocket server_secure_socket = (SSLServerSocket) secure_server_socket_factory.createServerSocket();
    SocketAddress endpoint = new InetSocketAddress(aPort);
    server_secure_socket.bind(endpoint, 1);
 	
    return server_secure_socket;
  }
	
  @Override
  public void close() throws IOException {
    sslServerSocket.close();
  }

}

```

**Comment by stephan-herrmann** [comment] 2024-04-02 20:02
```
		// The channel() method is not creating a new channel - no warning should be raised here. 
		if (lockToRelease.channel() != null && lockToRelease.channel().isOpen()) {
			lockToRelease.channel().close();
		}
```

The warning is expected and not reporting it was a bug in 2019.12 and earlier.

To tell the compiler that channel() does not create a new resource `@NotOwning` can be used. Otherwise the compiler cannot decide either way.

In this context stay tuned for #2258

**Comment by stephan-herrmann** [comment] 2024-04-02 20:04
```
  private SSLServerSocket initialise(SSLContext aSSLContext, int aPort) throws IOException {
    SSLServerSocketFactory secure_server_socket_factory = aSSLContext.getServerSocketFactory();
    // No warning here for Eclipse 2019.06 but warnings for later Eclipse versions
    SSLServerSocket server_secure_socket = (SSLServerSocket) secure_server_socket_factory.createServerSocket();
    SocketAddress endpoint = new InetSocketAddress(aPort);
    server_secure_socket.bind(endpoint, 1);
 	
    return server_secure_socket;
  }
```

This is wrong indeed. The analysis fails to connect the result from `createServerSocket()` with the local `server_secure_socket` and hence the return statement isn't respected. I have a fix.

**Closed** 2024-04-02 21:40 UTC
Labels: bug

**Comment by geoffblandrbs** [comment] 2024-04-03 06:12
@stephan-herrmann  Thanks for your work on this - much appreciated. Looking forward to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2258
