### ISSUE TITLE
Failed to find callers of a method with name 'run' by 'Open Call Hierarchy', but other methods just go fine.

### ISSUE THREAD

**Issue by higbos** [eclipse-jdt/eclipse.jdt.core#1721] opened 2023-12-10 12:38 UTC
I've tried eclipse 4.28 4.29 4.30, all failed. The 4.30 defail info is:
  eclipse.buildId=4.30.0.20231201-1200
  java.version=17.0.9
  java.vendor=Eclipse Adoptium
  BootLoader constants: OS=linux, ARCH=aarch64, WS=gtk, NL=zh_CN
  Framework arguments:  -product org.eclipse.epp.package.java.product
  Command-line arguments:  -os linux -ws gtk -arch aarch64 -product org.eclipse.epp.package.java.product

The exception stack trace in eclipse 'Error Log' is:
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.ClassScope.problemReporter()" because "this.scope" is null
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2817)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getExactMethod(SourceTypeBinding.java:1835)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findExactMethod(Scope.java:1340)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getMethod(Scope.java:3132)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:1023)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:838)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1157)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolveIfStatement(IfStatement.java:291)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:317)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:668)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:576)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1505)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:670)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2077)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1387)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1433)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1553)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:675)
	at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
	at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) 

When I tried to cancel the checkbox 'Application libraries' in 'Search in', all goes fine.

**Comment by iloveeclipse** [comment] 2024-05-08 15:38
Please
1) Try with latest 4.32 integration SDK build from https://download.eclipse.org/eclipse/downloads/
2) If still reproducible, attach updated stack trace and steps to reproduce.

**Comment by jukzi** [comment] 2024-06-25 14:57
Closing due to missing information

**Closed by jukzi** 2024-06-25 14:57 UTC
Labels: needinfo
