### ISSUE TITLE
Enum class which has annotated constructor generated by ECJ is not compatible with java compiler.

### ISSUE THREAD

**Issue by raghucssit** [eclipse-jdt/eclipse.jdt.core#1964] opened 2024-02-06 16:14 UTC
Use the attached project to reproduce the issue.
**[EnumError.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14183171/EnumError.zip)**
**Steps to reproduce:**
1.	Compile the SimpleEnum.java using ECJ with below command.
`java -jar ecj-nightly.jar -17 -cp . SimpleEnum.java`
2.	Compile the Client.java using java compiler using below command.
`javac -cp . Client.java`
**Expected:**
Client.java should compile successfully.
**Actual:**
```
Client.java:3: error: cannot access SimpleEnum
                System.out.println("CONST:" + SimpleEnum.CONST);
                                              ^
  bad class file: ./SimpleEnum.class
    class file is invalid for class SimpleEnum
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Client.java:3: error: cannot access Byte
                System.out.println("CONST:" + SimpleEnum.CONST);
                                            ^
  bad class file: /modules/java.base/java/lang/Byte.class
    bad RuntimeInvisibleParameterAnnotations attribute: toString(byte)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Client.java:3: error: cannot access System
                System.out.println("CONST:" + SimpleEnum.CONST);
                ^
  bad class file: /modules/java.base/java/lang/System.class
    bad RuntimeInvisibleParameterAnnotations attribute: registerNatives()
    Please remove or make sure it appears in the correct subdirectory of the classpath.
3 errors
```

**Notes:**

- If we use the generated SimpleEnum class with ECJ it works fine.
- If we compile the SimpleEnum with java compiler and use it with java compiler it works fine.
- If we use annotation in class constructor it works fine but not in Enum constructor.

**Comment by iloveeclipse** [comment] 2024-02-06 16:22
Looking at the bytecode that ecj and javac produce, the ecj writes parameter annotation on enum constructor differently to javac and javac doesn't like or expect "ecj" format. The question is: who is right here? Bug in ecj or javac or just not clear specification?

@stephan-herrmann : is this something you can look at? I believe I saw few annotation related fixes from you recently, may be it is something you are familiar with.

**Comment by srikanth-sankaran** [comment] 2024-02-23 07:56
This is very likely the same as or closely related to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/205

I ran out of time for 4.31 and it is quite late now - Will certainly try to close this early in 4.32 M1

**Comment by srikanth-sankaran** [comment] 2024-03-07 03:45
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/205#issuecomment-1982295539 - there is some evidence javac encounters an AIOOB and swallows that but reports the class file as being bad

**Comment by srikanth-sankaran** [comment] 2024-03-07 03:47
Closing this as a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/205 - I will add a note in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/205 to include the test from here for regression test purposes.

**Closed by srikanth-sankaran** 2024-03-07 03:47 UTC
