### ISSUE TITLE
[23] General Release Activities

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2213] opened 2024-03-25 03:29 UTC
Top Level for bug general release activities for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2212

Increase the bundle service version
This must not use the same version as the base. As always, we increase the service segment by 50 for the beta work ==> 3.x. 50
(e.g. 0 -> 50, 1 -> 50, 100 -> 150).

Tasks:

-  https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1647
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1650
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1649
- https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/494
- https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/499
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2961
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2962
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2963
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2350
 
refer: [[A similar work](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577682#)]
 ([Also similar work in previous release](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2163)

After this:

- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2964
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1660

**Comment by stephan-herrmann** [comment] 2024-09-11 18:00
gathering some links now that building, full testing and provisioning are becoming the bottle neck towards Java 23 GA:

### Tests

https://ci.eclipse.org/releng/job/YPBuilds/job/ep433Y-unit-cen64-gtk3-java23/lastCompletedBuild/testReport/

:x: currently 478 failures, some fresh, some older then the job history on jenkins
* many of those in jdt.ui can be locally reproduced -> over to [eclipse-jdt/eclipse.jdt.ui#1639](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1639)

### Update site

https://download.eclipse.org/eclipse/updates/4.33-Y-builds/

* Installation into Eclipse SDK 4.33 Release works :heavy_check_mark: 
   * passes smoke test: can select Java compliance "23 (BETA)" :heavy_check_mark: 

### Patch builds

* Build: https://ci.eclipse.org/releng/job/YPBuilds/job/P-build/ last run 4 Sept :question:
* Result: https://download.eclipse.org/eclipse/updates/4.33-P-builds
   * looks like a composite site but does not offer anything for installation
   * latest child https://download.eclipse.org/eclipse/updates/4.33-P-builds/P20240904-0150
      * pretends to install OK, but in fact installs nothing into SDK 4.33 Release, because it tries to patch an older version of jdt feature :x:
      * in previous attempts with a matching SDK version (jdt 3.19.600.v20240827-1800) it claimed to not be applicable to the current configuration, turned out this is p2's way of telling us that one of the plugins now depends on commonmark, which isn't included (see also https://github.com/eclipse-equinox/p2/issues/541)

TODOs
* update the patch feature to refer to jdt feature 3.19.600.v20240903-0240
* include org.commonmark and org.commonmark-gfm-tables (both in 0.22.0.v20240316-0700) into the patch feature, either physically included or by a composite site pointing, e.g., to https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0
* there may be more

**Comment by stephan-herrmann** [comment] 2024-09-11 21:44
> ### Tests
> 
> https://ci.eclipse.org/releng/job/YPBuilds/job/ep433Y-unit-cen64-gtk3-java23/lastCompletedBuild/testReport/
> 
> ❌ currently 478 failures, some fresh, some older then the job history on jenkins
> 
> * many of those in jdt.ui can be locally reproduced -> over to [eclipse-jdt/eclipse.jdt.ui#1639](eclipse-jdt/eclipse.jdt.ui#1639)

I came to conclude that this is a JIT bug in JDK 23 ea. The following option avoids the problem:
```
-XX:CompileCommand=exclude,org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer::getExtendedRange
```

We should consider:
* adding a big red alert
* automatically adding these options when installing the java 23 patch (via `META-INF/p2.inf`)
* adding these options in the pom of o.e.j.ui.tests (right after `${leakTestsArgLine}`).

**Comment by stephan-herrmann** [comment] 2024-09-11 22:08
The [Y-builds job ](https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.33/) claims to run daily ("Daily Maintenance Builds"), but the last runs where only these:
* 9 Sept
* 31 Aug

Seemingly caused by this change: https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.33/jobConfigHistory/showDiffFiles?timestamp1=2024-08-23_10-00-01&timestamp2=2024-08-31_13-20-18

I kindly ask to ensure that daily really means daily from now on.

@MohananRahul

**Comment by MohananRahul** [comment] 2024-09-12 01:47
Scheduled it to run daily,

**Comment by jarthana** [comment] 2024-09-12 09:56
>     * include org.commonmark and org.commonmark-gfm-tables (both in 0.22.0.v20240316-0700) into the patch feature, either physically included or by a composite site pointing, e.g., to https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0

I like the latter option and would like to take a stab at it. Any pointers on how to go about it?

**Comment by stephan-herrmann** [comment] 2024-09-12 10:38
> Checking with @sravanlakkimsetti on how to go about this. Will take this up with his inputs.

I made local experiments with hand-crafted meta data like these:

* `compositeContent.xml`
```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeMetadataRepository version='1.0.0'?>
<repository name='REPOSITORY NAME' type='org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository' version='1.0.0'>
  <properties size='3'>
    <property name='p2.timestamp' value='TIMESTAMP'/>
    <property name='p2.compressed' value='true'/>
    <property name='p2.atomic.composite.loading' value='true'/>
  </properties>
  <children size='2'>
    <child location='PATHTOPBUILD_SITE'/>
    <child location='https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0'/>
  </children>
</repository>
```
* `compositeArtifacts.xml`
```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeArtifactRepository version='1.0.0'?>
<repository name='REPOSITORY NAME' type='org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository' version='1.0.0'>
  <properties size='3'>
    <property name='p2.timestamp' value='TIMESTAMP'/>
    <property name='p2.compressed' value='true'/>
    <property name='p2.atomic.composite.loading' value='true'/>
  </properties>
  <children size='2'>
    <child location='PATHTOPBUILD_SITE'/>
    <child location='https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0'/>
  </children>
</repository>
```

Replace the three all-caps placeholders with real values and that should be it.

I also played with adding this in `feature.xml` under `<requires>`:
```
      <import plugin="org.commonmark" version="0.22.0"/>
      <import plugin="org.commonmark-gfm-tables" version="0.22.0"/>
```
Not sure if that is of any value, though :) (since the dependency is already present in the ..core.manipulation plugin).

**Comment by stephan-herrmann** [comment] 2024-09-13 21:11
For posterity:
* much discussion on creating the patch feature happened in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2341
* in the end the change was merged via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2344
* the resulting update site was successfully tested: https://download.eclipse.org/eclipse/updates/4.33-P-builds/P20240913-0620
  * installs into SDK 4.33 as well as into Java IDE 2024-09
  * passes smoke tests

So even if ideas exist to improve this, we seem to be good for this iteration. 

Actually it's a rare situation that new dependencies will be added on behalf of a feature patch.


And finally, some hints on building the patch feature locally:
@sravanlakkimsetti recommended:
```
mvn -f eclipse.platform.releng.tychoeclipsebuilder/java23patch/pom.xml clean verify -Pjava23patch -DskipTests=true
```

@merks reported success with this command;
```
$mvn clean verify -Pbuild-individual-bundles -Duser.home=D:/Users/test35 -DfeatureToPatchVersion=3.19.600.v20240903-0240 -DfeatureToPatch=org.eclipse.jdt -DversionRangeForPatch="[3.19.600.v20240903-0240,3.19.600.v20240903-0240]"
```

**Comment by stephan-herrmann** [comment] 2024-09-13 21:42
> I came to conclude that this is a JIT bug in JDK 23 ea. The following option avoids the problem:
> 
> ```
> -XX:CompileCommand=exclude,org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer::getExtendedRange
> ```
> [...]
> * automatically adding these options when installing the java 23 patch (via META-INF/p2.inf)

Being addressed in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2954

**Comment by stephan-herrmann** [comment] 2024-09-14 22:06
> ### Tests
> 
> https://ci.eclipse.org/releng/job/YPBuilds/job/ep433Y-unit-cen64-gtk3-java23/lastCompletedBuild/testReport/
> 
> ❌ currently 478 failures, some fresh, some older then the job history on jenkins
> 
> * many of those in jdt.ui can be locally reproduced -> over to [eclipse-jdt/eclipse.jdt.ui#1639](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1639)

Finally the workaround for the JIT-bug worked leaving us with only [3 failures in JDT](https://ci.eclipse.org/releng/job/YPBuilds/job/ep433Y-unit-cen64-gtk3-java23/25/testReport/), all in ASTRewritingModifyingCopyTest. And guess what: all three show the infamous NPE without any `null`:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.dom.rewrite.TargetSourceRangeComputer$SourceRange.getStartPosition()" because "range" is null
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.getExtendedEnd(ASTRewriteAnalyzer.java:274)
```

So o.e.j.c.tests.model needs the same JIT workaround, too.

**Comment by stephan-herrmann** [comment] 2024-09-15 11:34
> So o.e.j.c.tests.model needs the same JIT workaround, too.

Done with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2957

**Comment by stephan-herrmann** [comment] 2024-09-15 20:47
Fresh status update:

### Tests

https://ci.eclipse.org/releng/job/YPBuilds/job/ep433Y-unit-cen64-gtk3-java23/26/testReport/ lists only a single test failure:
* org.eclipse.releng.tests.BuildTests.testComparatorLogSize
   * "Unanticipated comparator log file has increased in size, indicating a regression. See https://download.eclipse.org/eclipse/downloads/drops4/Y20240915-1000/buildlogs/comparatorlogs"
   * None of the files with difference are related to the Java23 patch feature so this should not be relevant.

Ergo: From a test suite p.o.v. we are good to go! :heavy_check_mark: 

### Update site

Had already been successful during my previous summary. :heavy_check_mark: 

### Patch build

Also patch builds run daily now at 5am and will pick up the Y-build of the previous day.
* :warning:  only adding child repos to the composite seems to lag - @MohananRahul does this step still require a manual trigger? Perhaps to await sanity checking before a new build goes live?

Installation from https://download.eclipse.org/eclipse/updates/4.33-P-builds/ succeeds and passes smoke tests. :heavy_check_mark: 

### JIT-bug workaroud

As mentioned, the landslide of failures in our test suite was caused by a JIT bug in JVM 23.

As a bonus feature, installing jdt.core now automatically adds the matching workaround into eclipse.ini, to make running Eclipse **on** Java 23 safe. :heavy_check_mark:

**Comment by stephan-herrmann** [comment] 2024-09-20 18:24
The feature has been released and shipped.

**Closed by stephan-herrmann** 2024-09-20 18:24 UTC
