### ISSUE TITLE
JDT Core throws EmptyStackException

### ISSUE THREAD

**Issue by r0texx** [eclipse-jdt/eclipse.jdt.core#3360] opened 2024-11-27 19:24 UTC
Hello,

I'm trying to parse a valid Java code using Eclipse JDT:
```java
package com;

public class TestClass {
    public static void testMethod(TestInterface test) {
        TestInterface test2 = test instanceof TestInterface ? test : null;
    }
}

interface TestInterface {
}
```

But it throws the following exception:
```
Exception in thread "main" java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:103)
	at java.base/java.util.Stack.pop(Stack.java:85)
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.pop(OperandStack.java:85)
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.pop(OperandStack.java:109)
	at org.eclipse.jdt.internal.compiler.ast.ConditionalExpression.generateCode(ConditionalExpression.java:322)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.generateCode(LocalDeclaration.java:171)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:387)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:323)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:759)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:829)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:935)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1173)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:786)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver$ECJCompilationUnitResolver.resolve(CompilationUnitResolver.java:92)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1071)

```

**Comment by iloveeclipse** [comment] 2024-11-27 20:27
It would be helpful if you would also provide the snippet that parses the code and produces exception. Could be just programming error, who not necessarily JDT bug.

**Comment by r0texx** [comment] 2024-11-27 20:41
Hey @iloveeclipse,

Please use the snipped from the following report: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2386

**Comment by srikanth-sankaran** [comment] 2024-11-28 01:00
You haven't mentioned what version you are on and whether you tried the latest bits. This could be a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3042

**Comment by srikanth-sankaran** [comment] 2024-11-28 01:49
OK, you don't need the AST parser code to reproduce. Just pasting the snippet above into 4.33 *with* the compiler option `Preserve unused (never read) local variables` checked *off* would reproduce the problem.

This is the same as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3042 - closing as duplicate.

**Closed by srikanth-sankaran** 2024-11-28 01:49 UTC
