### ISSUE TITLE
The field X is not visible: when using a private static final field of a Class in an annotation on top of that class

### ISSUE THREAD

**Issue by jmini** [eclipse-jdt/eclipse.jdt.core#2355] opened 2024-04-18 13:03 UTC
Given this source code:

```java
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName(value = AClass.DISPLAY_NAME)
public class AClass {
	private static final String DISPLAY_NAME = "test"; 
	
	@Test
	void testName() throws Exception {
		
	}
}
```

With JUnit 5 on the classpath (maven coordinates: `org.junit.jupiter:junit-jupiter:5.9.2`).

---

When compiling with javac, there is this error:
```
AClass.java:9: error: DISPLAY_NAME has private access in AClass
@DisplayName(value = AClass.DISPLAY_NAME)
                           ^
error: Class names, 'compile', are only accepted if annotation processing is explicitly requested
2 errors
```

Command line:
```
javac compile AClass.java -classpath /_path_to_/org/junit/jupiter/junit-jupiter/5.9.2/junit-jupiter-5.9.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar:/_path_to_/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/_path_to_/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar:/_path_to_/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-params/5.9.2/junit-jupiter-params-5.9.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar:/_path_to_/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar
```

---

In older Eclipse IDE version there was an error. With newer version it is no longer present.

<img width="480" alt="Example code" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1222165/c780c380-7f0e-4c17-96e2-5547788920da">

(opened in a regular java project, with the run of the quick action "Add Junit5 on the classpath" to get the dependencies).

---

When testing with `ejc`, with version  `3.31.0` and earlier there is this error:

```
----------
1. ERROR in /Users/jbr/Code/Workspace/aproject/src/aproject/AClass.java (at line 9)
	@DisplayName(value = AClass.DISPLAY_NAME)
	                            ^^^^^^^^^^^^
The field AClass.DISPLAY_NAME is not visible
----------
1 problem (1 error)
```

With command:
```
./ecj AClass.java -1.8 -classpath /_path_to_/org/junit/jupiter/junit-jupiter/5.9.2/junit-jupiter-5.9.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar:/_path_to_/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/_path_to_/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar:/_path_to_/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-params/5.9.2/junit-jupiter-params-5.9.2.jar:/_path_to_/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar:/_path_to_/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar
```

* `-1.8` can be replaced by any version where annotations are supported.
* `./ecj` is a way to run the eclipse compiler from the command line. One way is [with jbang](https://github.com/jmini/jdt-experiments/blob/master/run-ecj-with-jbang/README.adoc) like this: `jbang org.eclipse.jdt:ecj:3.31.0`

With version `3.32.0` and newer, there is no error anymore.

**Comment by srikanth-sankaran** [comment] 2024-05-08 05:12
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1216

**Closed by srikanth-sankaran** 2024-05-08 05:12 UTC
Labels: bug, compiler
