### ISSUE TITLE
[Sealed types] Proper sealing of hierarchy rejected in incremental builds if permitted class is generic

### ISSUE THREAD

**Issue by konczdev** [eclipse-jdt/eclipse.jdt.core#3488] opened 2024-12-26 11:31 UTC
The compiler incorrectly reports that a generic class is not a permitted subtype in a sealed class hierarchy, even when it's explicitly listed in the permits clause.

Minimal example to reproduce:

```java
public sealed abstract class Message permits Request {
    private final String id;
    
    protected Message(String id) {
        this.id = id;
    }
}

public final class Request<T> extends Message {  // Error here
    private final T payload;
    
    public Request(String id, T payload) {
        super(id);
        this.payload = payload;
    }
}
```

Expected behavior:
- The code should compile since Request is explicitly listed in Message's permits clause
- The addition of generic type parameters should not affect the sealed class hierarchy

Actual behavior:
- Compiler error: "The class Request cannot extend the class Message as it is not a permitted subtype of Message"
- Removing the generic type parameter <T> makes the error disappear

This appears to be a bug in handling generic type parameters within sealed class hierarchies.

Java version: 17 (Eclipse Temurin jdk-17.0.11+9)

Eclipse IDE for Eclipse Committers (includes Incubating components)

Version: 2024-12 (4.34.0)
Build id: 20241128-0757

**Comment by srikanth-sankaran** [comment] 2024-12-26 12:04
> This appears to be a bug in handling generic type parameters within sealed class hierarchies.
> 
> Java version: 17 (Eclipse Temurin jdk-17.0.11+9)
> 
> Eclipse IDE for Eclipse Committers (includes Incubating components)
> 
> Version: 2024-12 (4.34.0) Build id: 20241128-0757

I don't think these version numbers look right. 

This problem is not reproducible on Eclipse SDK 4.33 or 4.34 or on master/HEAD.

I intend to close this as not reproducible. 

It is likely the Temurin build is using an ancient version of JDT plugins.

**Comment by konczdev** [comment] 2024-12-26 12:21
@srikanth-sankaran 
Here is a freshly downloaded [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2024-12/r/eclipse-ide-java-developers)

![image](https://github.com/user-attachments/assets/b25d46f2-28e4-440b-8954-558ceac324d3)

**Comment by konczdev** [comment] 2024-12-26 12:22
JDT plugin versions:
![image](https://github.com/user-attachments/assets/75f126cf-a6bf-4805-83fe-0e794177a22c)

**Comment by konczdev** [comment] 2024-12-26 12:34
@srikanth-sankaran I made an observation: if I clean the project the error is gone until I touch the affected file and save. After saving the error shows.

**Comment by srikanth-sankaran** [comment] 2024-12-27 01:43
> @srikanth-sankaran I made an observation: if I clean the project the error is gone until I touch the affected file and save. After saving the error shows.

Thanks for that tip - reproduced. Looks like a defect in incremental building. Investigating ...

**Comment by srikanth-sankaran** [comment] 2024-12-27 02:18
Works fine in 3.43. Mea cupla :-(

**Closed** 2024-12-27 03:05 UTC
Labels: bug, regression, compiler

**Comment by konczdev** [comment] 2024-12-27 08:15
Thank you!
