### ISSUE TITLE
Increased compilation time with Eclipse 4.12+

### ISSUE THREAD

**Issue by Domare90** [eclipse-jdt/eclipse.jdt.core#549] opened 2022-11-18 12:51 UTC
Switching to newer Eclipse versions we could identify a noticable increase in compilation time for the same code.
I've attached an example project containing some repeated generic code reproducing the actual constellation that we have. With Eclipse 2019-03 this compiles in around **1 minute**, while with all Eclipse versions beginning with 2020-03 it requires nearly **7 minutes** to compile, effectively leading to an increased compile time of hours in some larger projects. Also tested the latest 2022-09 which shows the same behavior.

In the profiling I can see that basically all of the time is spent in **org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes()** drilling down to **org.eclipse.jdt.internal.compiler.lookup.TypeSystem.HashedParameterizedTypes**. Here you can also see a snippet of the profiling when compiling the attached test project with 2019-03 and 2022-06.
**2019-03**
![profiling-2019-03](https://user-images.githubusercontent.com/107324920/202706437-b76cb8da-7d3a-45ca-8ada-b7c7d050cdb9.JPG)
**2022-06**
![profiling-2022-06](https://user-images.githubusercontent.com/107324920/202706429-15a34c77-ea58-4fc6-8931-a9f5bf22f1df.JPG)

Analyzing this further I noticed that the hashCode() implementation of **org.eclipse.jdt.internal.compiler.lookup.TypeSystem.HashedParameterizedTypes.PTBKey** has been changed beginning with 2020-03. In 2019-03 it used all three fields *type*, *enclosingType* and *arguments*, while in the newer versions *enclosingType* has been dropped (while still being contained in the equals() implementation though).

As I don't have an JDT development setup, I've modified the bytecode of the hashCode() implementation in 2022-06 and afterwards the compile time then instantly dropped down to the same level as with 2019-03.

Example project: [compile-perf.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10041321/compile-perf.zip)

**Comment by iloveeclipse** [comment] 2022-11-18 13:17
> As I don't have an JDT development setup

Can you please try: https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment

Would be great if you could provide a PR with your patch & ideally with a regression test (also OK if that would be a manual one, since performance tests tend to be unstable).

The HashedParameterizedTypes.PTBKey code in question was added by https://bugs.eclipse.org/bugs/show_bug.cgi?id=521438  / 48a3a3eb7ea3d5a31b91fda5c892849f5bc403c6 to fix compilation performance issue. The specific change that **removed** the hash calculation of enclosingType was done in 716dc3e8bf36c9398625bc368b0e0fde4379794d.

@brychcy : would you please give a hint why [this change](https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/137903/10/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/TypeSystem.java#125) was necessary? I don't see it immediately reading the bug / patch.

**Comment by brychcy** [comment] 2022-11-21 12:56
From a quick look at the code: when a PTB (ParameterizedTypeBinding)  is created for an URB (UnresolvedReferenceBinding) as  genericType, the enclosingType is null. If the URB is resolved, the enclosingType is updated in PTBKey.swapUnresolved(...) and then possibly non-null. 
But the hashCode of the PTBKey instance must not change - so the hashCode of enclosingType cannot be used in PTBKey.hashCode().

IIRC the class file format actually has some metadata that  tells if a referenced type is nested or not, but ecj doesn't use that at all and instead just uses some heuristics if the name contains a "$". Maybe that metadata could be used to setup an enclosingType URB for an URB without resolving it. But that's just speculative - it would be a bigger rewrite, and maybe I remember that wrong anyway or maybe it still wouldn't help in this situation.

**Comment by iloveeclipse** [comment] 2022-11-21 15:47
Thanks Til. So it is about hashCode() stability.

**Comment by Domare90** [comment] 2022-11-22 07:55
Sorry for the late response but was quite busy.
Thanks Till for the explanation. Just tested your commit, which works perfect :)

**Comment by iloveeclipse** [comment] 2022-11-22 08:12
@brychcym @Domare90 : do you ming to add a regression test?

**Comment by Domare90** [comment] 2022-11-22 13:23
@iloveeclipse I've created a performance test that shows the difference in execution times with and without the fix of #551. Maybe @brychcy has a different idea on how to reliably test this, in case this does not suffice.

**Comment by brychcy** [comment] 2022-11-23 17:15
Thanks for the test. 
FYI: We now have to wait a few days until Eclipse 4.26 is done.

**Comment by brychcy** [comment] 2022-12-06 07:15
The fix is now contained in the integration builds in https://download.eclipse.org/eclipse/downloads/.

It looks like there are currently still some issues in PDE and/or Ant support, see https://github.com/eclipse-pde/eclipse.pde/issues/419

@Domare90, if you don't need any of that, you can already try with e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20221205-1800/

**Closed** 2023-01-10 06:52 UTC
Labels: regression, performance
