### ISSUE TITLE
[19] JEP 405: Record Patterns (First Preview)

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#85] opened 2022-05-16 08:42 UTC
JEP 405: Record Patterns has been targeted for Java 19 as a preview feature. This will require considerable changes from grammar all the way up to the code generation and DOM model. The specification is [here](http://cr.openjdk.java.net/~gbierman/jep427+405/jep427+405-20220426/specs/patterns-switch-record-patterns-jls.html#jls-6.3.3.2)

**Comment by kriegaex** [comment] 2022-09-11 10:35
In order to avoid many upstream merges from JDT Core int AspectJ, I would like to wait as long as possible, until only minor changes for Java 19 remain. Are you expecting this to be ready for Java 19 GA on September 20th or shortly thereafter? Of course, I am going to wait as long as it takes, I am just asking.

**Comment by jarthana** [comment] 2022-09-16 06:38
> In order to avoid many upstream merges from JDT Core int AspectJ, I would like to wait as long as possible, until only minor changes for Java 19 remain. Are you expecting this to be ready for Java 19 GA on September 20th or shortly thereafter? Of course, I am going to wait as long as it takes, I am just asking.

We always merge the language feature changes right after the GA and not before that. Hope this helps.

**Comment by kriegaex** [comment] 2022-09-16 12:24
Of course you merge after GA, which is fine. But that was not the question. I was unsure about whether this was already implemented or not, because the issue is listed as open. I do not know your GitHub issue status workflow and how you map subtasks to this overarching issue. I shall just wait then, sorry for the noise.

**Comment by iloveeclipse** [comment] 2023-02-28 08:06
@jarthana : please close if fixed or set other milestone, [BETA_JAVA19](https://github.com/eclipse-jdt/eclipse.jdt.core/milestone/13) is not valid anymore.

**Comment by mpalat** [comment] 2023-03-22 01:33
Closing this as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/481 is the latest

**Closed by mpalat** 2023-03-22 01:33 UTC
