### ISSUE TITLE
UI Freezes since 2023-09

### ISSUE THREAD

**Issue by gigermocas** [eclipse-jdt/eclipse.jdt.core#1728] opened 2023-12-11 11:26 UTC
I've been having constant UI freezes on my eclipse environment since updating to the 2023-09 release, triggering from simple copy/paste operations and function drill downs on java code. 2023-06 is working fine.

I did open first a more generic issue on https://github.com/eclipse-platform/.github/issues/157 first, but I think it was prematurely closed as not planed due to a miscommunication, and my last message was not seen (?)

Eclipse 2023-12 was released so I made a clean installation (with no external plugins), and imported all my projects and I'm experiencing the same behavior.
[trace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13633960/trace.log)

**Comment by iloveeclipse** [comment] 2023-12-11 11:41
What exactly is in your workspace, how many projects, targeting which Java version? 
Any chance for steps to reproduce ?

**Comment by jukzi** [comment] 2023-12-12 18:02
please take a serious sampling snapshot with for example https://visualvm.github.io/ and post stacktrace of hotspots or make the full result available for download

**Comment by gigermocas** [comment] 2023-12-13 11:43
I took a couple of snapshots here, hope it helps
[snapshots.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13660241/snapshots.zip)

**Comment by jukzi** [comment] 2023-12-13 14:34
Thanks, i can read them. however i don't see an obvious error despite that the compilation should not happen in the UI Thread
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/c7e8494f-edac-4a39-a1b2-f47caf492714) but in the background. If you can contribute a solution that would be nice.

**Comment by gigermocas** [comment] 2023-12-13 16:15
Don't know if I'm following correctly, this should not trigger a compilation, I'm not changing any files here

**Comment by gigermocas** [comment] 2023-12-13 16:35
Ok, didn't knew it did that, wasn't expecting that through simply trying to copy text from the source file.

**Comment by jukzi** [comment] 2024-02-14 13:55
@gigermocas any contribution to make it better would be very welcome. I am closing this issue as "not planned". We could reopen if you could contribute a PR which makes it any better.

**Comment by gigermocas** [comment] 2024-04-02 11:05
Thanks, but the specific annotation that's causing issues for me is @XmlSeeAlso which is not TYPE_USE but USE, I guess that wouldn't help me much here.

**Comment by gigermocas** [comment] 2024-04-02 11:24
Content assist being slower in this instance may be unavoidable, but the thing that makes this extra processing more impactful is it being triggered during a simple select text + copy operation, which can cause an UI freeze, and is something that doesn't actually use any of that information (?).

**Comment by stephan-herrmann** [comment] 2024-04-02 12:03
> Content assist being slower in this instance may be unavoidable, but the thing that makes this extra processing more impactful is it being triggered during a simple select text + copy operation, which can cause an UI freeze, and is something that doesn't actually use any of that information (?).

Do we have any stack traces, witnessing such slow down on select + copy? Note that selecting segments of code in an editor is indeed a "semantic" operation, since the codeSelect() functionality is provided for clients that indeed want semantic information. 

Perhaps, semantic analysis is happening in situations that could be weeded out, e.g., because the selection cannot be matched to one individual program element.

**Comment by stephan-herrmann** [comment] 2024-04-02 12:10
> Thanks, but the specific annotation that's causing issues for me is @XmlSeeAlso which is not TYPE_USE but USE, I guess that wouldn't help me much here.

Aside: There is no such target as USE (the opposite of TYPE_USE annotations are declaration annotations), but I see that that annotation has `@Target(value=TYPE)`, so not a TYPE_USE annotation indeed.

But perhaps my reasoning was a bit quick: yes, it's TYPE_USE annotations that require re-iteration of super types, but (some of) this extra work happens no matter if we find any TYPE_USE annotations or not. So, the better criterion would be, whether `org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.integrateAnnotationsInHierarchy()` appears in any stack trace during a 'freeze'.

**Comment by stephan-herrmann** [comment] 2024-04-02 13:50
> I see that CompilationUnitScope.integrateAnnotationsInHierarchy() will always be called through: 

sure

> and indeed you can see it in both traces I gave on https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1728#issuecomment-1850042922

So, if this indicates that `integrateAnnotationsInHierarchy()` is not only called, but also consumes a lot of time, then we may want to start the following project:

Investigate if for some clients of the compiler (which?) annotations are completely irrelevant. If so, we may want to add another parameter to methods like `org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(CompilationUnitDeclaration, boolean)` -- say: `boolean resolveAnnotations`. Based on that flag, *perhaps* we could skip all or most of the `resolveAnnotations()` calls. This should make a difference indeed, as it will reduce the number of types to be read and analysed.

**Closed** 2024-04-14 16:26 UTC
Labels: performance
