### ISSUE TITLE
Open Type Hierarchy has lost its shortcut (F4)

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#1226] opened 2023-07-12 05:05 UTC
Since update to new release I noticed that the `F4` shortcut is no longer working to open the Type Hierarchy I also see the in the latest Eclipse-SDK-IDE:

![grafik](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1331477/c0b5ad4a-2ce5-4f5a-8ff8-80b92e826534)

Eclipse SDK
Version: 2023-09 (4.29)
Build id: I20230711-1800

**Comment by iloveeclipse** [comment] 2023-07-12 05:23
- wrong tracker
- duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/644

**Closed by iloveeclipse** 2023-07-12 05:23 UTC
