### ISSUE TITLE
Method not formatted when calling static import

### ISSUE THREAD

**Issue by V-Smeets** [eclipse-jdt/eclipse.jdt.core#609] opened 2022-12-20 12:51 UTC
OS: Debian bookworm
Eclipse: 2022-12, IDE for Enterprise Java
Formatter: default build-in Eclipse formatter

In case a method of a class contains a statement call to an other method that was included by an "import static", then that method is not formatted by eclipse. Other methods in the same class are not influenced by this problem.

In the attached zip file, I have a minimal maven project with just one test class "FormatTest". This class contains 3 methods:
- testNoWhen(): This method contains no statements. It is formatted without problems.
- testWhen(): This method calls the statement "when" that was statically imported from the Mockito class. The method "testWhen()" is not formatted by eclipse.
- testMockitoWhen(): This method calls the statement "Mockito.when()". It is the same call as in the previous method, but not with the class specified. In this way, the method "testMockitoWhen()" is correctly formatted.

[project-test.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10267676/project-test.zip)

To test it, open the class "FormatTest", change the format to some incorrect format and then press CTRL-F or menu source/Format to format the class. You will see that the method "testWhen()" is not corrected.

Regards,
Vincent

**Comment by melekhove** [comment] 2022-12-21 07:35
It is interesting, it looks like it has something to do with the method name ("when") and number of arguments. 
You can add to the project a simple class with "when" method.
`
public class ClassWithStatic {
	public static void when(int a) {
	}
}
`
and experiment with method name and number of arguments

**Comment by melekhove** [comment] 2022-12-21 10:20
Well, seems something wrong with parsing. The AST for the "FormatTest.java" created/used in formatter  looks like this:
```java
package test;
import static test.ClassWithStatic.when;
public class FormatTest {
  public void testWhen(){
  }
}
```
The body of the `testWhen` method is missing. Actually the AST should look like this:
```java
package test;
import static test.ClassWithStatic.when;
public class FormatTest {
  public void testWhen(){
    when(1);
  }
}```

**Comment by melekhove** [comment] 2022-12-21 13:16
Seems that reason of the problem is the following line https://github.com/eclipse-jdt/eclipse.jdt.core/blob/19f448f47c9e3e7339bae5bd9c1a9f5d24751b13/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/parser/Scanner.java#L5092
'lookBack' is reset periodically, so at some point 'mayBeAtGuard' returns wrong value because lookBack is empty.

**Comment by jarthana** [comment] 2023-06-05 05:01
Copying @mpalat

**Comment by MaisiKoleni** [comment] 2023-06-09 18:11
As indicated by the comment, I think allowing `TokenNameNotAToken` is technically wrong, but when I rewrote the code for "when", there were plenty of tests that required starting in the middle of statements / expressions, so I left it more or less "as is", accepting no token before `when`.

It would be best to remove that case, it requires many additional modifications to existing tests, though.

**Comment by MaisiKoleni** [comment] 2023-06-09 18:14
@jarthana is there already a PR / fix for that? I could adjust it further and be more restrictive, but I would need to rewrite more tests.

**Comment by jarthana** [comment] 2023-06-12 08:31
> @jarthana is there already a PR / fix for that? I could adjust it further and be more restrictive, but I would need to rewrite more tests.

No,  only a suggestion from Eugene.

**Comment by deathpat** [comment] 2023-09-29 16:28
Hello,
Any news regarding a fix ? 
Having the same issue this is so annoying that I installed a 2021 version of eclipse to work ... but it has other annoying bugs .. 
Thanks

**Comment by srikanth-sankaran** [comment] 2023-09-30 01:00
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1436 when merged (early next week) should address this.

**Comment by deathpat** [comment] 2023-09-30 06:33
> #1436 when merged (early next week) should address this.

Great news ! thanks !

**Closed** 2023-10-02 03:33 UTC
