### ISSUE TITLE
Open Declaration (F3) sometimes not working for "Pattern Matching for instanceof"

### ISSUE THREAD

**Issue by youngroman** [eclipse-jdt/eclipse.jdt.core#1288] opened 2023-08-14 18:28 UTC
simple code reproducing the issue in Eclipse 2023-06 on Windows 11:
```
	public void test(Object s) {
		if(s instanceof String x) {
			x.length(); // fails
		}
	}
```
when you F3 on the length method you only get a "Current text selection cannot be opened in an editor" error message in the StatusBar. no exception is thrown, which makes this different to all the other reported issues when Pattern Matching is used.

if you remove the curly braces it works:
```
	public void test(Object s) {
		if(s instanceof String x)
			x.length(); // works
	}
```
some more test cases, where it is not always obvious why it works or fails:
```
		if(s instanceof String x) {
			x.length(); x.length(); // 1st fails, 2nd works
		}

		if(s instanceof String x) {
			x.length(); x.length(); x.length(); // 1st fails, 2nd + 3rd works
		}

		if(s instanceof String x) {
			int i; x.length(); // works
		}

		if(s instanceof String x) {
			int i; x.length(); int j; // fails
		}

		if(s instanceof String x) {
			x.length(); int j; // fails
		}
```

**Comment by iloveeclipse** [comment] 2023-08-14 20:05
Looks related to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1278.

@srikanth-sankaran :  could you also please take a look here? If the fix is "simple", would be nice to have in 4.29.

**Comment by srikanth-sankaran** [comment] 2023-08-16 03:52
> Looks related to #1278.
> 
> @srikanth-sankaran : could you also please take a look here? If the fix is "simple", would be nice to have in 4.29.

I will follow up. Prior to my 4 weeks time away from work, I was investigating a cluster of problems related to pattern matching instanceof - Symptoms are varied: CCE during code selection, hover, hyperlink, completion etc. 

The crux of the problem is that, so far, there has not been a construct that JDT had to handle that happens to be an expression but introduces a new variable into the scope. This is a new kind of a scenario and while the main Parser seems to have been upgraded to handle this adequately by all indications, AssistParsers have not been suitably enhanced. 

There have been a series of band-aid fixes that have been slapped on top of each other to mask the problem, but this is completely failing as can be witnessed by the several variants of bug reports mentioned at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1195#issuecomment-1612277800

A full solution would have to back out half a dozen defect fixes and refix those problems first. Grammar changes are going to be needed too. 

My rough estimate would be that, 3-4 weeks of work would be needed to build, test and stabilize.

**Comment by youngroman** [comment] 2023-08-17 21:10
I started debugging my problem and managed to get it to work by removing the implementation of SelectionParser.checkRestartRecovery that was introduced with https://github.com/eclipse-jdt/eclipse.jdt.core/commit/b9c7228db069a63b5c1805833caad7a4bb92e2ab#diff-0c678004ba73b1ec55d117bbe52fb6fbe6c8228f918986a2c33abd32ca8e9e54 5 years ago.

#1278 seems to work as well with an empty checkRestartRecovery.

No idea if this helps and what checkRestartRecovery tried to solve back then, but it seems that re-doing some past fixes is a good choice.

**Comment by srikanth-sankaran** [comment] 2023-09-11 03:49
Same problem with while:

```
public class X {
	public void test(Object s) {
		while(s instanceof String x) {
			x.length(); // F3 on length fails
		}
	}
}
```

**Comment by srikanth-sankaran** [comment] 2023-09-11 05:31
Same problem with for loop. The uses of unopenable cannot be clicked on or F3ed to visit the declaration:
```
import java.util.ArrayList;

public class X {
	public void foo(ArrayList<Object> alo) {
		for (int i = 0; i < alo.size() && alo.get(i) instanceof String unopeanble; unopeanble.length()) {
			unopeanble.length();
		}
	}
}

```

**Comment by srikanth-sankaran** [comment] 2023-09-11 06:29
Similar problem with do-while:
```
import java.util.ArrayList;

public class X {
	public void foo(ArrayList<Object> alo) {
		int i = 0;
		do {
		}	while (!(alo.get(i) instanceof String unvisitable) || unvisitable.length() > 0);
	}
}
```

**Comment by srikanth-sankaran** [comment] 2023-09-12 07:24
The PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1349 fixes this problem and includes a regression test from here. I will close this as a duplicate

**Comment by srikanth-sankaran** [comment] 2023-09-12 07:24
Duplicate of #1195

**Comment by srikanth-sankaran** [comment] 2023-09-12 07:24
Duplicate of #1195

**Closed by srikanth-sankaran** 2023-09-12 07:24 UTC
