### ISSUE TITLE
Error: Syntax error on token "RestrictedIdentifierWhen", while expected

### ISSUE THREAD

**Issue by RalfNaujokat** [eclipse-jdt/eclipse.jdt.core#1518] opened 2023-10-27 10:51 UTC
Hi there!

After upgrading a project from Java 17 to Java 21 i got the following error:
`Syntax error on token "RestrictedIdentifierWhen", while expected`

The error was on the static imported when() of Mockito, so having code like
`when(something).thenReturn(something_else);`

This error pops up only, if that 'when' is the first instruction in a method.
So having one simple instruction (no matter what, afaik) gets it back to working.
Looks like some issue with the parser / syntax analyzer or what else.

The code is part of a Maven 3.9.5 project. 
This error does only occur in Eclipse and Java Version set to 21.
Compiling with (any) javac is not affected by this issue.

I managed to figure out, that this is not specific to that Mockito.when,
a very small sample (about 20 lines of code in two files) is attached.

Error occurs in
* Eclipse 2023-09 with Java 21 Plugin from Marketplace, latest updates installed
* Eclipse 2023-12-M1

Both are on Ubuntu 23.10 with
* GraalVM 21
* Oracle JDK 21 

greetings
  Ralf

**Comment by RalfNaujokat** [comment] 2023-10-27 10:51
package de.ralfn.bug;

public class Util
{
	public static void when( final Integer param )
	{
		System.out.println( param );
	}
}

**Comment by RalfNaujokat** [comment] 2023-10-27 10:51
package de.ralfn.bug;

import static de.ralfn.bug.Util.when;

public class ShowCase
{
	public static void main( final String[] args )
	{
		// remove or comment out the line below to see the error
		final int x;

		when( 42 );
	}
}

**Comment by iloveeclipse** [comment] 2023-10-27 10:59
Please try latest nightly build, AFAIK this problem should be fixed already.
https://download.eclipse.org/eclipse/downloads/drops4/I20231027-0140

**Comment by RalfNaujokat** [comment] 2023-10-27 11:08
Thanks for that info.
Will this be in 2023-12-M2,
what should be scheduled for today?

**Comment by iloveeclipse** [comment] 2023-10-27 11:17
I have to search, I don't know for sure in which build it was fixed, why not try out latest one?

**Comment by RalfNaujokat** [comment] 2023-10-27 11:26
Did it just right now.
You are right, the issue is fixed.

Thank for this!

**Comment by RalfNaujokat** [comment] 2023-10-27 11:27
Than was i quick fix!
:-)

**Closed** 2023-10-27 11:27 UTC

**Comment by iloveeclipse** [comment] 2023-10-27 11:56
OK, did a quick search: it is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/456 fixed by @srikanth-sankaran and I believe should be in M2 too.

**Comment by srikanth-sankaran** [comment] 2023-10-27 11:59
> OK, did a quick search: it is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/456 fixed by @srikanth-sankaran and I believe should be in M2 too.

Yep, that was one popular defect with more than half a dozen variants.
