### ISSUE TITLE
[BUG] `Syntax error, modifiers are not allowed here` on a `@deprecated` javadoc tag in package-info.java

### ISSUE THREAD

**Issue by Monniasza** [eclipse-jdt/eclipse.jdt.core#803] opened 2023-03-01 06:35 UTC
When trying to document a deprecated package using a `@deprecated` tag in javadoc, I get a syntax error even though the code AND Javadoc are correct
Eclipse version: 2022-09
### Expected result
There are no errors
### Actual result
`Syntax error, modifiers are not allowed here` from the beginning of the file inclusive to the package declaration exclusive
### Reproduction:
Create a package `abc` with following package-info.java:
```java
/**
 * @deprecated
 */
package abc;
```

**Comment by iloveeclipse** [comment] 2023-03-01 15:10
Hmm, I can't reproduce it in 4.27 master also not in 4.25.
Can you please attach the entire project, with .classpath / .settings folder?

**Comment by Monniasza** [comment] 2023-03-01 16:56
@iloveeclipse https://github.com/MultiMachineBuilder/MultiMachineBuilder/archive/refs/heads/master.zip

**Comment by iloveeclipse** [comment] 2023-03-01 17:39
OMG, it's using m2 / org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER, so can't be compiled in SDK. It can't find annotations library, probably they are resolved by that container.
Is there a way to have a self-contained example that does NOT use m2 container and can be imported into a "pure" SDK?

**Comment by Monniasza** [comment] 2023-03-02 06:27
I'm talking about Javadoc tags causing a syntax error, not annotations.

**Comment by iloveeclipse** [comment] 2023-03-02 06:32
And I'm talking about missing libraries which cause build problems (incomplete classpath), so I can't observe your problem because of that.

**Comment by srikanth-sankaran** [comment] 2023-11-03 09:51
I think this is the same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=569780 - a simple test case is available here: 
https://gist.github.com/tberne/d94623c9832df38033ba8fb812e74545

**Comment by srikanth-sankaran** [comment] 2023-11-03 09:53
>### Reproduction:
> Create a package `abc` with following package-info.java:
> 
> ```java
> /**
>  * @deprecated
>  */
> package abc;
> ```

This is missing the `@Deprecated` annotation which is necessary to reproduce the defect

**Comment by srikanth-sankaran** [comment] 2023-11-03 11:13
> The issues applies to the Javadoc tag, not an annotation

Right, but the annotation is essential to reproduce the problem. Isn't it ?

**Comment by Monniasza** [comment] 2023-11-03 13:03
Annotation is not required, only the Javadoc tag

**Comment by srikanth-sankaran** [comment] 2023-11-03 13:09
This file 

https://gist.github.com/tberne/d94623c9832df38033ba8fb812e74545

Shows the problem but only if both the tag and annotation exist.

**Comment by tberne** [comment] 2023-11-03 14:42
Hi, guys, 
I've opened the [original bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569780) almost three years ago.
I also am the proprietary of the [given gist that can reproduce the problem](https://gist.github.com/tberne/d94623c9832df38033ba8fb812e74545).

As far as I can remember, _both_ were required: annotation and javadoc tag (although the annotation could be pretty much anything).

**Closed** 2024-03-07 06:34 UTC
