### ISSUE TITLE
[21] Internal compiler error

### ISSUE THREAD

**Issue by boris-petrov** [eclipse-jdt/eclipse.jdt.core#1727] opened 2023-12-11 10:55 UTC
```java
class Main {
	public Object foo(Object value) {
		return switch (value) {
			case String string -> {
				try {
					yield string;
				} catch (IllegalArgumentException exception) {
					yield string;
				}
			}
			default -> throw new IllegalArgumentException("Argument of type " + value.getClass());
		};
	}
}
```

This causes an `Internal compiler error: java.util.EmptyStackException at java.base/java.util.Stack.peek(Stack.java:103)`.

**Comment by srikanth-sankaran** [comment] 2023-12-12 05:34
Reproduced, I will take a look

**Comment by srikanth-sankaran** [comment] 2023-12-12 05:35
Same as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394 - Disabling `CompilerOptions.OPTION_UseStringConcatFactory` makes the problem go away.

**Comment by srikanth-sankaran** [comment] 2023-12-12 05:36
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394

**Closed by srikanth-sankaran** 2023-12-12 05:36 UTC

**Comment by srikanth-sankaran** [comment] 2023-12-13 12:01
We have a fix merged in for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394 that includes a test from here
