### ISSUE TITLE
[Modernization] Should we generify the DOM APIs ?? 

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.core#3341] opened 2024-11-24 14:44 UTC
Should this code be processed without error?

```java
...
import org.eclipse.jdt.core.dom.Modifier;
import org.eclipse.jdt.core.dom.FieldDeclaration;
...
private boolean isFieldStatic(FieldDeclaration field) {
	    return field.modifiers().stream()
	        .filter(Modifier.class::isInstance) 
	        .map(Modifier.class::cast) 
	        .anyMatch(Modifier::isStatic); 
	}
```
I get "The type Modifier does not define isStatic(Object) that is applicable here" on the last line. (Please ignore errors about the semantic)

In contrast to that this code does not get an error:

```java
private boolean isFieldStatic(FieldDeclaration field) {
	    return field.modifiers().stream()
	        .filter(Modifier.class::isInstance)
	        .map(Modifier.class::cast)
	        .anyMatch(modifier -> ((Modifier) modifier).isStatic());
	}
```

Version: 2024-12 M3 (4.34.0 M3)
Build id: 20241116-0259

**Comment by srikanth-sankaran** [comment] 2024-11-25 00:42
Did it work in earlier versions ? 
A standalone reproducer that stubs out the concerned classes would be very welcome.

**Comment by jukzi** [comment] 2024-11-25 08:16
Does it compile with javac?

**Comment by Madjosz** [comment] 2024-11-26 11:18
I created a reproducer:
```java
import java.util.stream.Stream;
public class ModifierTest {

    private class Modifier {
        public boolean isStatic() { return false; }
        public static boolean isStatic(int flags) { return false; }
    }

    public static void main(String[] args) {
        Stream s = Stream.of();
        s.filter(Modifier.class::isInstance)
         .map(Modifier.class::cast)
         .anyMatch(Modifier::isStatic);
    }
}
```
The problem hereby is that `FieldDeclaration.modifiers()` returns a raw `List`. With that all generics get lost on any of the `Stream` methods and one gets in `javac` (16+)
> `ModifierTest.java:13: error: incompatible types: invalid method reference`
> `         .anyMatch(Modifier::isStatic);`
> `                   ^`
> `    incompatible types: Object cannot be converted to int`

and in `ecj` (3.38.0)
> `ERROR in ModifierTest.java (at line 13)
> `        .anyMatch(Modifier::isStatic);`
> `                  ^^^^^^^^^^^^^^^^^^`
> `The type ModifierTest.Modifier does not define isStatic(Object) that is applicable here`

So all is fine in this case.

Of course hardcasting the instance will not make problem. Providing the generics also makes this compile in both compilers.

**Comment by srikanth-sankaran** [comment] 2024-11-26 11:32
Our (still crystalizing) policy is not to fix any problems that may involve raw types ;-)
Larger question is modernizing the DOM APIs by generifying them. I'll initiate a discussion within JDT.

**Comment by srikanth-sankaran** [comment] 2024-11-26 11:34
What is involved, what could be the impacts ? Pros/cons ? Who may be impacted ?

**Comment by Madjosz** [comment] 2024-11-26 11:36
Since `ecj` and `javac` behave the same in this case I wouldn't even consider this a problem/bug. If this behaviour is according to the specs is another question I am not competent enough to answer.

**Comment by srikanth-sankaran** [comment] 2024-11-26 11:39
> Since `ecj` and `javac` behave the same in this case I wouldn't even consider this a problem/bug. If this behaviour is according to the JLS is another question I am not competent enough to answer.

Sure, hence the hijack to larger question: Should we modernize the APIs by using generics ?

**Comment by Madjosz** [comment] 2024-11-26 11:39
This ticket looks like a duplicate of #1622 now.

**Comment by srikanth-sankaran** [comment] 2024-11-26 11:41
> This ticket looks like a duplicate of #1622 now.

Thanks, closing as duplicate.

**Closed by srikanth-sankaran** 2024-11-26 11:41 UTC
